<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<parent>
		<artifactId>kbee</artifactId>
		<groupId>com.novamens</groupId>
		<version>8.5-SNAPSHOT</version>
		<relativePath/>
	</parent>

	<artifactId>aerolineas-lib</artifactId>
	<name>${project.artifactId}</name>
	<description>Aerolineas Tools.</description>
	
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
	
	<developers>
		<developer>
			<id>aferraria</id>
			<name>Alejo Ferraria</name>
			<email>aferraria@novamens.com</email>
		</developer>
		<developer>
			<id>atolomei</id>
			<name>Alejandro Tolomei</name>
			<email>atolomei@novamens.com</email>
		</developer>
		
		<developer>
			<id>grodriguez</id>
			<name>Germán Rodriguez</name>
			<email>grodriguez@novamens.com</email>
		</developer>
	</developers>
	
	<dependencies>
		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-app-content</artifactId>
			<version>8.5-SNAPSHOT</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-api-server</artifactId>
			<version>8.5-SNAPSHOT</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-api-client</artifactId>
			<version>8.5-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-app-content</artifactId>
			<version>8.5-SNAPSHOT</version>
		</dependency>
		<dependency>
  			<groupId>org.ccil.cowan.tagsoup</groupId>
  			<artifactId>tagsoup</artifactId>
  			<version>1.2.1</version>
		</dependency>
	</dependencies>
</project>