create=Create

titlecolumn = Title
iconcolumn = Icon
sizecolumn = Size
filecolumn=File

contextmenu.open = Open
contextmenu.create = Create
contextmenu.delete=Delete

datecolumn=Uploaded
thumbnailcolumn=Thumbnail

one-for-each=
one-for-each=<span class="ago" style="margin-left: 6px;">1 for Each</span> 
one-for-each-desc=

one-for-all=<span class="ago" style="margin-left: 6px;">1 for All</span>
one-for-all-desc= 

