
title=Note - 
default.welcome_title=What is My Notes ?
default.welcome_text=<p>The Notepad is a panel easily accesible from the toolbar where you can create and manage simple notes.</p><p>Notes can include&nbsp;<a href=\"http://novamens.com\">links</a> and formats like <strong>bold</strong> or <em>italic</em>.</p><p>Notes are private, no one else can read or edit them.</p>
			