<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<artifactId>kbee</artifactId>
		<groupId>com.novamens</groupId>
		<version>8.5-SNAPSHOT</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>kbee-dm-hibernate</artifactId>
	<name>${project.artifactId}</name>

	<description />
	<developers>
		<developer>
			<id>aferraria</id>
			<name>Alejo Ferraria</name>
			<email>aferraria@novamens.com</email>
		</developer>
	</developers>
	<scm>
		<connection>
			scm:git:ssh://alejo@git.hq.novamens.com/var/git/novamens/hibernate.git
		</connection>
		<developerConnection>
			scm:git:ssh://alejo@git.hq.novamens.com/var/git/novamens/hibernate.git
		</developerConnection>
	</scm>

	<dependencies>

		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-model-dom</artifactId>
			<version>${kbee-version}</version>
		</dependency>

		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-services-spring</artifactId>
			<version>${kbee-version}</version>
		</dependency>

		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-dm-indexer-api</artifactId>
			<version>${kbee-version}</version>
		</dependency>

		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-services-model</artifactId>
			<version>${kbee-version}</version>
		</dependency>

		<!--  =========  External  =========================   -->

		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-core</artifactId>
			<version>${hibernate-version}</version>
		</dependency>

		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-entitymanager</artifactId>
			<version>${hibernate-version}</version>
		</dependency>

		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-ehcache</artifactId>
			<version>${hibernate-version}</version>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>${jackson-databind-version}</version>
		</dependency>

		<dependency>
			<groupId>com.codesnippets4all</groupId>
			<artifactId>quick-json</artifactId>
			<version>${quick-json-version}</version>
		</dependency>
	</dependencies>
</project>