<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<artifactId>kbee</artifactId>
		<groupId>com.novamens</groupId>
		<version>8.5-SNAPSHOT</version>
	</parent>

	<modelVersion>4.0.0</modelVersion>
	<artifactId>kbee-webapp</artifactId>
	<packaging>war</packaging>
	<description>kbee</description>

	<build>
		<plugins>
			<plugin>
				<groupId>org.liquibase</groupId>
				<artifactId>liquibase-maven-plugin</artifactId>
				<version>4.16.1</version>
				<configuration>
					<changeLogDirectory>
						/src/main/resources/META-INF/db-evolution</changeLogDirectory>
					<propertyFile>
						/src/main/resources/META-INF/db-evolution/liquibase.properties</propertyFile>
					<changeLogFile>db.changelog-master.xml</changeLogFile>
				</configuration>
			</plugin>

			<plugin>
				<artifactId>maven-antrun-plugin</artifactId>
				<version>1.8</version>
				<executions>
					<execution>
						<id>main-class-copy</id>
						<phase>prepare-package</phase>
						<configuration>
							<tasks>
								<copy
									todir="${project.build.directory}/${project.artifactId}-${project.version}/">
									<fileset
										dir="${project.build.directory}/classes/">
										<include name="**/Main.class"></include>
									</fileset>
								</copy>
							</tasks>
						</configuration>
						<goals>
							<goal>run</goal>
						</goals>
					</execution>

					<!-- extract release package for maven-assembly-plugin -->
					<execution>
						<phase>prepare-package</phase>
						<configuration>
							<tasks>
								<echo
									message="unzipping release package empty folders"></echo>
								<unzip src="release-package/emptyfolders.zip"
									dest="release-package/"></unzip>
							</tasks>
						</configuration>
						<goals>
							<goal>run</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<artifactId>maven-war-plugin</artifactId>
				<version>3.3.2</version>
				<configuration>
					<!--<outputDirectory>${project.build.directory}/release/lib</outputDirectory>
					<packagingExcludes>WEB-INF/lib/</packagingExcludes>-->
					<archive>
						<manifestEntries>
							<Class-Path>../config/</Class-Path>
							<version>${git.commit.time}.${git.commit.id.abbrev}</version>
						</manifestEntries>
						<manifest>
							<mainClass>com.novamens.content.web.Main</mainClass>
							<addClasspath>true</addClasspath>
						</manifest>
					</archive>
				</configuration>

			</plugin>

			<plugin>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>${maven-javadoc-plugin-version}</version>
				<configuration>
					<source>${java-version}</source>
					<links>
						<link>https://docs.oracle.com/javase/11/docs/api/</link>
					</links>
					<encoding>UTF-8</encoding>
					<notimestamp>true</notimestamp>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>


			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>${maven-jar-plugin-version} </version>  <!--   2.3.1  -->
				<configuration>
					<outputDirectory>${project.build.directory}/release/lib</outputDirectory>
					<archive>
						<manifest>
							<mainClass>com.novamens.content.web.Main</mainClass>
							<addClasspath>true</addClasspath>
						</manifest>
					</archive>
				</configuration>
			</plugin>

			<!-- assembly:attached goal -->
			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<descriptors>
						<!-- ruta al descriptor del empaquetado: por convención
						se incluye en el directorio assembly -->
						<descriptor>assembly-release.xml</descriptor>
					</descriptors>
					<finalName>app</finalName>
					<appendAssemblyId>false</appendAssemblyId>
				</configuration>
				<!-- uncomment for creating release package by default
				<executions>
				   <execution>
					  <id>package-native</id>
					  <phase>prepare-package</phase>
					  <goals>
						 <goal>attached</goal>
					  </goals>
				  </execution>
				</executions>
				-->
			</plugin>
		</plugins>
	</build>

	<reporting>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>jdepend-maven-plugin</artifactId>
				<version>2.0</version>
			</plugin>
		</plugins>
	</reporting>

	<profiles>
		<profile>
			<id>externalDependenciesWar</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-dependency-plugin</artifactId>
						<executions>
							<execution>
								<id>copy-dependencies</id>
								<phase>package</phase>
								<goals>
									<goal>copy-dependencies</goal>
								</goals>
								<configuration>
									<outputDirectory>
										${project.build.directory}/release</outputDirectory>
									<overWriteReleases>false</overWriteReleases>
									<overWriteSnapshots>false</overWriteSnapshots>
									<overWriteIfNewer>true</overWriteIfNewer>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>assembly</id>
			<build>
				<plugins>
					<!-- assembly:attached goal -->
					<plugin>
						<artifactId>maven-assembly-plugin</artifactId>
						<configuration>
							<descriptors>
								<!-- ruta al descriptor del empaquetado: por
								convención se incluye en el directorio assembly -->
								<descriptor>assembly-release.xml</descriptor>
							</descriptors>
							<finalName>app</finalName>
							<appendAssemblyId>false</appendAssemblyId>
						</configuration>
						<executions>
							<execution>
								<id>package-native</id>
								<phase>package</phase>
								<goals>
									<goal>attached</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>

			<id>idoc</id>

			<!-- dependencies>
				<dependency>
					<groupId>com.novamens</groupId>
					<artifactId>idoc-resources</artifactId>
					<version>${kbee-version}</version>
					<scope>compile</scope>
				</dependency>
				
				
				<dependency>
					<groupId>com.novamens</groupId>
					<artifactId>idoc-lib</artifactId>
					<version>${kbee-version}</version>
					<scope>compile</scope>
				</dependency>
			</dependencies-->

		</profile>
		<profile>
			<id>aerolineas</id>
			<dependencies>
				<dependency>
					<groupId>com.novamens</groupId>
					<artifactId>aerolineas-lib</artifactId>
					<version>${kbee-version}</version>
					</dependency>
			</dependencies>
		</profile>
		<profile>
			<id>IDE</id>
			<build>
				<resources>
					<resource>
						<directory>src/main/webapp</directory>
					</resource>
					<resource>
						<directory>src/main/resources</directory>
					</resource>
				</resources>
			</build>
		</profile>
	</profiles>

	<dependencies>


	
				<dependency>
					<groupId>com.novamens</groupId>
					<artifactId>aerolineas-lib</artifactId>
					<version>${kbee-version}</version>
					<scope>compile</scope>
				</dependency>
				

		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-content-model</artifactId>
			<version>${kbee-version}</version>
		</dependency>

		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-app-content</artifactId>
			<version>${kbee-version}</version>
		</dependency>

		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-api-server</artifactId>
			<version>${kbee-version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-api-client</artifactId>
			<version>${kbee-version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>p6spy</groupId>
			<artifactId>p6spy</artifactId>
			<version>${p6spy-version}</version>
		</dependency>

		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>${postgres-jdbc-version}</version>
			<scope>runtime</scope>
		</dependency>


		<!-- https://mvnrepository.com/artifact/org.slf4j/jcl-over-slf4j -->

		<dependency>
			<!-- 	
					JAXB provides an API and tools that automate the mapping between XML documents
			and Java objects. 
					https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api
			-->
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>2.3.1</version> <!-- 5/2022 -->
		</dependency>

		<dependency>
			<!--
				Old JAXB Core module. Contains sources required by XJC, JXC and Runtime modules
			with dependencies.
			-->
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-core</artifactId>
			<version>4.0.1</version> <!-- 12/2022  -->
		</dependency>

		<dependency>
			<!-- 
				Old JAXB Runtime module. Contains sources required for runtime processing.
			-->
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-impl</artifactId>
			<version>4.0.1</version> <!-- 12/2022  -->
		</dependency>

		<dependency>
			<!--
				Liquibase is a tool for managing and executing database changes.
				https://mvnrepository.com/artifact/org.liquibase/liquibase-core
			-->

			<groupId>org.liquibase</groupId>
			<artifactId>liquibase-core</artifactId>
			
			<version> ${liquibase-version}</version>  <!--
			4.17.2 -->
			<exclusions>
				<exclusion>
					<artifactId>logback-classic</artifactId>
					<groupId>ch.qos.logback</groupId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-server</artifactId>
			<version>${jetty-version}</version>
		</dependency>

		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-webapp</artifactId>
			<version>${jetty-version}</version>
		</dependency>

		<!-- <dependency> 
				<groupId>javax.activation</groupId> <artifactId>activation</artifactId>
				<version>1.1.1</version> 
		</dependency> -->

	</dependencies>


	<developers>
		<developer>
			<id>Ferraria</id>
			<name>Alejo</name>
			<email>aferraria@novamens.com</email>
			<roles>
				<role>Software design and development</role>
			</roles>
		</developer>
		<developer>
			<id>Tolomei</id>
			<name>Alejandro</name>
			<email>atolomei@novamens.com</email>
			<roles>
				<role>Software design and development</role>
			</roles>
		</developer>
	</developers>
</project>