column.dow = Day
column.date=Date
column.time = Hour
column.user = User

column.total=Total
column.username=Username
column.lastname=Name

column.firstname=Firstname


column.portal=Portal

column.version=Version

column.portal=Portal/Section