column.dow = Day
column.date=Date
column.time = Hour
column.user = User
		
column.page=Page 
column.page_type=Type
column.site_title=Portal/Section 
column.content_title=Content
column.version=Version
column.content_oid=OId
column.content_link=Link


column.xid=OId / Id
optional=Optional