column.sendername=Sent by 
column.senderfirstname=Firstname
column.contentoid=Oid
column.contentid=Content ID
column.contentversion=Version
column.title=Alert Title
column.type=Type
column.isalert=Alert
column.isbillboard=Billboard
column.datesend=Sent 
column.dateread=Read
column.startpub=Publish From
column.endpub=Publish To

receiver=User (Alert Receiver)
optional=Optional

column.contenttitle=File