ok-message = The action was executed successfully. 
errors-message = The action was executed with errors.
button.submit = Execute
button.submiting = Working
actions = Action
ok=Delete
delete=Delete
cancel=Cancel
close= < Back to Dataset Values  
howitworkstitle=How it Works
howitworks=<p>Values that have Files Classified or Relationships to other Information Entities in the system can not be deleted. Please check the results in the table below after the process.</p>





