published={0} published 

expand=Expand 
collapse=collapse  

open=Open File

not-in-library= {0} not in Library
expand-collapse=Expand/Collapse Note

mark-read=Mark as Read
mark-read-open=Mark as Read and Open

menu.readandopen = Mark as Read and Open
menu.read = Mark as Read
menu.delete = Remove