notifications.acceptall=Mark all as read 
notifications.close=Close

notifications.title=NOTIFICATIONS
notifications.hassent=has sent you
notifications.accept=Mark as read
notifications.notfound=not found in Workspace.
