notifications.acceptall=Marcar todos como leídos 
notifications.close=Cerrar

notifications.title=Alertas
notifications.hassent=le ha enviado 
notifications.accept=Marcar como leído
notifications.notfound=no encontrado en el Area de Trabajo.