
download-excel=Download (xslx)
favorites=My Bookmarks
property.name=List Name
property.description=Description

property.title=Name Favorite
addlist=Add list

close=close

clearall=clear all filters
addlist=add list
removeall=delete all lists


apply=Apply to grid

save=save
cancel=cancel

edit-list-name=Edit list name
empty-list=Empty list
delete-list=Delete list
download-excel=Download (MS Excel)

add-to-main=Add to Main Panel
share=Open List page