removeall=delete all queries
working=working
clearall=clear all filters
close=close


add-to-main=Add to Main Panel
add-home=Add to Dashboard
remove-home=Remove from Dashboard

property.name=Query Name
property.title=Name Favorite
close=close



delete=Delete
save=save
cancel=cancel

edit=Edit Query name

