
add-favorites=Add to Favorites
remove-favorites=Remove from Favorites
download=Download
send-email=Share


restore.content=Restore Content
restore.content=Restore My Tasks


restore.workspace=Restore to Workspace
edit=Edit
edition=Edition
