
members=Members
roles = Roles

editor.role = Role

console.name = Roles

searchplaceholder=Search in Roles

rolesconsole.contextmenu.open = Open
rolesconsole.contextmenu.audittrail =Audit Trail
rolesconsole.contextmenu.delete = Delete
rolesconsole.contextmenu.delete.confirmation = Please confirm you want to delete Role <b>{0}</b>

rolesconsole.column.isdefault=Assign by Default
rolesconsole.column.alias=Alias 
rolesconsole.column.type = Type
rolesconsole.column.name = Name
rolesconsole.column.scope = Classifier
rolesconsole.column.condition = Condition 
rolesconsole.column.modified = Modified
rolesconsole.column.modifiedby = Modified by
rolesconsole.column.groups=Sections Enabled
rolesconsole.column.created = Created
rolesconsole.column.isapi=API
rolesconsole.column.description=Description
yes=<span class="yes">Yes</span>
no=<span class="no">No</span>