



role-rights=Role Rights
entity-rule=Role Permissions 

entity=Dynamic
general=General

info=Info

property.name = Name
property.id = Id
property.roleclass = Role Type
property.entitySet = Dynamic
property.classifier = Entity
classifier.help=This field is read only


property.general-rights=General Rights
property.description=Description
property.alias=Alias 
alias.help=Used by API and internal Commands
property.apiEnabled=API
property.isDefault=Assign by default to new Users  
isDefault.help=Select <b>Yes</b> if you want new users to have this Role. Only General Roles can be Default.
 

property.groupsList = Groups (users with this Role will belong to)
groupsList.help = Users with this Role will belong to these Groups.
 

property.groupsList = Groups (users with this Role will belong to)
groupsList.help = Users with this Role will belong to these Groups.


workflow=Workflow
content=Libraries
settings=Settings
admin=Admin
general=General
factory=Factory

