



issystem=This is a system Content Template, only root user can edit it. 
property.description=Description
description.help=this is the help.

contentClass.help=Low level Java Class. If you don't know what class to use select the standard <b>iDoc</b>. This field may be read only (except for <span class="only-root">root</span>)

property.linkResources=Resources of type Link 
linkResources.help=Select <b>Yes</b> if section Resources can include Links.

property.treeFileResource=Resource of type Tree File 
treeFileResource.help=Select <b>Yes</b> if this Content Template can include a Tree File


property.externalReference=Elements are just a simple URL
externalReference.help=Some UI elements use the fact that this Content Template is an external reference (like an external website) to open the reference directly.

external=External

external-title=External reference
property.res=Resources
property.tit=Resources (Title)

relations-title = Relationships

isapi=This Content Template is used by the API. Modifying the <b>Name</b>, <b>Attributes</b> or <b>Status</b> may affect the electonic interface.
structure=Info
edition=Creation and Edition
semantic=Content and Media type

property.PrivateNotes=Internal Information

templates=Yes


property.contentclass=Class (only root)

contentbase=No

property.ComplianceCabinet=Compliance
yes=Yes
no=No


property.instanceTimeBasedNotification=Supports instance based notifications 


property.customAttributes=Custom Tags
property.iscustomattributes=Custom Tags
property.isAd=Is Ad

standard=No
kbase=Yes

templateorcontentbase=Belongs to Library
property.KnowledgeBaseCabinet=Knowledge Base

property.contentClassCode=Alias 

contentClassCode.help=Used internally by API, logs and reports. Short code that identifies this Content Template. This field may be read only (except for <span class="only-root">root</span>)


property.contentclasscode=code

private-notes=Internal Information
text=Text
Notes=Notes
custom-attributes=Custom Tags

treefile=File Explorer
resources=Resources

property.abstract_label=Public Notes / Abstract (Title)
property.private_notes_label=Internal Information (Title)
property.customattributes_label=Custom Tags (Title)
property.text_label=Text (Title)
property.contentclasscode=Code

fields=Main Sections

property.Resources=Resources List
property.ResourcesLabel=Resources <i>List</i> (Title)
property.TreeFile=Resources Tree
property.TreeFileLabel=Resources <i>Tree</i> (Title)

property.includesRelationshipsByCriteria = Includes Criteria Relationships <span style="font-weight: normal;">(outbound)</span>
includesRelationshipsByCriteria.help=Computing this field is costly, we recommend to select No if not sure.

property.acceptsRelationshipsByCriteria = Accepts Criteria Relationships <span style="font-weight: normal;">(inbound)</span>
acceptsRelationshipsByCriteria.help=Computing this field is costly, we recommend to select No if not sure. 

Resources.help=Resources List and Tree are mutually exclusive (they can not be both True).
TreeFile.help=Resources List and Tree are mutually exclusive (they can not be both True).
