resource-tags=Resource Tags
resource-tags-info= A <a href="/model/resourcetags" target="_blank">Resource Tag</a> is a tag applied to a Resource (pdf, xlsx, ...) added to a content. <br/> \
Resource tags are designed as a way to group resources and apply permissions to them. <br/> \
Example: a <b>Compliance File</b> that groups resources under the tags: <i>'Property'</i> (Submitted by the Property) and <i>'Compliance'</i> (added by the Compliance Analyst).