
sort=Sort Elements
title={0} Structure

structure-for-eforms = <a href="/model/classifiers" target="_blank">Classifiers</a> and <a  href="/model/attributes" target="_blank">Attributes</a> that ca be used by the Forms of this Content Template.
