

apply-default=apply default values

test-macro=Test title macro

subtitle=Subtitle
title=Title
display=Display
			
property.isTitleEditable=Title editable 
isTitleEditable.help=Whether users can edit the title or it will be generated just by the rule

property.consoleSubtitleRule=Tasks Subtitles 
consoleSubtitleRule.help=Macro to generate subtitles in Consoles. Click on the (i) for more help.

property.portalsSubtitleRule=Library and Portals Subtitles
portalsSubtitleRule.help=Macro to generate subtitles in Library Portals and selectors. Click on the (i) for more help. 


property.titleMacro = Title Macro
titleMacro.help=Macro para generar títulos de los documentos en las tareas. click en la <b>( i )</b> para ayuda.


property.titleScript = Title Script
titleScript.help = Example: <#if cliente??>${cliente}</#if> <#if tipodocumento??> - ${tipodocumento}</#if> <#if fechareferencia??> - ${fechareferencia?string["dd/MM/yy"]}</#if>


property.titleRuleType = Title Rule Type
titleRuleType.help = Macro -> Expresión IQL. <br/>
titleRuleType.help = Script -> JS con variables de Contexto KBEE. Ejemplo: <#if cliente??>${cliente}</#if> <#if tipodocumento??> - ${tipodocumento}</#if> <#if fechareferencia??> - ${fechareferencia?string["dd/MM/yy"]}</#if>



property.defaultViewMode = Default View 
resources=Resources
