launchers.error.constraint = The procedure has processes that executed. It is not possible to delete it. 

start=Users or Groups that can start this Workflow. <br />Select a Group if you want to grant the permission to all Users from that Group
