
launcher.label = Process Launcher





launcher.info=A Process Launcher starts a  Business Process. \
They can be used from more than one context (such as new files from <b>My Tasks</b>, \
Check out from <b>Library</b>,  via the electronic <b>API</b>, and others).

property.description=Description
description.help=Text published in "New" menus (for example in <a href="/myhome" class="btn-link">the front page</a>) when the user clicks the [i]. 

start=Users or Groups that can start the Business Process

open-procedure=Open Business Process definition
property.label=Name
property.launcherGroup=Group


property.classifiersrules = Set Classifier
property.classifier = Classifier
property.value = Value



property.enabled=My Tasks
property.apiEnabled = Api and Rules


 

property.library = Library
library.help=Yes -> add this Launcher to <b>Library</b>

property.condition = Condition

property.procedure=Business Process 

enabled.help=Yes-> Add to <b>Mis Tareas</b>
label.help=Etiqueta en botón <b>Nuev</b> en <b>Mis Tareas</b>,  y acción <b>Crear copia de Trabajo</b> en <b>Biblioteca</b>

condition.help = Conditions that the content must meet in order for the initiator to be used expressed in a script that must return true or false as a functional value 

procedure.help=<b>Business Process</b> 
read-only=Read only

launcherGroup.help=new in <b>My Tasks</b>


security.section = Security

contexts.section = Applies to
start.section = On Startup
launcher.label = Process Launcher

launcher-info=A Process Launcher starts a workflow from the Home page or My Tasks (for new files), or the Library (when a working copy is created).
Un iniciador de proceso es el responsable de iniciar un proceso de trabajo desde la portada, mis tareas o al crear una copia de trabajo en la Biblioteca.
launcher-name = Process Launcher - {0}

start=Users or Groups that can start this Workflow. <br />Select a Group if you want to grant the permission to all Users from that Group
start=Start

open-procedure=Open Business Process Editor

property.label=Label
label.help=

property.enabled=My Tasks Launcher 
enabled.help=Yes. Add this launcher to <b>My Tasks</b>

property.apiEnabled=Api and Rules Launcher

property.mobile=Mobile 

property.library = Library Launcher 
library.help = Add this launcher to <b>Library</b>

property.procedure=Business Process 
procedure.help=Select the <b>Procedure</b>. The Launcher will create a copy of the Model Procedure. 
read-only=This field can not be edited

property.launcherGroup=Launcher List
launcherGroup.help=Launcher lists group launchers in menus 

property.launchergroup=Launcher List
launchergroup.help=This is the list in button <b>New</b> in <b>My Tasks</b>

property.classifiersrules = Set classifiers in
property.classifier = Classifier 
property.value = Value
property.useTemplate = Templates

property.attributesrules = Set Attribute
property.attribute = Attribute
attributesrules.help =

property.script = Execute JS Script 

property.condition = Condition
condition.help = Conditions that the content must meet in order for the launcher to be used

property.description=Description
description.help=This text is displayed n "New File" menus, when the user clicks on the (i)

property.router = Initial Task
router.help = Optional Javascript to define the initial task of the process. It must return the identifier of the selected task as a functional value. If the script is not defined or its result is not recognized , the initial task of the process will be the one marked as such in the procedure