
musthavecapitalletter    = Password does not have capital letters, it must have at least 1 capital letter.
musthavedigit			 = Password does not have digits, it must have at least 1 digit.
minimunlength			 = The password must have at least 8 characters.

service.enabled = Enabled
service.disabled = Disabled
organization=Organization
externalId=External Id
emailservice=Alerts and Emails
consoles=Consoles
description=Description
tipoftheday=Tip of the day
portal=Portal module
type=Type

other=Other
calendar=Calendar

globaltipoftheday.help=Applies to all users
property.globaltipoftheday=Tip of the Day

cabinet=Cabinet


property.defaultpassword=Default Password
defaultpassword.help=Default password for new Users (leave blank if you want to force users to enter a new Password). <br />If not blank this field must have \
a minimum of <b>8 characters</b>, must have at least <b>1 capital letter</b> and at least <b>1 digit</b>.

property.locale=Language

property.CabinetTemplate=Templates
property.CabinetKnowledgeBase=Knowledge Base
property.CabinetExternal=External
property.logo=Logo
logo.help=The logo should have 45px height.

property.portalLibrary=Portals

property.externalId=OneSite Id
property.storageType=Default Storage
property.encryptFiles=Encrypt Files

property.timezone=Time Zone

api-storage=API and File Storage

externalid.helptext=Domain Id used by external applications
portals=Portals