
editor.newdomain = Basic Info

editor.stats = Storage
editor.settings = Settings
editor.cabinets = Libraries
editor.audit=Audit Trail
editor.emailsettings=Alerts and Emails
editor.calendar=Calendar
editor.login=Login page


editor.rootuser=Root User
editor.quotas=Usage
editor.advanced=Advanced  
api-info=API 

property.name = Name
property.address = Addresss
property.description = Description
property.organization = Organization
property.type = Type
property.website = Website
property.tipoftheday=Show Tip of the Day
property.portal=Portals
portal.help= Requires Portal License


property.eMailServiceStatus = Status
property.eMailServiceNoReply = No Reply Address
property.consolesShowResources = Show resources in expanded panel
property.consolesPersistLabels = Keep Label on File in Library
consolesPersistLabels.help=

system.status.title= Server
system.status.section.application=Application
system.status.section.platform=Platform
system.status.section.server =Server

meta.title = Domain Info
meta.keywords = Domain Info
