service.enabled = Enabled
service.disabled = Disabled

organization=Organization
emailservice=Alerts
consoles=Consoles
description=Description
portal=Portal

emailservice.help=Applies to all users
tipoftheday.help=Applies to all users

disclaimer-basic=This selector applies to <b>Send File by Email</b> and <b>Notification Rules</b>. <b>Task Alerts</b> are available in the Premium Version. <br />They allow you to receive emails when a new file has been added to your Tasks. If you would like to have this option, please contact your sales rep for additional information.
			
disclaimer-premium=This selector applies to all emails sent by the system.  If you want to set up your personal emails please go to <a class="btn-link" href="/myaccount" target="_blank"><b>User Settings</b> (Tab Account)</a>.