form0 = {"type":"section","name":"form","components":[\
			\
			{"type":"multiple choice","name":"multiplechoice","label":"Multiple Choice","choices":[ \
				{"type":"choice","name":"choice1","label":"Choice 1","enabledTextInput":false},\
				{"type":"choice","name":"choice2","label":"Choice 2","enabledTextInput":false},\
				{"type":"choice","name":"choice3","label":"Choice 3","enabledTextInput":false}\
			]},\
			\
			{"type":"text field","name":"field1","label":"Field 1", "enabledCondition": "choice1"}, \
			\
			{"type":"classifier autocomplete","name":"selector1","classifierId":"1501","label":"Selector 1"}, \
			\
			{"type":"classifier combo","name":"selector2","classifierId":"1501","label":"Selector 2"} \
		]}
		
		
form2 = {"type":"section","name":"form","components":[\
			\
			{"type":"classifier combo","name":"type","classifierId":"1500","label":"Document Type", "cssClass":"col-xs-6 col-lg-6 col-md-6"}, \
			{"type":"classifier combo","name":"status","classifierId":"1501","label":"Status", "cssClass":"col-xs-6 col-lg-6 col-md-6"}, \
			{"type":"classifier autocomplete","name":"site","classifierId":"1502","label":"Site", "cssClass":"col-xs-10 col-lg-10 col-md-10"}, \
			{"type":"string attribute","name":"unit","attributeId":"91001", "cssClass":"col-xs-2 col-lg-2 col-md-2"}, \
			{"type":"string attribute","name":"party","attributeId":"91000", "cssClass":"col-xs-12 col-lg-12 col-md-12"}, \
			{"type":"classifier combo","name":"verification","classifierId":"91150", "cssClass":"col-xs-6 col-lg-6 col-md-6"}, \
			{"type":"date attribute","name":"verification sent","attributeId":"91003", "cssClass":"col-xs-3 col-lg-3 col-md-3"}, \
			{"type":"date attribute","name":"verification received","attributeId":"91004", "visibleCondition":"verification=='Verified' ", "cssClass":"col-xs-3 col-lg-3 col-md-3"}, \
			{"type":"section","name":"site", "label":"Site Details", "components": 	[ \
				{"type": "classifier combo", "name":"owner", "classifierId":"1504", "parentClassifierId": "1502", "cssClass": "col-xs-6 col-lg-6 col-md-6"}, \
				{"type": "classifier list", "name":"department", "classifierId":"1503", "cssClass": "col-xs-6 col-lg-6 col-md-6"} \
			]} \
		]}
		
		
form1 = {"type":"section","name":"form","components":[\
			\
			{"type":"classifier combo","name":"type","classifierId":"1500","label":"Document Type", "cssClass":"col-xs-6 col-lg-6 col-md-6"}, \
			{"type":"classifier combo","name":"status","classifierId":"1501","label":"Status", "cssClass":"col-xs-6 col-lg-6 col-md-6"}, \
			{"type":"classifier autocomplete","name":"site","classifierId":"1502","label":"Site", "cssClass":"col-xs-10 col-lg-10 col-md-10"}, \
			{"type":"string attribute","name":"unit","attributeId":"91001", "cssClass":"col-xs-2 col-lg-2 col-md-2"}, \
			{"type":"string attribute","name":"party","attributeId":"91000", "cssClass":"col-xs-12 col-lg-12 col-md-12"}, \
			{"type":"classifier combo","name":"verification","classifierId":"91150", "cssClass":"col-xs-6 col-lg-6 col-md-6"}, \
			{"type":"date attribute","name":"verification sent","attributeId":"91003", "cssClass":"col-xs-3 col-lg-3 col-md-3"}, \
			{"type":"date attribute","name":"verification received","attributeId":"91004", "visibleCondition":"verification=='Verified' ", "cssClass":"col-xs-3 col-lg-3 col-md-3"},\
			{"type":"section","name":"site-section", "label":"Site Details", "components": 	[ \
				{"type": "classifier combo", "name":"owner", "classifierId":"1504", "parentClassifierId": "1502", "cssClass": "col-xs-6 col-lg-6 col-md-6"}, \
				{"type": "classifier list", "name":"department", "classifierId":"1503", "cssClass": "col-xs-6 col-lg-6 col-md-6"} \
			]} \
		]}		
		
		
form34= {"type":"section","name":"form","components":[\
			\
			{"type":"classifier list","name":"type","classifierId":"500", "cssClass":"col-xs-6 col-lg-6 col-md-6"}, \
			{"type":"attribute field","name":"effective date","attributeId":"91400", "cssClass":"col-xs-6 col-lg-6 col-md-6"}, \
			{"type":"row","name":"propertydata", "components": [ \
				{"type":"classifier autocomplete","name":"property","classifierId":"507", "cssClass":"col-xs-6 col-lg-6 col-md-6"}, \
				{"type":"classifier combo", "name":"pmc", "classifierId":"503", "parentClassifierId": "507", "cssClass": "col-xs-4 col-lg-4 col-md-4"}, \
				{"type":"attribute field","name":"unit","attributeId":"702", "cssClass":"col-xs-2 col-lg-2 col-md-2"} \
			]}, \
			{"type":"attribute field","name":"householdlastname","attributeId":"700", "cssClass":"col-xs-6 col-lg-6 col-md-6"}, \
			{"type":"attribute field","name":"householdfirstname","attributeId":"701", "cssClass":"col-xs-6 col-lg-6 col-md-6"}, \
			{"type":"resources","name":"resources"} \
		]}		