




icon=Icon
thumbnail=Thumbnail
jumbo=Jumbo
sort-date=Sort by Date
sort-title=Sort by Title

flat-view=Flat view
tree-view=TRee view



drag-and-drop = Drag & drop here, or click to upload

menu.upload-version = Upload Version
menu.showversions = Show Versions
menu.edit = Edit
menu.delete = Delete
menu.up = Move Up
menu.down = Move Down
menu.setasindex = Set as index

menu.download = Download
menu.newfolder = New Folder
menu.move = Move to {0}

menu.create = Create

menu.actions = Action

downloadall=Download All (Zip)

property.title=Title
property.description=Description
property.Url=URL
property.inPortalVersion=Portal Library
property.group = Group
property.check=

dialog.delete.title=Confirm
dialog.delete.message= Do you want to delete the file <b>{0}</b> ? 

dialog.confirm.title=Confirm
dialog.confirm.message= Move the file <b>{0}</b> to the Bulk Upload page ?

ok = Ok
close = Close
save = Save
cancel = Cancel
add = Add File
add-link = Add Link
add-tree = Add Tree
noimage = Text
image = Image
icon = Icon
noimage=No icon
thumbnail = Thumbnail
thumbnail-large = Image

full=Full width
standard=Standard

dragdrophere=Drag & Drop Files or click here

quotalimit=Storage quota completed
menu.delete-restore-bulkupload=Move to Bulk Upload

inportal=Portal: Yes
notinportal=Portal: No

file.editedby={0} · {1} · Edited 
external.editedby={0} · {1} · {2} · Edited
fileupload.uploadedby = {0} · {1} · {2} {3} 
fileupload.versionuploadedby =  {0} · {1} · {2} {3} Version {4}  

versions.label = Versions
version.name = Name
version.number = Version
version.date = Date
version.user = Uploaded By

folder.newname = New Folder

title = Title
date = Date

date_asc = Date (asc)
date_desc = Date (desc)


