noroles= Roles associated with this Dataset Value.
readonly=This panel is read only. It lists all <a href="/security/roles" target="_blank">Entity Roles</a> that use this <b>DataSet Value</b> with the <a href="/security/users" target="_blank">User</a> assigned. 
