personeditor.firstname=First Name
personeditor.lastname=Last Name
personeditor.email=EMail
personeditor.phone=Mobile Phone
personeditor.archive.archived=Archived
personeditor.archive.title = Archive
