contextmenu.open=Open
contextmenu.download=Download


console.section = Audit
console.label = Resources
console.name = Tree Resources
console.displayname=Resources

totalnodescolumn=Total Nodes
levelcolumn=Level
htmlcolumn=Tree
parentcolumn=Parent


systemlog = Activity
emaillog = Email
xplorer = File Server

audit.title=Audit {0}

titlecolumn = Title
datecolumn = Modified Date
taskcolumn = Task
idcolumn = ID
pathcolumn=URL
sizecolumn=Size
crc32column=CRC32
sha256column=SHA 256
usercolumn=User
iconcolumn=Icon
domaincolumn=Domain
urlcolumn=URL

taskprioritycolumn=Priority
workspacecolumn=Workspace

audit.title=Audit {0}
modal.sendbyemail.title=Share


bucketnamecolumn=Bucket
objectnamecolumn=ObjectName

kbfstypecolumn=KBFS Type
namecolumn=Name 

yes=<span class="yes">Yes</span>
no=<span class="no">No</span> 
