

contextmenu.open=Open

audit-resource=Audit Resource
console.section = Audit
console.label = Email Sent
console.name = Email Sent
console.displayname=Email Sent

systemlog = Activity
emaillog = Email Sent
xplorer = File Server

audit.title=Audit {0}

titlecolumn = Subject
datecolumn = Modified
taskcolumn = Task
idcolumn = ID
pathcolumn=Path
sizecolumn=Size
crc32column=CRC32
sha256column=SHA 256
usercolumn=User
iconcolumn=Icon
executedcolumn=Date Sent
eventcolumn=Event
usercolumn=User
actioncolumn=Action
resultcolumn=Result
fromcolumn=From
tocolumn=To
textcolumn=Text
attachmentscolumn=Attachments
kbeeclasscolumn=Internal Class
domaincolumn=Domain




taskprioritycolumn=Priority
workspacecolumn=Workspace

audit.title=Audit {0}
modal.sendbyemail.title=Share
