
search-in=Search in Activity
console.section=Audit
console.label=User Activity
console.name=User Activity

titlecolumn = Event Title
executedcolumn = Timestamp
 
usercolumn = User
idcolumn = Class - ID / version
eventcolumn=Event

eventtypecolumn=Event Type
eventactioncolumn=Action
objectclasscolumn= Object Class

descriptioncolumn=Description
kbeeclasscolumn=KbeeClass

systemlog=User Activity
xplorer=File Server
emaillog=Email

contextmenu.open=Open