console.label = Tasks

console.name = Monitor
monitor.name =Monitor

mytasks=My Tasks
pending=Pending Tasks
monitor=Monitor
workload=Dashboard


export.confirm=Please confirm you want to export a grid of <b>{0}</b> items ?<br />You will receive an email with a .csv file that can be opened with Excel and other Spreadsheets.

gridexport.confirm=Please confirm you want to export a grid of <b>{0}</b> items ?<br />You will receive an email with a .csv file that can be opened with Excel and other Spreadsheets.

titlecolumn = Title
contentconsole.titlelabel = Title
contentconsole.modifiedlabel =  Modified
contentconsole.modifiedasclabel =  Modified (Asc)
contentconsole.modifieddesclabel =  Modified (desc)
contentconsole.sendbyemail.message = {0} sent you this File,\n\n{1}\n\n{2}.


titlecolumn = Title
datecolumn =  Modified
taskcolumn = Task
idcolumn = ID
taskprioritycolumn=Priority
workspacecolumn=Workspace
contentclasscolumn=Template
modifieduser=Modified by

audit.title=Audit {0}
modal.sendbyemail.title=Share

taskstartcolumn=Task


monitor.contextmenu.sendbyemail=Share

monitor.contextmenu.audittrail = Audit Trail
monitor.contextmenu.open = Open
monitor.contextmenu.download=Download
monitor.contextmenu.take = Take
monitor.contextmenu.take.working = Reassign...
monitor.contextmenu.forcedactions = Force Termination
monitor.contextmenu.assignation-tome = Reassign to Me
monitor.contextmenu.assignation = Reassign
monitor.contextmenu.acl = Access Rights
monitor.error.alreadyinyourworkspace=The File is alredy in your Workspace

monitor.assigned-column-name = Taken/Pending Since

monitor.assigned = Taken/Pending Since (desc)
#Taken/Pending Since

monitor.assigned-asc = Taken/Pending Since (asc)
# Taken/Pending Since (desc)

monitor.assignedBy = From
monitor.workspace = Workspace
monitor.task = Task
monitor.priority = Priority

reassign=Reassign

monitor.reassignedfrom = Reassigned from 
monitor.by = by

monitor.batch.reassign = Reassign  
monitor.batch.class = Tasks
monitor.batch.return = < Back

monitor.action.myfilters  = My Filters
monitor.action.myfilters.clear = clear filters

monitor.error.nolonger = Content not longer in Workspace

toomanyitems=Unfortunately your selection has <b>{1}</b> items.<br/>Your Profile has a limit of <b>{0}</b> items. <br /> Please narrow down yor grid. 

unreadcolumn=R