package com.novamens.kbee.content.notification;

import java.time.OffsetDateTime;
import java.util.List;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import com.novamens.beans.BeansService;
import com.novamens.content.base.Content;
import com.novamens.content.base.ContentCreationException;
import com.novamens.content.base.ContentMgmtException;
import com.novamens.content.dao.ContentDao;
import com.novamens.content.notes.Billboard;
import com.novamens.content.notification.Notification;
import com.novamens.content.notification.NotificationService;
import com.novamens.content.notification.NotificationState;
import com.novamens.content.notification.NotificationType;
import com.novamens.content.service.ContentFactoryService;
import com.novamens.event.Event;
import com.novamens.event.EventListener;
import com.novamens.kbee.event.EventType;
import com.novamens.kbee.event.EvictCacheServiceEvent;
import com.novamens.logging.CheckinEvent;
import com.novamens.logging.DueDateAlertEvent;
import com.novamens.logging.ProgressNoteEvent;
import com.novamens.logging.SecurityUpdateEvent;
import com.novamens.logging.TaskPendingEvent;
import com.novamens.logging.TaskReassignedFormerOwnerEvent;
import com.novamens.logging.TaskStartEvent;
import com.novamens.logging.WorkNoteDeleteEvent;
import com.novamens.logging.WorkNoteUpdateEvent;
import com.novamens.scheduler.SchedulerException;
import com.novamens.scheduler.SchedulerService;
import com.novamens.scheduler.ServiceRequest;
import com.novamens.security.User;
import com.novamens.service.ServiceLocator;

/**  
 * 
* <p>Notifications Service. It is used for Workflow tasks and {@link ENotiRule}. </p>
 *
 * Calling from {@link EventNotifier}
 *
 * ------------------------
 * <p> <b> IMPORTANT </b> <br/>
 * ------------------------
 * This service executes during the ongoing DB Transaction in the same Thread.
 * Therefore, it must be fast, because in most cases the user is waiting for the action to complete.
 * 
 * In order to make it fast, the bulk of the processing and tasks are carried out by a {@link ServiceRequest} via the {@link SchedulerService}.
 * 
 * see also:
 * {@link PublishNotificationTaskServiceRequest}
 * {@link TaskStartNotificationTaskServiceRequest}
 * </p>
 *
 * <p>
 * Notifications by email of {@link CheckinEvent} events
 * defined by {@link ENotiRules}. They are rule-based notifications
 * They are only by email, they do not generate internal system notifications (those that appear with a red sign on the bell in the application).
 * </p>
 * <p> The notification service is called by the same thread that performed the action that generates the event.
 * This is done by {@link EventNotifier}, which is a Log4j appender. </p>
 *
 * There are notifications by email:
 *
 *. Workflow Task -> sent from {@link KbeeNotificationService}
 *. ReAssign Task -> is sent from {@link KbeeNotificationService}
 *. ENotiRule -> Publish is sent from {@link KbeeNotificationService}
 *. ENotiRule -> Send to Pending is sent from {@link KbeeNotificationService}
 *
 *
 * Internal system notifications (they do not send email):
 *
 *
 *. Social Subscription -> sent from {@link SocialEventListener}
 *
 *. Subscription Follow Content -> Update, comment registration, Vote
 *. Subscription Report Content -> Content Report sends mail to the Site administrator or Dr Bit Admin
 *. Subscription Follow Site -> High View, content update, content publication.
 * *  
 * 
 * 
 * Plantillas para el envío del email:
 * 
 * Tarea
 * Evento Publicación
 * Evento Pending
 * 
 */
public class KbeeNotificationService implements NotificationService, EventListener {
			
	private static kbee.util.logging.Logger logger = kbee.util.logging.Logger.getLogger(KbeeNotificationService.class.getName());
	static private Logger txLogger = LogManager.getLogger("TxLogger");

	

	public KbeeNotificationService() {
	}
	

	/** ---- 
	 * 
		* <p> The notification is sent when processing the Authoring Log Event
		* generated by the logging system used (Log4j). </p>
		*
		* <p> In addition, all Notifications generate a notification email. </p>
		*
		* ----------------------------
		* You have a new task -> When doing Task Start, if it is not taken by Take (if it is Take, it does not require notification)
		* There is Task in Pending -> It is a rule like Publish
		* ----------------------------	 
		**/
	@Override
	@Transactional(propagation = Propagation.REQUIRED)
	public void process(com.novamens.event.LogEvent event) {
		
		if (event.isSilentMode() ||
		       !((event instanceof CheckinEvent)            			|| 
				 (event instanceof TaskStartEvent)      				||
				 (event instanceof TaskPendingEvent)    				||
				 (event instanceof ProgressNoteEvent)					||
				 (event instanceof TaskReassignedFormerOwnerEvent)     	||
				 (event instanceof WorkNoteUpdateEvent)     			||
				 (event instanceof DueDateAlertEvent) 	    			||
				 (event instanceof WorkNoteDeleteEvent))) {
			return;
			
		}
		
		if (event.isSilentMode() || !event.isNotifiable()) {
				return;
		}
		
		schedule(new LogEventHandlerServiceRequest(event));
		
	
		// Work Note (Billboard) ------------------------------------------
		//
		// 
		if (event instanceof WorkNoteDeleteEvent) {
			/**
			 * When the Work Note is deleted the Database should delete all the
			 * WorkNoteNotifications associated via the ON DELETE CASCADE Constraint 
			 * Table is: kb_notification
			 */
			return;
		}
	}
	
	@Override
	public void sendPublishNotification(Content content,  User user) {
		ContentFactoryService factory = ServiceLocator.getService(ContentFactoryService.class);
		try {
			KbeeContentPublishNotification notification = (KbeeContentPublishNotification) factory.createContentPublishNotification(content,  user);
			logger.debug(notification!=null?notification.toString():" notification is null");
		} 
		catch (ContentCreationException | ContentMgmtException e) {
			logger.error(e);
		} 
	}

	@Override
	public void sendNotification(NotificationType type, Content content, String message, User user) {
		try {
			ServiceLocator.getService(ContentFactoryService.class).createNotification(type, content, message, user);
		} 
		catch (ContentCreationException | ContentMgmtException e) {
			logger.error(e);
		} 
	}
	
	@Override
	public void subscribe(EventType type, Content content, User user) {}
	
	@Override
	public void subscribe(EventType type, User user) {}
	
	@Override
	public void unsubscribe(EventType type, Content content, User user) {}
	
	@Override
	public void unsubscribe(EventType type, User user) {}
	
	@Override
	public boolean isSubscribed(EventType type, User user) {
		if (type==EventType.ASSIGN)
			return true;
		return false;
	}

	@Override
	public boolean isSubscribed(EventType type, Content content, User user) {
		if (type==EventType.ASSIGN)
			return true;
		return false;
	}

	private void schedule(ServiceRequest req) {
		try {
			logger.debug("Schedule ->  " + req.toString());
			ServiceLocator.getService(SchedulerService.class).enqueue(req);
		}
		catch (SchedulerException e) {
			logger.error(e);
		}
	}

 	/** ---- 
 	 * 
	 *  Notification CRUD
	 *  save
	 *  delete
	 *  getAll(user)
	 *  deleteAll(user)
	 *  getUserTotal()
	 * 
	 */
	@Override
	@Transactional(propagation = Propagation.REQUIRED)
	public void save(Notification noti) {
		try {
			getContentDao().save(noti);
		} 
		catch (ContentMgmtException e) {
			logger.error(e);
		}
	}
	
	
	@Override
	@Transactional(propagation = Propagation.REQUIRED)
	public void deleteForWorkNote(User receiver, Billboard note) {
		try {
			getContentDao().deleteNotification(receiver, note);
		} 
		catch (ContentMgmtException e) {
			logger.error(e);
		}
	}

	
	/**
	 * Called once a week from
	 *  
	 * {@link WorkNotesNotificationsCleanUp}
	 * 
	 *  CronJonb Service Request:
	 *  
	 * <bean id="clean-up-work-notes-notifications" class="com.novamens.kbee.content.notification.WorkNotesNotificationsCleanUpServiceRequest">
			<property name="cronExpression" value=  "0 15 4 ? * SUN"/>
		</bean>
	 * 
	 * 
	 */
	@Override
	@Transactional(propagation = Propagation.REQUIRED)
	public void deleteWorkNoteNotification(OffsetDateTime date) {
		getContentDao().deleteWorkNoteNotification(date);
	}


	
	/**
	 * Called once a week from
	 *  
	 * {@link WorkNotesNotificationsCleanUp}
	 * 
	 *  CronJonb Service Request:
	 *  
	 * <bean id="clean-up-content-publish-notifications" class="com.novamens.kbee.content.notification.ContentPublishNotificationsCleanUpServiceRequest">
			<property name="cronExpression" value=  "0 15 4 ? * SUN"/>
		</bean>
	 * 
	 * 
	 */
	@Override
	@Transactional(propagation = Propagation.REQUIRED)
	public void deleteContentPublishNotification(OffsetDateTime date) {
		getContentDao().deleteContentPublishNotification(date);
	}

	@Override
	@Transactional(propagation = Propagation.REQUIRED)
	public void markAsRead(Notification notification) {
		try {
			notification.setNotificationState(NotificationState.READ);
			notification.setOffsetDateTimeRead(OffsetDateTime.now());
			txLogger.info(new SecurityUpdateEvent(notification.getReceiver(), "Read Alert -> " + notification.getTitle()));
			logger.debug("Mark as Read -> " + notification.getReceiver().getDisplayName()+ " | " + notification.getTitle());
		}
		catch (ContentMgmtException e) {
			logger.error(e);
		}
	}
	
	@Override
	@Transactional(propagation = Propagation.REQUIRED)
	public void markAsDelete(Notification notification) {
		try {
			if (notification.deleteOnAccept()) {
				logger.debug("Delete -> " + notification.getReceiver().getDisplayName()+ " | " + notification.getTitle());
				getContentDao().delete(notification);
				txLogger.info(new SecurityUpdateEvent(notification.getReceiver(), "Delete Alert -> " + notification.getTitle()));
			}
			else {
				notification.setNotificationState(NotificationState.ARCHIVED);
				notification.setOffsetDateTimeRead(OffsetDateTime.now());
				txLogger.info(new SecurityUpdateEvent(notification.getReceiver(), "Delete Alert -> " + notification.getTitle()));
				logger.debug("Mark as Delete -> " + notification.getReceiver().getDisplayName()+ " | " + notification.getTitle());
			}
		}
		catch (ContentMgmtException e) {
			logger.error(e);
		}
	}
	
	@Override
	@Transactional(propagation = Propagation.REQUIRED)
	public List<Notification> getNotifications(User user) {
		try {
			List<Notification> list = getContentDao().getNotifications(user);
			//cache.put(user.getId(), list.size());
			return list;
		} 
		catch (ContentMgmtException e) {
			logger.error(e);
		}
		return null;
	}
	
	@Override
	@Transactional(propagation = Propagation.REQUIRED)
	public void deleteAll(User user) {
		try {
			getContentDao().deleteNotifications(user);
			txLogger.info(new SecurityUpdateEvent(user, "delete all Notifications"));
			//if (cache.containsKey(user.getId()))
			//		cache.remove(user.getId());
		} 
		catch (Exception e) {
			logger.error(e);
		}
	}
	
	@Override
	public int getTotalNotifications(User user) {
		if (user==null)
			return 0;
		return getContentDao().getTotalNotifications(user);
	}
	
	@Override
	public int getTotalBillboardNotifications(User user) {
		return getContentDao().getTotalBillboardNotifications(user);
	}

	public void evict() {
		//this.cache.clear();
	}
	
	protected ContentDao getContentDao() {
		return (ContentDao)ServiceLocator.getService(BeansService.class).getBean("contentDao");
	}

	@Override
	public boolean listen(Event event) {
		if (event instanceof EvictCacheServiceEvent)
			return true;
		return false;
	}

	@Override
	public void onEvent(Event event) {
		if (event instanceof EvictCacheServiceEvent)
			evict();
	}
}