name = Name
type = Type
modifiers = Modifiers
path = Macro in Template 
description = Description
content-structure = El contenido tendra una estructura de acuerdo a su template
freemaker = Las macros utilizan <a href="https://freemarker.apache.org/" target="_blank">Apache Freemaker</a>
