property.username=Username
property.email=Email


login=go to login
instructions=Please enter your username and email address registered in the system. You will receive a link to create a new password via email.
send=Send

forgotpassword.errorkbeemsg=The username and email address you entered do not match our records. 
forgotpassword.errormsg=The username and email address you entered do not match our records (#{0}).
forgotpassword.successmsg=We sent email to {0} with instructions to reset your password.
