
username-or-email=Username 
property.domain=Domain

property.username=
property.password=

property.password.placeholder=Password

forgot=Forgot your Password ?

errorcode-1=Authentication Error
errorcode-2=The domain is not Enabled. <br /> Please contact support.
errorcode-3=The account is not Enabled. <br /> Please contact support.


errorcode-4=ERROR CODE 4 
errorcode-5=ERROR CODE 5 



forgot-password=forgot password


biblioteca-corporativa=Corporate Library
signin-microsoft=Sign in with Microsoft


username-or-email.placeholder=Username
paassword=Password

signin=Sign in
