console.toolbar.expanded-mode = Content
console.toolbar.condensed-mode = List
 
console.toolbar.order-action = Sort
console.toolbar.content-layout = Content

console.toolbar.viewmode = View
 
gridnavigation.of = of
gridnavigation.filtersapplied=Filters 