down = down
up= up
send=Save
cancel=Cancel
columns=Columns

display-options=Display Options
cell-borders=Cell borders
row-bck=Row background
date-mode=Date format
resources=Resources
list-size=Page Size
yes=Yes
no=No

colloquial=Informal
timestamp=Timestamp


resize-defaults=Resize columns to default width

repeat-title-end=Repeat title col. at right end
