registration=Registro
title = Registro de Dispositivo Móvil
instructions = Hola <b>{0}</b>, para terminar con el proceso de Registro del Dispositivo Móvil <b>{1}</b> hace un click en el botón: 
email = Correo Electrónico Registrado
gotologin = Ir al Login
name.label = Nombre
submit.label = Registrar
not-found.error = Persona no encontrada
owner-not-found.error = Usuario o Terminal no encontrados
already-created.error = {0} ya tiene una cuenta de usuario registrada
done = Listo {0}! Su terminal <b>{1}</b> fue registrada. 
token-expired.error = Expiró el tiempo disponible para completar el registro. Por favor, inicie nuevamente el procedimiento desde su terminal.
