title = CREACION DE CUENTA
instructions = Le eviaremos un correo electrónico a la dirección registrada con las instrucciones para la creación de la cuenta
email = Correo Electrónico Registrado
gotologin = Ir al Login
name.label = Nombre
submit.label = Enviar correo electrónico
