modal.grid-config.title = Page settings

list-title=Settings
working=loading

page-size = Items per page
compact-view = Compact View
comfortable-view = Comfortable View

grid-settings = Grid Settings
cell-borders = Item Borders

background-odd=Background odd rows


grid=Grid
list=List


