
newsite=New Site
site=New Site
site=Portal

url-external=Enter full url (example: http://www.mysite.com)
url-intranet=Lowercase, no spaces, only letters and numbers

newsite.message.sucess=The Site was created succesfully.
newsite.action.label=Next Steps

newsite.action.create=Create New Portal
newsite.action.open=Open Portal
newsite.message.sucess=The Site was created successfully.

property.title=Title
property.url=URL
property.subtitle=Subtitle
property.description=Description
property.email_address=Email
property.ispublic=Access
property.istools=Tools
property.isexternal=External
property.sitetype=Portal Type

private=Private
public=Public
