


edit-site=Open Site Editor
edit-home=Open Home page editor

siteconsole.working=Working

console.label=Portal
console.name = Portals

column.subtitle = Subtitle

public=<span class="public">Public</span>
private=<span class="private">Private</span> 

yes=<span class="yes">Yes</span>
no=<span class="no">No</span> 

intranet=<span class="intranet">Intranet</span>
external=<span class="external">External</span>

modal.acl.title = ACL

sitesconsole.deleteconfirmation.message = Delete Site <b>{0}</b> ?

edit=Edit Portal
open=Open Portal
archive=Archive
reports=Reports
delete=Delete
name=Name
new=New Portal
publish=Publish
archived=Archived
archive-areas=Archive all Areas

suscriptors=# Suscriptors
id=ID
title=Title
url=URL
subtitlte=Subtitle
ispublic=Public
access=Access
external-title=Plataform
pages=Pages
tools=Tools
template=Type
type=Type NOT USED
public=Public
modified=Modified
status=Status

open-site-editor=Open Portal Editor

addtofavs=Add to My Favorites
removefromfavs=Remove from My Favorites

console.name=Portals




