# IDOC Windsor 
# KBFS2 --------------------------------------------------------------------------------------
#  
kbfs2.endpoint=http://localhost:9000
kbfs2.accesskey=G17YNO4C7RSYXPNGGKJE
kbfs2.secretkey=fz0VPr0Sh3DtTYWVtlkERR+tE68kVUvwfffHdvgA
kbfs2.fsid=aa

# default storage
kbfs.storage.default=kbfs2





