com.novamens.kbee.modules=aerolineas, kbee, solr, services, content, workflow,api, test

# SOLR Server
#solr.url=http://rcpidcfsdoc003.realpage.com:8983/solr
solr.url=http://localhost:8983/solr

solr.content-core=pymecontent
#solr.content-core=pjsf
solr.file-core=aafile

# Startup patches
startup.applypatches=no

# Database
#jdbc.url=jdbc:postgresql://localhost:5434/pjsf
jdbc.url=jdbc:postgresql://localhost:5434/aa2
jdbc.driverClassName=org.postgresql.Driver
jdbc.username=kbfree_admin
#jdbc.username=kbee_admin
jdbc.password=novamens
jdbc.schema=

updateSolrSchemas = true

# Reports
reports.enabled=true
reports = calculate

# ASYNC LOGGING LOG4J2
Log4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector

# Server
#server=http://localhost
port=8080

# Application
com.novamens.kbee.application = RPDM
com.novamens.content.web.idoc.url.context = rpdm

com.novamens.kbee.jettyShutdownPassword=IdocShutd0wn

# SEARCH ENGINE

solr.index.maxSize = 5000000
solr.index.maxFiles = 10

timezone.default=US/Central
support1.email=idocsupport1@realpage.com
support1.email=idocsupport2@realpage.com
noreply.email=noreply@idoc.realpage.com


# EMAIL  ----------------------------------------------------------------------------------------
#
email.server=smtp.gmail.com
email.port=587
email.username=aferraria@novamens.com
email.password=planeta2016
email.auth=true



# default storage
kbfs.storage.default=kbfsv1

# The server id matches the Database
# schema with the Minio Server
server.id=dev

wicketDebugEnabled=true

accept-all-signatures = no

spring.jackson.default-property-inclusion=non_null

odilon.enabled=yes  
odilon.shard1.endpoint=http://localhost:9234
odilon.shard1.accesskey=odilon
odilon.shard1.secretkey=odilon
odilon.shard1.fsid= OD01

kbee.user.behavior.onendtask = home
kbee.user.behavior.target = _blank
kbee.user.login.external.enabled = true
kbee.user.billing.enabled = false
kbee.user.profile.types = 1,4 
kbee.user.resources.draft.enabled = false
kbee.user.mydocuments.enabled = false
kbee.user.signature.enabled = false

kbee.security.workflow = false

kbee.text.defaulteditor = Tiny

kbee.cloud.enabled = false

kbee.rabbit.host = localhost
kbee.rabbit.port = 5672
kbee.rabbit.user = guest
kbee.rabbit.password = guest


# Porta Stat Database
portal.bcv.jdbc.url=jdbc:postgresql://localhost:5434/aalogs
portal.bcv.jdbc.driver=org.postgresql.Driver
portal.bcv.jdbc.username=kbfree_admin
portal.bcv.jdbc.password=novamens
portal.bcv.jdbc.schema=kbee

