semantics=Semantic

property.UniquenessKeyValidator=Must be unique
UniquenessKeyValidator=Must be unique


isapi=This Attribute is used by the API. Modifying the <b>Name</b>, <b>Number of Values</b> or <b>Status</b> may affect the electonic interface.

search-filters=Search Filter and Advanced Search forms
include-content-templates=Include in new Content Templates

predicate=Predicate
property.predicate=IQL Predicate

property.validatorType = Validator

property.isIdentityDocument = Is Identity Document

property.boostFactor = Boost Factor

NoneValidator = None
RangeValidator = Range

property.from = From
property.to = To

