

add-to-all-content-templates=Add to all Content Templates' Structure

console-description=<p>Attributes are free values that can be associated to Files, Users and other information objects.</p>\
<p>Attributes can be: String, Date, Integer Number, Float Number, String, Text (a text with format), Boolean, Validity From - To (used for Date Ranges) <br /><br /></p> 



contenttemplates=Content Templates
classifiers=Classifiers
searchplaceholder=Search in Attributes
readonly=Attributes are read only in this version
 
console.label = Information Model
console.name = Attributes
settings=Settings


modified = Modified
name = Name
relevance = Relevance

open = Open

alias=Alias 
username = User
status = Status
id = ID
type = Type
elements =# Miembros

new = New Attribute

dataset = DataSet

contenttype = Content Type
gridcolumn = GridColumn
metadatasubtitle = Subtitles
semantic = Use in Semantic calc.

multiplicity=Multiplicity


facetorder=Facet index
visibility=Is Column in

yes=<span class="yes">Yes</span>
no=<span class="no">No</span>

contextmenu.delete = Delete
deleteconfirmation.message = Please confirm to delete Attribute <b>{0}</b> ?
error.constraint = Integrity Constraint. The Attribute can't be removed.

enabled = <span class="enabled">Enabled</span>
deleted = <span class="deleted">Deleted</span>
archived = <span class="archived">Archived</span>
draft = <span class="draft">Draft</span>