

add-to-all-content-templates=Add to all Content Templates' Structure
yes-html=<span class="yes">yes</span>
no-html=<span class="no">no</span>

console-description=<p>A Classifier is a relationship between two Information Objects, on one side a File, User or DataSet Value, and on the other side another DataSet Value.</p>\
<p>Classifiers are basically the fields on the Forms, the values they offer in the selector are <a class="btn-link" href="/datasetmembers" target="_blank">DataSet Values</a> of the target <a class="btn-link" href="/model/datasets" target="_blank">DataSet</a><br /><br /></p>\
<p>A Classifier is always associated to a DataSet, that is the source of the DataSet values that can be associated on the eForm. Examples: Classifier Compliance Manager allows to assign a value of DataSet Person to a Compliance File</p>
 



searchplaceholder = Search in Classifiers
readonly=Classifiers are read only in this version 

console.label = Information Model
console.name = Classifiers
settings=Settings

modified=Modified
name=Name
relevance=Relevance

open=Open
uniquename=Search Field (SolR)

alias=Alias 
username=User
status=Status
id=ID
type=Type
elements=# Miembros

new = New Classifier

predicate=Predicate
dataset=Dataset
multiplicity=Multiplicity
rules=Condition in Custom Data Rights

contenttype=Content Type
gridcolumn=GridColumn
metadatasubtitle=Subtitles
semantic =Use in Semantic calc.

defaultstructure=Default Structure

alias=Alias 
facetorder=Facet index
visibility=Is Column in

yes=<span class="yes">Yes</span>
no=<span class="no">No</span>

contextmenu.delete=Delete
deleteconfirmation.message= Please confirm to delete Classifier <b>{0}</b> ?
error.constraint=Integrity Constraint. The Classifier can't be removed.


enabled=<span class="enabled">Enabled</span>
deleted=<span class="deleted">Deleted</span>
archived=<span class="archived">Archived</span>
draft=<span class="draft">Draft</span>



