include-default-content-templates=Default Structure
semantics=Semantic
access=Selector Strategy (Advanced Search and Forms)
advanced = Advanced
property.accessStrategy=Strategy
accessStrategy.help=All: allow to select All values. Roles: Allow to select values enabled by Roles. None: no values at all

property.UniquenessKeyValidator=Must be unique
UniquenessKeyValidator=Must be unique


property.description=Description

iql=IQL Conditions and Predicates
isapi=This Classifier is used by the API. Modifying the <b>Name</b>, <b>Number of DataSet Members</b> or <b>Status</b> may affect the electonic interface.

isContentType.helptext.title=Is Content Type
isContentType.helptext=Select <b>Yes</b> if the Classifier represents a document type like <b>File Type</b> or <b>Document Type</b> 
isContentType.help=This is a kind of semantic guide for the application. Select <b>Yes</b> if the Classifier represents a content type (like <b>File Type</b> or <b>Document Type</b>).

isMetadataSubtitle.helptext.title=Subtitle 
isMetadataSubtitle.helptext=Include the classifier value in subtitles (the tagline under the title)
 
property.dataSet=The entity whose values populate selectors 
dataSet.help=Form selectors will take values from this DataSet ( see Information Model <a class="btn-link" target="_blank" href="/model/datasets">DataSets</a> )

property.dataSet2 = Second DataSet Source 
dataSet2.help = The values defined by this classifier will be the sum of the selected dataSets: DataSet and DataSet 2 

multiplicity.help=<b>Exactly One</b> or <b>One or More</b> will make the field mandatory (displayed with <span style="color:#ff7070"> * </span> at the right of the label). <br /> \
Note that this general setting can be overridden by: 1st the <b>Content Template</b> on tab <b>Structure</b> -> 2nd <b>Task Structure</b> form.

multiplicity.modal.title=Multiplicity
multiplicity.modal.text=<b>Exactly One</b> or <b>One or More</b> will make the field mandatory (displayed with <span style="color:#ff7070"> * </span> at the right of the label). <br /> \
Note that this general setting can be overridden by: 1st <b>Content Template</b> on tab Structure -> 2nd Business Process' <b>Task Structure</b> form. 

name.help=Name
property.alias=Alias 

alias.help=Lowercase without spaces. It is used by API and other internal components. This field may be read only (except for user <b>root</b>)
predicate.help=Capitalized String without spaces. It is used by API and IQL conditions (Roles, Libraries, and other). This field may be read only (except for <span class="only-root">root</span>). 

property.isPortalSubtitle=In Portal Subtitles
property.isPortal=In Portal pages

			
property.isDistribution=Distribution

property.isMyDocument= Is My Document

isportal.helptext.title=Display in Portals
isportal.helptext=Include this field in portals 

isPortalSubtitle.helptext.title=Display in Portal subtitles
isPortalSubtitle.helptext=Include this field in portals

property.isWorkflowStatus=Is Workflow Status
isWorkflowStatus.help=Field Status in business process

property.isOrganization = Is Organization

property.isHierarchical = Is Hierarchical

property.isIdentityDocumentType = Is Identity Document Type


dataSet2.help=Although not usual, it is possible that a <b>Classifier</b> takes its values from <b>more than one DataSet</b> (Example: Classifier Owner may take values from DataSet Person and DataSet Organization). <br /> \
if not sure leave "None".
 
 
 property.hasHome = Mini Site
 