
info=Information
UniquenessNameValidator=This name already exists
UniquenessKeyValidator=This Key already exists

property.id = ID
editor.info = Info
editor.state = Status
editor.audit = Audit
editor.aggregations = Built-in DataSets
editor.display = Display

property.name = Name
property.alias = Alias
property.state = Status
property.classifiers = Classifiers
property.type = Type
type.help=This field is Read only. It is not possible to modify the Type after creating the DataSet  

property.enabled = Enabled
property.attributes = Attributes
property.multiplicity = Number of Elements
property.classifier = Classifier
property.metadataSubtitle =Subtitles
property.attribute = Attribute

property.readonly=Read only
readonly.help=<b>Yes</b>: if the values are managed only by the electronic inteface (API)

alias.help=Lowercase without spaces. It is used by API and other internal components. This field may be read only (except for <span class="only-root">root</span>)
predicate.help=Capitalized String without spaces. It is used by API and IQL conditions (Roles, Libraries, and other). This field may be read only (except for <span class="only-root">root</span>). 



editor.classifiers=Used by  
editor.structure = Structure 