createClassifier.help=This field may be read only (it is editable only for newly created DataSets)
attributes=Attributes

canonical=This is a System DataSet that can not be deleted.

property.description=Description

type.help=Type can be <b>String</b> or <b>Entity</b> (used by Dynamic Roles)

create-classifier-title=Add Classifier
property.createClassifier = Create Classifier from this DataSet

property.aggregation = Is built-in DataSet
property.alias = Alias

property.accessStrategy=Selector Strategy (Search Forms Selectors)
accessStrategy.help=Selector Strategy for <b>Search Forms</b> and other <b>Selectors</b>. <b>All:</b> allow Users to select all values. <b>Roles</b>: Allow to select values enabled by the user's Roles

property.alias=Alias

property.suggester = Include in Suggesters
suggester.help=Suggesters include items (like <b>Files</b> or <b>Users</b>) and Filters options that are taken from <b>DataSet Values</b>.

property.hierachical = Hierarchical

property.uniqueValues = Unique Values