


canonical=System
canonical-title=Sistem/Standard
standard=Standard

console-description=<p>DataSets represents the entities of the problem domain, like Property, Organization or Document Type. Their items (<a class="btn-link" href="/datasetmembers" target="_blank">DataSet Values</a>), can be associated like a  kind of 'tag' to Files, Users and other information objects through the <a class="btn-link" href="/model/classifiers" target="_blank"> Classifiers</a>.</p>\
<p>DataSets can be String (a simple label), Label (a label plus a color icon) or Entity (a label that can be used to grant permissions in <a class="btn-link" href="/security/roles" target="_blank">Roles</a>)<br /><br /></p> \
<h4>Built in DataSet</h4> \
<p>It is a special type of DataSet that is associated to another DataSet that contains it.</p>\
<p>The association describes a relationship between a whole and its existential parts.</p><p>Put simply, a Built in DataSet, a part can never be larger than the container DataSet. An example: A building consists of rooms. The building is the whole, the rooms are parts of the whole. Since it is a concrete building, its multiplicity is 1. The multiplicity of the rooms can go from 1..*, so there is at least one room (without space no building), but there can be (at least in theory) infinitely many rooms. The existence of an object or an instance cannot be dependent on two other objects/instances at the same time. A room belongs to one building and not to several buildings at the same time. In other words: the whole determines the life cycle of the parts. If the whole (i.e. the building) is removed, the individual parts (i.e. the rooms) disappear as well. This is called existential dependency.</p>


readonly=DataSets are read only in this version  

console.label = Information Model
console.name = DataSets
settings=Settings
datasets=DataSets

new-label=New Label
new-string=New String
new-entity=New Entity

modified=Modified
name=Name
relevance=Relevance

open=Open

external=External
yes=<span class="yes">Yes</span>
no=<span class="no">No</span>

alias=Alias 
username=User
status=Status
id=ID
type=Type
elements=# Members
classifiers=Classifiers

standard=Standard
built-in=Built in

builtin=Std/Built in

new = New DataSet
archive=Archive
delete=Delete

deleteconfirmation.message = Please confirm delete Dataset <b>{0}</b> ?

error.constraint = Integrity Constraint. If the Dataset contains Elements it can not be removed. 

contextmenu.delete=Delete

searchplaceholder=Search in DataSets
newelement=New Dataset


set-enabled=Set Status -> Enabled

Enabled=<span class="enabled">Enabled</span>
create-classifier=Create Classifier from this DataSet
add-element=Add DataSet Value
add-bulk-elements=Add DataSet Value (Bulk)
open-values=Open Values 
 





