UniquenessValidator=the name already exist
editor.info=Info
editor.notes=Notes
editor.state = Status
editor.audit = Audit Trail
editor.users = Users
editor.rules = Custom Data Rights
property.value = Name
property.archived = Archived
property.state = Status
property.note = Note
secured=Security Handler (creates a Group and a Security Rule).

property.readonly=Readonly

property.external=