display = Display Rules
displayName = Display Name
subline = Subline

property.alternativeDisplayNameTemplate=Shortened Display Name
alternativeDisplayNameTemplate.help=By default it will use the displayname. Example:${firstname} ${lastname}    
property.displayNameEditable= Is Editable 
property.displayNameTemplate = Title Macro 
property.sublineTemplate = Macro


displayNameTemplate.help=Example:${firstname} ${lastname} 
