label.aggregations = Built-in
property.modified = Modified
property.newname = Name
label.type = Type
label.name = Name
label.modified = Modified
label.members = # Members
button.new = Add New
button.create = Create
button.cancel = Cancel
confirmation.delete =  Delete <b>{0}</b> built-in DataSet ?

