tools.checkout=Create Working Copy
tools.archive=Archive
tools.delete=Delete


tools.grid.export.csv=Download Grid (.csv)
tools.grid.export.xls=Download Grid (.xlsx)

tools.grid.setasdefaultpreferences=Set as Default Preferences

