
batchcreation= Bulk Creation
elements=Values
oneperline=(One per line)
create=Save
close=Close
cancel=Cancel
add-elements=Dataset and Values

dataset-values=Dataset Values
stop=Stop

howitworkstitle=How it Works
howitworks=<p>Enter one value per line. The creation process will check for existing and duplicate values in the list.</p>
values=Values

property.datasets=DataSet