dataset.hitpanel.modified = Modified Date: {0}. {1}
dataset.hitpanel.alternate = Alternate: {0} 
dataset.hitpanel.children = Children ({0}): {1} 

				
dataset.hitpanel.status = Status: {0} 
dataset.hitpanel.path = Path: {0} 
dataset.hitpanel.relations = Classifiers: {0} 


open=open
delete=delete
archive=archive
enable=enable


dataset.hitpanel.phone=Mobile Phone {0}
dataset.hitpanel.email=Email {0}