
new-tag=New Resource Tag
tags=Resource Tags
console-description=<p>A <b>Resource Tag</b> is a tag applied to a resource (pdf, xlsx, ...) added to a content.<br />\
Resource tags are designed as a way to group resources and apply permissions to them.</p> <br /> \
<p>Example: a <b>Compliance File</b> that groups resources in <b>'Property'</b> (Submitted by the Property) and <b>'Compliance'</b> (added by the Compliance Analyst).</p>
 



searchplaceholder = Search in Resource Tag
readonly=Resource Tag are read only in this version 

console.label = Information Model
console.name = Resource Tag
settings=Settings

modified=Modified
name=Name
relevance=Relevance

open=Open
uniquename=Search Field (SolR)

alias=Alias 
username=User
status=Status
id=ID
type=Type
elements=# Members

new = New Resource Tag

predicate=Predicate
dataset=Dataset
multiplicity=Multiplicity
rules=Condition in Custom Data Rights

contenttype=Content Type
gridcolumn=GridColumn
metadatasubtitle=Subtitles
semantic =Use in Semantic calc.

defaultstructure=Default Structure

alias=Alias
facetorder=Facet index
visibility=Is Column in

yes=<span class="yes">Yes</span>
no=<span class="no">No</span>

contextmenu.delete=Delete
deleteconfirmation.message= Please confirm to delete Resource Tag <b>{0}</b> ?
error.constraint=Integrity Constraint. The Resource Tag  can't be removed.


enabled=<span class="enabled">Enabled</span>
deleted=<span class="deleted">Deleted</span>
archived=<span class="archived">Archived</span>
draft=<span class="draft">Draft</span>



