title = Resources Group
property.UniquenessKeyValidator=Must be unique
UniquenessKeyValidator=Must be unique
name.help=Display name of the tag 
property.alias=Alias 
alias.help=Lowercase without spaces. It is used by API and other internal components. This field may be read only (except for user <b>root</b>)
property.multiple = Multiple
multiple.help=Select yes if contents can have more than 1 resource with this tag
property.default = Default Tag