template.name = Workspace

template.config.name=Template

template.config.action.create = New
template.config.action.delete = Delete

template.config.contextmenu.open = Open
template.config.contextmenu.delete = Delete

template.config.notification.position=272

template.config.section=Information Model

column.name=Name
column.id=ID


column.user=User
column.modified=Modified
column.status=Status
column.organization=Organization
