reindex=Reindex Query
property.condition=Hibernate Query
property.batchsize=Batch Size
property.attachments = Attachments

howto-criteria=This is a Hibernate Query
IqlValidator = Syntax error


condition.help=<b>Sample Hibernate Queries</b>:<br/> from KbeeDomain where name='windsor' <br/>  from KbeeContent <br/>  from KbeeDataSetMember  <br/>  \
from KbeeContent where domain.id in (10754,4950,7600,7150,5901,3157) and id > 87921722-10000000 and id <= 87921722  <br/>  \
from KbeeUser <br/> \
from KBFileImpl where lastModifiedDate >= '2020-09-02T20:45:20Z' 

property.threads=Threads
threads.help=Number of indexing threads, by default this value is 1.5 times the available processors