reindex-contents=Reindex Contents


property.custommodel=Query type
custommodel.help=Select a custom (on) or predefined (off) query

property.domainmodel=Domain
property.frommodel=From (last modified)
property.tomodel=To (last modified)
property.sectionmodel=Section
property.attachmentsmodel=Include attachments
property.maxmodel=Max items
property.listmodel=Query (predefined)
property.domainmodel=Domain

