contextmenu.delete.confirmation = Confirma el movimiento a la papelera de : <b>{0}</b>
contextmenu.delete = Delete
contextmenu.delete.working = Recycling...
contextmenu.delete.confirmation = Confirma