report.name=Billing Report

column.billable_sites=Billable Sites
column.billable_users=Billable Users
column.date=Date
column.domain=Domain

organization=Organization
domaintype=Domain Type

column.users=Users
column.contents=Contents

gatewayhd=Hard disk Gateway (GB)
s3hd=S3 Hard Disk (GB)


column.hd_total=Hard Disk Total (GB)
column.db_total=Database (GB)

report.description=The application has a process that collects system data every nigth.<br/><br/><b>Billable Sites.</b> Sites with at least 1 file published<br/><b>Billable Users</b>. Users where field 'billable' is true (normally root and support and other users are exlcuded)<br/><b>Date</b>. Date when the data is collected (the closest to the Parameter selected)<br/><b>Users</b> Number of Users<br/><b>Billable Users</b> Number of Billable Users<br/><b>Total Hard Disk</b>. Total Hard Disk Usage (includes Minio, Odilon, AWS and Gateway Mode)<br/> 
 
 

