execute=Execute
title=Parameters


property.domain=Domain

property.from=Modificado Desde <span class="ago">(MM/dd/yyyy)</span>
property.to=Modificado Hasta <span class="ago">(MM/dd/yyyy)</span>


property.domain=Domain
