clear-form=clear form
move-domain-objects=Move
alert-move=Este comando mueve recursos del dominio seleccionado de un repositorio a otro.<br/>Sólo puede ser usado por el usuario <b>root@kbee</b>.


property.hdmodel=Hard Disk (GB)
property.source=Source Storage
property.destination= Destination Storage

 