


reconnect=Reconnect S3
resources=Resources
property.maxmodel=Max items
property.frommodel=From
property.tomodel=To
property.domainmodel=Domain
move=Move
delete=Delete 
commands=Commands
info=Info
encrypt=Encrypt
migrate=Move
clean=Clean 
purge=Remove <i>ghost files</i>
 



