alert-purge=This command deletes rogue binary files from Object Storage. <br/>Rogue files are files that are stored in the Object Storage but do not have a database entry referencing them (KBFile). \ 
This is because the file was uploaded and the transaction did not complete or the file was deleted from the database without removing the binary object.


purge=Remove ghosts
clear-form=Clear form
property.maxmodel=Max items
property.onlylist=List or Delete