clear-form=clear form
encrypt-domain-objects=Encrypt Resources
alert-encrypt=Este comando encripta recursos del dominio seleccionado que no están encriptados.<br/>Sólo puede ser usado por el usuario <b>root@kbee</b>. 