modal.sendbyemail.title=Share

tab.internalinfo=Internal Information
tab.main = Main
tab.history = Version History
tab.versioncontrol = Version Control
tab.audit = Audit

error.title = ERROR
error.no-document = Document not found or access deniend