property.cronField=Schedule
property.schedule=Send emails  
property.enable=Status
enable.help=Enable/disable sending this report 
property.scheduleDescription=Description


property.userSelector=Test as user
userSelector.help=The system will generate the report for the selected user

testSubscriptionBtn=Send this report to my email
emailWillBeSentTo=Subscription Email will be sent to 

successTestModalTitle=Information
successTestModalBody=Test email operation has been processes successfully.


userSelector.help=Test email will be sent to your email address.