
forgotpassword.title=Reset Password
forgotpassword.instructions= Please enter your Username and the Email address registered in the system and we will send you an email with the instructions.

forgotpassword.label.user=Username
forgotpassword.label.email=Email address
forgotpassword.label.domain = Domain
forgotpassword.backtologin= Back to login
					
forgotpassword.label.submit=Send

forgotpassword.errormsg = The pair username and email address does not match an existing user ({0})
forgotpassword.successmsg  = We sent a email notification to <strong>{0}</strong> with the instructions.

forgotpassword.subject 	= Reset password {0} 
forgotpassword.textemail = You can create your new password in this page:\n {0}.\n\n Please note that the link will be valid for 60 minutes.




