
forgotpassword.title=Reset Password
forgotpassword.instructions= Please enter your <b>username</b> and <b>email address</b> \
registered in the system and we will send you an email with the instructions. <br/><br/>\
Username has de form <i>name@organization</i>, <br/>example: <i>atolomei@novamens</i> 

forgotpassword.label.user=Username
forgotpassword.label.email=Email Address
forgotpassword.label.domain = Domain
forgotpassword.backtologin= Back to Login
forgotusername=If you don't know your username click here.				
					
forgotpassword.label.submit=Submit

backtologin=Back to login

forgotpassword.errormsg = The pair username and email address does not match an existing user. <br />Note that username must end with the domain (like <i>jsmith@realpage</i>)<br/>errocode: {0}
forgotpassword.successmsg  = We sent a email notification to <strong>{0}</strong> with the instructions.

forgotpassword.errorkbeemsg = For security reasons it is not possible to reset Factory password from this page. <br />We sent an email to the administrator to contact you.
 


com.novamens.kbee.mail.noreply=noreply@novamens.com

com.novamens.kbee.mail.forgot-password.subject= Reset password: {0} ({1})
com.novamens.kbee.mail.forgot-password.text=We have received your request to reset your account password.\nTo reset your password, visit the link below and follow the instructions:\n\n{0}\n\nFor security reasons, you will need to click on the link in the next 30 minutes from when the request was made.\nIf you didn't request to reset your password, you can safely ignore this email.\nIt's possible that another user entered your email address by mistake when trying to reset their own password.\n\nThanks. The {1} Team.\n\n
com.novamens.kbee.mail.fromemail=noreply <noreply@novamens.com>
forgotpassword.subject = Reset password {0} 
forgotpassword.textemail = To create your new password <strong><a href="{0}"   target="_blank">click here</a></strong>.\n\n Please note that the link will be valid for 1 hour.\n\nNote: if the link does not work in your email client try opening this url directly in your browser:{0}
