UniquenessValidator=the name already exist
property.name=Name
property.group=Group
property.groups=Parents
editor.info=Info
editor.users=Users
editor.rules=Custom Data Rights
editor.audit=Audit Trail
property.id=ID
