security.label = Security
console.name = Groups

usersconsole.name = Users
groupsconsole.name = Groups
rulesconsole.name = Custom Data Rights
groups=Groups

console.label=Security

searchplaceholder=Search in Groups

new = New Group
search-in-groups=Search in Groups

groupsconsole.column.name = Name
groupsconsole.column.id = ID
groupsconsole.column.modified = Modified
groupsconsole.column.modifiedby = Modified by
groupsconsole.column.path = Path
groupsconsole.column.users = # Users
groupsconsole.column.type = Type
groupsconsole.column.areacode=Area


groupsconsole.action.delete = Delete
groupsconsole.action.create = New

groupsconsole.action.myfilters = My Filters

groupsconsole.contextmenu.open = Open
groupsconsole.contextmenu.audittrail = Audit Trail
groupsconsole.contextmenu.delete = Delete

groupsconsole.deleteconfirmation.message = Please confirm you want to delete group <b>{0}</b> ?
groupsconsole.deleteconfirmation.message-with-members The Group <b>{0}</b> has <b>{1}</b> members.<br />They will no longer belong to this Group. Please confirm you want to delete it ?


groupsconsole.error.constraint = The object is referenced by other objects
							
groupsconsole.isderived=The Role {0} is derived from a Security Handler Dataset Value. It will be removed automatically when the Dataset Value is removed.

user-email-disabled-grid-export=You have disabled email notifications. <br />We will not be able to send you the export. <br />Please enable them back in <a class=\"btn-link\" href=\"/myaccount\" target="_blank">User Settings</a>, tab Account.


confirm.title = Confirm 
confirm.text =  Please confirm.

canonical=<span class="highlight">System</span>
standard=Standard

enabled=<span class="enabled">Enabled</span>
deleted=<span class="deleted">Deleted</span>
archived=<span class="archived">Archived</span>
draft=<span class="draft">Draft</span>

