user=User
password=Password
forgot=Forgot your Password ?
title=Welcome to kbee
error=Authentication error
error-domain-not-enabled=The domain is not Enabled. <br /> Please contact support.
error-user-not-enabled=The account is not Enabled. <br /> Please contact support.

