complete-pwd=Please enter password
password=password
complete-verification=Please enter password verification
verify-password=password verification
password-verification-no-match=Password and verification do not match
success=The password was changed successfully !
error=Application error

 new-pwd-title=Please enter new password for user
 new-pwd=New password
 new-pwd-verification=Repeat new password
 backtologin=go to Login