

property.password = New Password
property.password-verification = Repeat New Password

property.password.placeholder = New Password
property.password-verification.placeholder = New Password

pwd-characters = For your protection we require that the password must be <span class="highlight">8 characters or more</span>, must include <span class="highlight">1 digit or more</span> and <span class=" highlight">at least 1 capital letter</span>. 

reset-password=PASSWORD RESET

intro=You use a username and password to sign in to secure pages on KBEE. \
For your protection, we require that the password has <b>8 characters or more</b>, must include <b>one or more digit</b> and <b>one or more capital letter</b>.
										
complete-pwd=Please enter password
password=password
complete-verification=Please enter password verification
verify-password=password verification
password-verification-no-match=Password and Verification must match
success=The password was changed successfully ! <br /><a href="/login">click here to Sign in</a>.
error=Application error

does-not-have-number=Must have 1 digit or more 
does-not-have-capital-letter=Must have 1 capital letter or more 
minimum-8chars=Minimum 8 characters
new-pwd-title=Please enter new password for user
new-pwd=New password
new-pwd-verification=Repeat new password
backtologin=go to Login