
resetpassword.password  = New Password
resetpassword.password.explanation=

resetpassword.retype=Retype new password

resetpassword.button.submit=Save
resetpassword.button.cancel=cancel




