security.label = Security
console.name = Custom Data Rights
new=New Custom Data Rights
rules=Custom Data Rights

console.label=Security


rulesconsole.name = Custom Data Rights

error.constraint.security-handler=The Rule was created by a Security Handler Dataset Value.<br/>It will be removed automatically when the Dataset Value is removed. 
error.constraint.security-handler-name=The Rule was created by the Security Handler Dataset Value: <b>{0}</b>.<br/>It will be removed automatically when <b>{0}</b> is removed.
								
rulesconsole.new-rule-label = New Custom Data Rights

# Context Menu (actions applied to the selected content)
rulesconsole.contextmenu.open = Open
rulesconsole.contextmenu.audittrail=Audit Trail
rulesconsole.column.name = Name
rulesconsole.column.id= ID
rulesconsole.column.status= Status
rulesconsole.column.modified = Modified
rulesconsole.column.modifiedby = Modified by
rulesconsole.column.condition = Condition 
rulesconsole.column.acl = User or Group and Permissions

rulesconsole.column.isrole=Role
yes=Yes
no=No


deleteconfirmation.message=Please confirm to delete Rule <b>{0}</b> ?
error.constraint=Integrity Constraint. The rule can't be removed 
contextmenu.delete=Delete

enabled=<span class="enabled">Enabled</span>
indexing=<span class="indexing">Indexing</span>
deleted=<span class="deleted">Deleted</span>
archived=<span class="archived">Archived</span>
draft=<span class="draft">Draft</span>

searchplaceholder=Search in Custom Data Rights

user-email-disabled-grid-export=You have disabled email notifications. <br />We will not be able to send you the export. <br />Please enable them back in <a class=\"btn-link\" href=\"/myaccount\" target="_blank">User Settings</a>, tab Account.
