
property.password				 = New password for the selected users  
property.minimunlength 			 = Password must have at least 8 characters.
property.musthavecapitalletter   = Password does not have capital letters, it must have at least 1 capital letter.
property.musthavedigit			 = Password does not have digits, it must have at least 1 digit.
property.password.help			 = At least 8 characters, and must include 1 or more numbers
property.password.placeholder	 = type new password

minimunlength=The password must have at least 8 characters.
password.help=Minimum 8 characters. Must have at least 1 capital letter and at least 1 digit.
password=Password

musthavecapitalletter    = Password does not have capital letters, it must have at least 1 capital letter.
musthavedigit			 = Password does not have digits, it must have at least 1 digit.

info=Please enter the new password for the selected users.
