

batchcreation=Create
elements=Users

help=(Last name, First Name, Email address) 
create=Execute
close=Close
stop=Stop

users=Elements

section=Users
howitworks= <p>Enter <b>1 user per line</b> with the following structure: <b>last name , first name , email address</b> (commas are parsed as separators). All fields are mandatory, if one is missing, the user will not be created.</p>

howitworkstitle=How it works
values=Users