
deprecated=This Editor is deprecated and will be removed in future versions. Roles is the current mechanism to assign these rights.

account=Account

property.factory=Factory Management
property.api=API Developer
property.dservice=Service Admin

yes=Yes
no=No

settings					= Settings								
property.is_su 				= Super User
is_su.help 					= Can Sign in as another User
								
property.pending_tasks 		= Pending Tasks

property.usereditaccount=User Can Edit Personal Info
property.usersendemail=User Can Download and Send Files by email

property.userEditAccount=User Can Edit Personal Info
userSendContentEmail=User Can Download and Send Files by email

		
property.my_tasks 			= My Tasks
property.my_tasks_bulk 		= My Tasks. Bulk Upload    
property.monitor 			= Monitor   
property.auditor 			= Monitor   

property.content_base 			=  {0} Library
property.templates_cabinet 		=  {0} Library
property.kbase_cabinet 			=  {0} Library
property.external_cabinet 		=  {0} Library
				

property.work_notes  			= Work Notes				
property.archive 				= Archive
property.datasets_elements 		= Dataset Values (Manage)
property.datasets_elements_read = Dataset Values (Read)  
property.information_model  	= Information Model (DataSets, Classifiers and Classes)
property.security 				= Security (Users, Groups, Roles and Custom Data Rights) 
property.domain_admin 			= Domain Admin 
property.portal_admin			= Portal Admin

workflow=Access Workflow
content=Access Content
settings=Settings 
admin=Administration

readonly=This panel is read only.

internal-tools=Internal Tools

property.secured-access=Secured Access
property.editors=Editor



#information_model.help  = Manage DataSets, Classifiers, Content Templates
#my_tasks.help 			= Acces to My Tasks Section    
#monitor.help 			= Monitor Rights (on Files w/Write permissions) 
#auditor.help 			= Audit Rights (on Files with Read Permissions)  
#content_base.help 		= Access to Library Section
#templates.help 			= Access to Templates Section 
#archive.help 			= Access to Archive Section
#datasets_elements.help 	= Add, Edit, Delete Dataset Values and Labels 
#security.help 			= Data Rights
#domain_admin.help 		= All permissions in the System (except root)
#portal_admin.help		= All permissions in Sites


