user=User 
domain-admin=Domain Admin
support=Support
security=Security Admin
information-model=Information Model
model-read=Information Model Read
dataset-values=DataSet Values 
dataset-values-read=DataSet Values Read
monitor=Monitor
workspace=Workspace
su=Super User
mytasks=My Tasks
mytasks-bulk-actions=My Tasks. Bulk Upload
mybox=My Resources
library=Library
system-log=System Log


# deprecated
selector-system-log=Audit. System Log



# For Selectors

# internal use
selector-workflow=Admin. Workflow
selector-user=User
 
 
selector-domain-admin=Admin. Domain Admin
selector-su=Admin. Super User
selector-support=Admin. Support
selector-portal-admin=Admin. Portal Admin


selector-security=Settings. Security
selector-information-model=Settings.Information Model
selector-dataset-values=Settings. DataSet Values Read/Write 
selector-dataset-values-read=Settings. DataSet Values Read

selector-monitor=Workflow. Monitor
selector-workspace=Workflow. My Tasks
selector-mytasks=Workflow. My Tasks

dashboard=Dashboard

recycle-bin=Recycle Bin


mytasks-bulk-actions=My Tasks. Bulk Upload
selector-mytasks-bulk-actions=Workflow. My Tasks Bulk Upload

selector-library=Content. Library
selector-archive=Content. Archive Library
selector-templates=Content. Templates Library
selector-external=Content. External Library
selector-knowledge-base=Content. Knowledge Base Library 
selector-enterprise=Content. Enterprise Library

selector-auditor=Workflow.Monitor



workflow=Workflow
archive=Archive
auditor=Auditor
monitor=Monitor

portal-admin=Portal Admin
templates=Templates
external=External
knowledge-base=Knowledge Base
enterprise=Enterprise



corporate-admin=Corporate Admin
corporate-auditor=Corporate Auditor
corporate-editor=Corporate Editor

root=Root
pending-tasks=Pending Tasks
work-notes=Work Notes

domain-factory-manager=Domain Factory Manager
api-developer=API Developer
support-agent=Support Agent

service-management=Service Operations
operations-engineer=Operations Engineer
file-server=File Server

basic-editors=Editors
basic-secured-access=Secured Access
reports=Reports





portal=Portal Admin
internal=Internal
workflow=Workflow
notifications= Notifications
admin=Admin
security=Security
federated-security=Federated Security
federated-values=Federated Values
settings=Settings
audit=Audit
content=Library
legacy=Legacy
kbee-admin=Factory Admin

kbee-reports=Reports
reports=Reports