property.deployCheck=Deploy application before restart
property.deploySelector=Deploy File
property.fallbackCheck=Restore application if not validated after start
property.fallbackBackupSelector=Restore File
restart=Restart
markDeployAsValid=Mark Deploy As Valid