

# borrar estos ---------- 


content=Contenido

property.file=Adjunto
property.frequent=Enviar regularmente
property.cronExpression=
billboard-info=Carteleras del dominio kbeee se envían a todos los usuarios


property.startpub=Desde
property.endpub=Hasta


startpub.help=En blanco -> Hoy
endpub.help=En blanco -> Hasta ser aceptada

property.icon=Icono
property.title=Título
property.text=Texto

property.isbillboard=Alertas de Cartelera
isbillboard.help=Alertas de Cartelera y Alertas comunes (en la campanita) son excluyentes, si Cartelera está en Sí, la campanita se pasará a No.

receivers = Receptores
property.receivers=Enviar a
property.roleReceivers=Enviar a Rol
property.roles=Rol
user-or-group=Usuario
 
property.glyphicon=Icono 
glyphicon.help=Css de <b><a href="https://fontawesome.com/search" target="_blank">https://fontawesome.com/search</a></b>. Ejemplos: \
<b>fal fa-exclamation</b>, <b>fal fa-tools</b>, <b>fal fa-check</b> \
<b>fal fa-hourglass</b>, <b>fal fa-cabinet-filing</b>, <b>fal fa-toolbox</b>, <b>fal fa-tree-christmas</b> <b>fal fa-glass-cheers</b


property.isemail = Correo Electrónico
isemail.help=Enviar Notificación por Correo Electrónico

property.isalert = Alerta 
isalert.help=Notificación interna (la campanita en la barra superior)

was-sent=La Alerta ya fue enviada. Si edita la Alerta afectará a las no leídas aún. No es posible agregar o remover destinatarios.
create=Creada
modified=Modificación

billboard=Billboard
alert=Alerta
property.alert=Tipo de Alerta

preview=Previsualizar


property.sideImage = Imagen 

iconcss.help=Css de <a class="btn-link" href="https://fontawesome.com/search" \
target="_blank">FontAwesome</a>. Ejemplos: <i>"fal fa-exclamation"</i>, <i>"fal fa-tools"</i>, <i>"fal fa-check"</i>

#-----------------
content=Content

property.file=Attachment
property.frequent=Send billboard regularly

property.cronExpression=
billboard-info=Billboards from Domain kbee are sent to all users in all Domains

property.isemail = Email
isemail.help=Email Alert Templates can be edited by Admin users in <a class="btn-link" target="_blank" href="/emailtemplates">Email Templates</a> (Title <b>Alert</b>) 

property.startpub=From (Date)
startpub.help=Only for Billboard (if blank-> Today)

property.endpub=To (Date)
endpub.help=Only for Billboard (if blank-> Until accepted)


property.iconcss=Icon Class
iconcss.hep= Select the icon from <a class="btn-link" target="_blank" href="https://fontawesome.com/search">FontAwesome</a> and copy the class. For example: "fa fa-icon" 

property.icon=Icon
property.alert=Type

alert=Alert
billboard=Billboard

property.isbillboard=Billboard Alert
isbillboard.help=Note that Billboard Alert and regular (bell) alerts are exclusive, if Billboard is on, bell Alerts will be set to off.

property.title=Title
property.text=Text

receivers = Receivers

property.receivers=Send to
property.roleReceivers=Send to
property.roles=Roles 
property.glyphicon=Icon 
glyphicon.help= Css string from <b><a href="https://fontawesome.com/search" target="_blank">https://fontawesome.com/icons?d=gallery</a></b>. Examples: \
<b>fal fa-exclamation</b>, <b>fal fa-tools</b>, <b>fal fa-check</b> \
<b>fal fa-hourglass</b>, <b>fal fa-cabinet-filing</b>, <b>fal fa-toolbox</b>, <b>fal fa-tree-christmas</b> <b>fal fa-glass-cheers</b> 


property.isalert = Alert
isalert.help=Internal Notification (My Alerts)


was-sent-frequent=Note that changes to this Billboard do not affect alerts already created but only future alerts
was-sent=This Alert was already sent. Please note that: <br />- Some users may have already read it. <br />- It is not possible to add or remove receivers.
create=Created
modified=Modified

preview=Preview


property.sideImage = Image