property.title=Title
property.uri=Relative URL
property.alias=Alias 
property.description=Description
property.id=Id
id.help=Visible for Domain Admin only
property.state=Status

site-editor=Info