

close=Close
save=Save


editor.info = Info
editor.workflow = Business Processes
editor.structure = Structure
editor.display = Display
editor.relations = Relationships
editor.relationshipsbycriteria = Criteria Relationships
editor.state = Status
editor.audit = Audit

# Structure
property.name = Name
property.section = Name

property.attribute = Attribute
property.contentClass = Internal Class
property.abstract = Public Notes/Abstract

property.subsection = Subsection

# Semantic
property.multimedia = Is Multimedia
property.relations = Contents have Relationships to other Contents
property.document=Is Document
property.text = Is Text
property.video = Is Video
property.audio = Is Audio
property.image = Is Image
property.tool = Is Tool
property.activity = Is Activity
property.gridColumn = Default GridColumn




# Creation and Edition
property.instantiable = Instantiable
property.titleRule = Rule to generate Title 

titleRule.help=click on the (i) for the list of macros and examples

titleRule.help=Default: Name of the first resource attached without the extension. Example: <b>lease-jones.pdf</b> will be titled <b>Lease jones</b>

titleRule.onhelp= <h2>Macros</h2> \
1. <b> $classifier:</b> <i>classifier name</i><b>$</b>   <br /> \
2. <b>$attribute:</b> <i>attribute name</i><b>$</b>       <br /> \
3. <b>$attribute:</b> <i>attribute name:mask</i><b>$</b> <br /> \
4. <b>$classifier:</b><i>classifier name.classifier/attribute name</i><b>$</b> <br /> <br />  \
<h2>Modifiers</h2> 1. <b>:capital</b> -> capitalize <br /> 2. <b>:MM/dd/yy</b> -> date format <br /> <br /> <h2>Examples</h2> \ &#9642; If <b>File Type</b> has Attribute <b>Code</b>, ie. "Move In" has Code "MI",  <br /> \
<i>$attribute:Household Last Name:capital$, $attribute:Household First Name:capital$ $classifier:File Type.Code$ $attribute:Effective date:MM/dd/yy$</i> <br /> \
Renders: <br /> <b>Orth, Deborah MI 08/10/19</b><br /> <b>Bonzi, Aldo MI 06/09/18</b><br /><br />  \
&#9642; <i>$attribute:Household Last Name:capital$, $attribute:Household First Name:capital$ $classifier:File Type.Code$ $classifier:Effective Date:MM/dd/yy$</i> <br /> <br />  \
&#9642; <i>$classifier:Property.Property Number$ $attribute:Unit$ - $classifier:Document Type.Doc Code$ -  $attribute:Household Last Name:capital$, $attribute:Household First Name:capital$</i>  <br /><br />  \
&#9642; <i>$attribute:Unit$ - $attribute:Resident/Applicant Name$ -  $classifier:Property$ - $classifier:Document Type$ - $attribute:Effective date:MM/dd/yyyy$</i>  <br /><br />  \
&#9642; <i>$classifier:Property$ - $attribute:Effective Date:MM/yyyy$ - $classifier:Document Type$</i>  <br />


# Cabinet
property.template =Templates

property.state = Status

property.type = Type
property.default = Default
property.ordered = Ordered
property.visible = Visible
property.MetadataSubtitle=Subtitles
property.inherited = Inherit all in Dependent Relations
property.classifier = Classifier
property.classifiers = Classifiers
property.attributes = Attributes
property.multiplicity = Cantidad de Elementos
property.accessibility = Selector Strategy (Classifier)
property.valuesCriteria = IQL 
valuesCriteria.help = IQL to filter DataSet Values in Selectors
property.metadataSubtitle =Subtitles
property.type = Type
property.canonical = System
property.label = Label
property.structure = Elements
property.element = Element
property.classifier = Classifier
property.attribute = Attribute
property.calculation = Script for Selection
calculation.help = The returned value must be the display name of the selected value


# Launchers
#
property.processLaunchers = Procedures

property.enabledContext = Start from Library   
property.procedure =Procedure
procedure.help=This is the starting procedure that can be specialized. 
property.id=ID
property.enabled = Start from My Tasks


menu.procedure = Procedure
menu.down = Down
menu.up = Up
menu.delete = Remove

# Relations
#

property.state = Status

property.targetLabel = Target Label 
property.reverseLabel = Reverse Label 
property.reverseOrder = Reverse Order
property.targetOrder = Order
property.targetTemplates = Target Template 
property.reverseDisplayMode = Reverse Display Mode 
property.targetDisplayMode = Target Display Mode
property.aggregation = Is Built-in
property.name = Name

anytemplate.name = Any