

launchers=Business Processes

clone=Clone (create new from this)
searchplaceholder=Search in Templates
readonly=Content Templates are read only in this version
console.label = Information Model
console.name = Content Templates
settings=Settings
contentclasses=Content Templates

modified=Modified
name=Name
relevance=Relevance

open=Open

username=User
status=Status
id=ID
type=Type
elements=# Members
new = New Content Template
class=Internal Class
kbase=Knowledge Base
standard=Corporate
templates=Templates

templatesconsole.deleteconfirmation.message = Delete <b>{0}</b> ?
templatesconsole.error.constraint = There are Information Objects that reference this Content Template.
templatesconsole.contextmenu.delete = Delete

enabled=<span class="enabled">Enabled</span>
deleted=<span class="deleted">Deleted</span>
archived=<span class="archived">Archived</span>
draft=<span class="draft">Draft</span>


yes=<span class="yes">Yes</span>
no=<span class="no">No</span>
