display=Display
property.consoleSubtitleRule=Consoles Subtitles 
consoleSubtitleRule.help=Macro to generate subtitles in Consoles. Example: <i>$classifier:File Type$ $classifier:Effective date:MM/dd/yy$</i>. Click on the (i) for more help.

property.portalsSubtitleRule=Portals Subtitles
portalsSubtitleRule.help=Macro to generate subtitles in Portals and selectors. Example: <i>$classifier:File Type$ $classifier:Effective date:MM/dd/yy$</i>. Click on the (i) for more help. 
