

start=Start

open-procedure=Open Business Process Editor

property.label=Label
label.help=Label in button <b>New</b> in <b>My Tasks</b>,  and action <b>Edit</b> in <b>Library</b>

property.enabled=My Tasks Launcher 
enabled.help=Yes. Add this launcher to <b>My Tasks</b>


property.enabledContext=Library Launcher 
enabledContext.help=Add this launcher to <b>Library</b>


property.procedure=Business Process 
procedure.help=Select the <b>Procedure</b>. The Launcher will create a copy of the Model Procedure. 
read-only=This field can not be edited


property.launcherGroup=Launcher List
launcherGroup.help=This is the list in button <b>New</b> in <b>My Tasks</b> 



property.launchergroup=Launcher List
launchergroup.help=This is the list in button <b>New</b> in <b>My Tasks</b>

