<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<parent>
		<artifactId>kbee</artifactId>
		<groupId>com.novamens</groupId>
				<version>8.5-SNAPSHOT</version>
	</parent>


	<modelVersion>4.0.0</modelVersion>
	<artifactId>kbee-services-logging</artifactId>
	<name>${project.artifactId}</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
	<scm>
		<connection>
			scm:git:ssh://alejo@git.hq.novamens.com/var/novamens/logging.git
		</connection>
		<developerConnection>
			scm:git:ssh://alejo@git.hq.novamens.com/var/novamens/logging.git
		</developerConnection>
	</scm>
	<dependencies>
		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-util</artifactId>
			<version>${kbee-version}</version>
		</dependency>
		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-model-security</artifactId>
			<version>${kbee-version}</version>
		</dependency>
		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-services-classes</artifactId>
			<version>${kbee-version}</version>
		</dependency>

		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-model-dom</artifactId>
			<version>${kbee-version}</version>
		</dependency>


	</dependencies>
	
		<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>${java-version}</source>
					<release>${java-version}</release>
				</configuration>
			</plugin>
		</plugins>
	</build>
	
	
</project>