edit=Edit
open=Open
delete=Delete
archive=Archive
restore=Restore
moveup=Move Up
movedown=Move Down
archive-restore=Archive/Restore

archive=Archive
restore=Restore
move-internal=Move internal
move-external=Move external
move=Move (to new Parent)
add=Add 
