

UniquenessValidator=This name already exists
editor.info = Info
editor.grids=Column in Grids NOOOOOOOOOOOOOOOOOOOOOOO
editor.state = Status
editor.audit = Audit
editor.references = Used by

property.isPortalSubtitle=Subtitles in Portals
property.isPortal=Display in Portals

property.alias = Alias

alias.help=Lowercase without spaces. It is used by API and other internal components. This field may be readonly  (except for <span class="only-root">root</span>)
predicate.help=Capitalized String without spaces. It is used by API and IQL conditions (Roles, Libraries, and other). This field may be readonly  (except for <span class="only-root">root</span>)


property.name = Name
property.state = Status
property.multiplicity = Number of values
property.type = Type
property.isDefaultGridColumn=This column is visible by default in grids 

property.isRuleCondition=Condition in Custom Data Rights

property.order = Order
property.id=ID

property.isContentType=Is Content Type
property.isSemantic=Should be used in Semantic Functions


property.isGridColumn = Default Column (where visible)
property.ordered = Is this Column Sortable ?

property.isMetadataSubtitle=Include in subtitles
property.isFilterable=Search filter based on this Attribute
isFilterable.help=Whether to create a search filter based on this field (search filters are managed in <a class="btn-link" target="_blank" href="/facets">Search Filters</a>)

defaultstructure=Default Structure

property.isSearchable=Include in Advanced Search Selectors
isSearchable.help=

semantic=Display

display=Grids
structure=Name and Type 
 
 
property.isDefaultStructure=Default Structure
isDefaultStructure.help=If this Attribute must be added by Default to new Content Templates
 
property.defaultstructure=ISSSSSSSSSS
 
 