UniquenessValidator= Este nombre ya existe
property.name = Nombre
property.type = Tipo
property.multiplicity = Cantidad de elementos
property.predicate = Predicado
property.ordered = Ordenado
property.order = Orden
property.id=ID

editor.info = Info
editor.state = Status
editor.audit = Auditoría
editor.grids=Grillas


property.isDefaultGridColumn=Es Columna x Defecto en Grillas
property.isGridColumn=Es Columna en Grillas
property.isContentType=Es Tipo de Contenido
property.isSemantic=Usar en Funciones Semánticas
property.isSubTitles=Usar en Subtítulos de Metadata

property.isRuleCondition=Condición en Reglas

property.isMetadataSubtitle=Subtítulos
property.isFilterable=Filtros
property.isSearchable=Buscable
isSearchable.help=Si el atributo es buscable se incluye en los formularios de busqueda 

structure=Nombre y Estructura 
grids=Grillas
semantic=Otros
display=Grillas


defaultstructure=Agregar campo en nuevas Plantillas de Contenido 

property.isDefaultStructure=Agregar campo en nuevas Plantillas de Contenido
isDefaultStructure.help=Si este Atributo debe ser agregado en la estructura de nuevos Plantillas de Contenido por defecto
