
property.UniquenessKeyValidator=Must be unique
UniquenessKeyValidator=Must be unique


isapi=This Attribute is used by the API. Modifying the <b>Name</b>, <b>Number of Values</b> or <b>Status</b> may affect the electonic interface.


property.predicate=IQL Predicateeeeeeeeeeeeeeee

property.validatorType = Validator

NoneValidator = None
RangeValidator = Range

property.from = From
property.to = To

