UniquenessValidator=This name already exists
editor.info = Info
editor.grids=Column in Grids NOOOOOOOOOOOOOOOOOOOOOOO
editor.state = Status
editor.references = Used by
editor.audit = Audit

property.name = Name
property.state = Status
property.dataSet = Dataset Source
property.multiplicity = Number of Dataset Members
property.predicate = IQL Predicate (Custom Data Rights, Portals)
predicate.help = This field is read only (except for root user)
property.isDefaultGridColumn=Is this column enabled by default

property.order = Order
property.id=ID

property.isSearchable=Include in Advanced Search Forms
isSearchable.help=Yes: Include in advanced search forms

property.isContentType=Is Content Type
property.isSemantic=Should be used in Semantic Functions
property.isRuleCondition=Condition in Custom Data Rights

property.isGridColumn = Is a Default Column where visible
property.ordered = Is this Column Sortable
property.isMetadataSubtitle=In Subtitles in Forms and Library pages 

semantic=Other Settings
display=Display
structure=Classifier Name and Dataset 

grid-info=This form applies to Columns in Grids. To set up search filters for the sections please go to <a class=\"btn-link\" href=\"/facets\" target=\"_blank\"> Search Filters</a>


property.isDefaultStructure=Default Structure
isDefaultStructure.help=If this Classifier must be added by Default to new Content Templates (for general Classifiers like 'Document Type' or 'Status')

 
