


readonly=DataSets are read only in this version  

console.label = Information Model
console.name = DataSets
settings=Settings
datasets=Datasets

new-label=New Label
new-string=New String
new-entity=New Entity

modified=Modified
name=Name
relevance=Relevance

open=Open

external=External
yes=<span class="yes">Yes</span>
no=<span class="no">No</span>

alias=Alias 
username=User
status=Status
id=ID
type=Type
elements=# Members

new = New Dataset
archive=Archive
delete=Delete

deleteconfirmation.message = Please confirm delete Dataset <b>{0}</b> ?

error.constraint = Integrity Constraint. If the Dataset contains Elements it can not be removed. 

contextmenu.delete=Delete

searchplaceholder=Search in DataSets
newelement=New Dataset


Enabled=<span class="enabled">Enabled</span>
create-classifier=Create Classifier from this DataSet
add-element=Add DataSet Value
add-bulk-elements=Add DataSet Value (Bulk)
open-values=Open Values 
 





