visibility.workspace = My Tasks
visibility.monitor = Monitor
visibility.contentbase = Library
visibility.archive = Archive
visibility.portals = Portals
visibility.pendingtasks = Pending Tasks
visibility.templates = Templates

visibility = Column in Section


visibility.standard=Enterprise
visibility.templates=Templates
visibility.external=OneSite
visibility.kbase=Knowledge Base
visibility.all=All
visibility.pending=Pending


