package com.novamens.site.logging;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;

import javax.sql.DataSource;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.engine.spi.SessionImplementor;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.ResultSetExtractor;

import com.novamens.kbee.sql.SqlPlatform;
import com.novamens.kbee.sql.SqlPlatformFactory;
import com.novamens.util.KbeeRuntimeException;

/**
 * <p>Portal visits satistics</p>
 * 
 *     IMPORTANT: Log4j must be configured to include the SiteStats appender.
 *     	
 *      <Auditor name="Auditor"/>
		<SiteStats name="SiteStats"/>
		<EventNotifier name="EventNotifier" />
 *     
 *   	<Async name="Async">
			<AppenderRef ref="EventNotifier"/>
			<AppenderRef ref="Auditor"/>
			<AppenderRef ref="SiteStats"/>
		</Async>
		
		@see {@link SiteStatsAppender}
 *
 */
public class KbeePortalStatService implements  PortalStatService  {
	
	static kbee.util.logging.Logger logger =  kbee.util.logging.Logger.getLogger(KbeePortalStatService.class.getName());
	
	static private final int ID 					=  1;
	static private final int DOMAIN_ID				=  2;
	static private final int USER_ID				=  3; 
	static private final int USER_NAME				=  4;
	static private final int SITE_ID				=  5;
	static private final int SITE_TITLE				=  6;
	static private final int PAGE_ID				=  7;
	static private final int PAGE_TYPE				=  8;
	static private final int PAGE_TITLE				=  9;
	static private final int CONTENT_ID				= 10;
	static private final int CONTENT_TITLE			= 11;
	static private final int VISIT_TIME				= 12;
						
								
	static private final int SESSION_ID				= 13;
	static private final int RENDER_MILISECS		= 14;
	static private final int USER_AGENT				= 15;

	static private final int CONTENT_OID			= 16;
	static private final int CONTENT_VERSION		= 17;
	
	static private final int CONTENT_LONG_ID		= 18;
	
	
	static private final int OUT_ID 				=  1;
	static private final int OUT_DOMAIN_ID			=  2;
	static private final int OUT_USER_ID			=  3; 
	static private final int OUT_USER_NAME			=  4;
	static private final int OUT_SITE_ID			=  5;
	static private final int OUT_SITE_TITLE			=  6;
	static private final int OUT_PAGE_ID			=  7;
	static private final int OUT_PAGE_TYPE			=  8;
	static private final int OUT_PAGE_TITLE			=  9;
	
	static private final int OUT_BLOCK_ID			= 10;
	static private final int OUT_BLOCK_TITLE		= 11;
	
	static private final int OUT_VIEW_ID	  	    = 12;
	static private final int OUT_VIEW_TITLE		    = 13;
	static private final int OUT_VIEW_TYPE		    = 14;
	static private final int OUT_VIEW_LINK		    = 15;
	static private final int OUT_VIEW_SITE_ID		= 16;
	static private final int OUT_VIEW_CONTENT_ID	= 17;
	
	static private final int OUT_VISIT_TIME		    = 18;
								
	private DataSource dataSource;
	private SessionFactory sessionFactory;
	private String tableNameIn;   // po_site_login
	private String tableNameOut;

	private String schema;

	
	public KbeePortalStatService() {
	}

	
	/**
	 * 
	 * 
	 * @param stat
	 * 
	 * 
	 */
	@Override
	public void addInboundLog(SiteStatInEvent stat) {
		
		Connection connection = null;
		PreparedStatement statement = null;
		
		try {
			connection = getConnection(getSessionFactory().getCurrentSession());
			String enqueuestatement = this.getAddInboundLogStatement();
			statement = connection.prepareStatement(enqueuestatement);
			
			// id is generated by the database engine
			//
			statement.setLong(ID				, getNewOId());

			if (stat.domain_id!=null)
				statement.setLong(DOMAIN_ID			, stat.domain_id);
			
			
			

			statement.setLong(USER_ID			, stat.user_id!=null?stat.user_id: 0);
			statement.setString(USER_NAME		, stat.user_name!=null?stat.user_name:null);
			statement.setLong(SITE_ID			, stat.site_id!=null?stat.site_id: 0);
			
			if (stat.site_title!=null && stat.site_title.length()>256)
				stat.site_title=stat.site_title.substring(0,256);
			statement.setString(SITE_TITLE		, stat.site_title!=null?stat.site_title:null);

			statement.setLong(PAGE_ID			, stat.page_id!=null?stat.page_id: 0);
			
			if (stat.page_title!=null && stat.page_title.length()>256)
				stat.page_title=stat.page_title.substring(0,256);
			statement.setString(PAGE_TITLE		, stat.page_title!=null?stat.page_title:null);

			statement.setString(PAGE_TYPE		, stat.page_type!=null?stat.page_type:null);
			statement.setString(CONTENT_ID	    , stat.contentId!=null?stat.contentId:null);
			
			if (stat.content_title!=null && stat.content_title.length()>256) 
				stat.content_title=stat.content_title.substring(0,256);
			statement.setString(CONTENT_TITLE	, stat.content_title!=null?stat.content_title:null);
	
			if(stat.timestamp!=null)  
				statement.setTimestamp(VISIT_TIME,new Timestamp(stat.timestamp.toInstant().toEpochMilli()));
			else										
				statement.setTimestamp(VISIT_TIME, new Timestamp(System.currentTimeMillis()));

			if (stat.sessionId!=null)
				statement.setString(SESSION_ID, stat.sessionId!=null?stat.sessionId:null);
				
			if (stat.render_milisecs!=null)
				statement.setLong(RENDER_MILISECS, stat.render_milisecs);
			
			if (stat.user_agent!=null)
				statement.setString(USER_AGENT, stat.user_agent.length()<512?stat.user_agent:stat.user_agent.substring(0, 512));
			else
				statement.setString(USER_AGENT, "");
			
			if (stat.OId!=null)
				statement.setLong(CONTENT_OID, Long.valueOf(stat.OId));
			else
				statement.setLong(CONTENT_OID, Long.valueOf(0));
				

			if (stat.content_long_id!=null)
				statement.setLong(CONTENT_LONG_ID, Long.valueOf(stat.content_long_id));
			else
				statement.setLong(CONTENT_LONG_ID, Long.valueOf(0));

			if (stat.content_version!=null)
				statement.setInt(CONTENT_VERSION, stat.content_version.intValue());
			
			//logger.debug(statement.toString());
			
			statement.executeUpdate();
			
			//connection.commit();
			
		} 
		catch (SQLException e) {
			
			logger.error(e);
			logger.error("Can not log Visit " + (stat.site_title!=null?stat.site_title:null));
			
			try {
				try {
					connection.rollback();
				} catch (SQLException e1) {
					logger.error(e1);
				}
				throw new IOException(e);
			} catch (IOException e1) {
				logger.error(e1);
			}
		} 
		finally {
			if (statement != null) {
				try {
					statement.close();
				} catch (SQLException e) {
					logger.error(e);
				}
			}
			
			if (connection != null) {
				try {
					connection.close();
				} catch (SQLException e) {
					logger.error(e);
				}
			}
		}
	}

	
	/** 
	 * 
	 * @param stat
	 */
	@Override
	public void addOutboundLog(SiteStatOutEvent stat) {

		Connection connection = null;
		PreparedStatement statement = null;

		try {
			connection = getConnection(getSessionFactory().getCurrentSession());
			String enqueuestatement = this.getAddOutboundLogStatement();
			statement = connection.prepareStatement(enqueuestatement);
																			
			// id is generated by the database engine
			//
			statement.setLong(OUT_ID				, getNewOId());
			statement.setLong(OUT_DOMAIN_ID			, stat.domain_id);

			statement.setLong(OUT_USER_ID			, stat.user_id!=null?stat.user_id:null);
			statement.setString(OUT_USER_NAME		, stat.user_name!=null?stat.user_name:null);
			statement.setLong(OUT_SITE_ID			, stat.site_id!=null?stat.site_id:null);
			
			if (stat.site_title!=null && stat.site_title.length()>256)
				stat.site_title=stat.site_title.substring(0,256);
			
			statement.setString(OUT_SITE_TITLE		, stat.site_title!=null?stat.site_title:null);

			statement.setLong(OUT_PAGE_ID			, stat.page_id!=null?stat.page_id: 0);
			
			if (stat.page_title!=null && stat.page_title.length()>256)
				stat.page_title=stat.page_title.substring(0,256);

			statement.setString(OUT_PAGE_TITLE		, stat.page_title!=null?stat.page_title:null);

			statement.setString(OUT_PAGE_TYPE		, stat.page_type!=null?stat.page_type:null);

								
			statement.setLong(OUT_BLOCK_ID			, stat.block_id!=null?stat.block_id: 0);
			statement.setString(OUT_BLOCK_TITLE		, stat.block_title!=null?stat.block_title:null);
			
			statement.setLong(OUT_VIEW_ID			, stat.view_id!=null?stat.view_id:null);
			statement.setString(OUT_VIEW_TYPE		, stat.view_type!=null?stat.view_type:null);

			if (stat.view_title!=null && stat.view_title.length()>256)
				stat.view_title=stat.view_title.substring(0,256);
			statement.setString(OUT_VIEW_TITLE		, stat.view_title!=null?stat.view_title:null);

 			
			statement.setString(OUT_VIEW_LINK		, stat.view_link!=null?stat.view_link:null);

			
			if (stat.view_content_id!=null)
				statement.setLong(OUT_VIEW_CONTENT_ID	, stat.view_content_id!=null?stat.view_content_id:null);
			else
				statement.setLong(OUT_VIEW_CONTENT_ID	, Long.valueOf(-1));


			if (stat.view_site_id!=null)
				statement.setLong(OUT_VIEW_SITE_ID	    , stat.view_site_id);
			else
				statement.setLong(OUT_VIEW_SITE_ID	    , Long.valueOf(-1));

			if(stat.timestamp!=null)  
				statement.setTimestamp(OUT_VISIT_TIME,new Timestamp(stat.timestamp.toInstant().toEpochMilli()));
			else										
				statement.setTimestamp(OUT_VISIT_TIME, new Timestamp(System.currentTimeMillis()));

			logger.debug(statement.toString());
			
			statement.executeUpdate();
			connection.commit();
			
		} 
		catch (SQLException e) {
			
			logger.error("Can not log Outbound click " + (stat.site_title!=null?stat.site_title:null));
			
			try {
				try {
					connection.rollback();
				} catch (SQLException e1) {
					logger.error(e);
				}
				throw new IOException(e);
			} catch (IOException e1) {
				logger.error(e);
			}
		} 
		finally {
			if (statement != null) {
				try {
					statement.close();
				} catch (SQLException e) {
					logger.error(e);
				}
			}
			
			if (connection != null) {
				try {
					connection.close();
				} catch (SQLException e) {
					logger.error(e);
				}
			}
			
		}
	}
	

	
	
	/** 
	 * 
	 * 
	 */
	public Long getNewOId() {
		SqlPlatform sqlplatform = getSqlPlatform(); 
		JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
		Long value = (Long)jdbcTemplate.query(sqlplatform.nextSequenceQuery( getSchema()+"logsites_sequence"), new ResultSetExtractor<Long>() {
			public Long extractData(ResultSet rs) throws SQLException, DataAccessException {
				if (rs.next())
				return rs.getLong(1);
				return null;
			}
		}); 
		return value;
	}


	public void setDataSource(DataSource dataSource) {
		this.dataSource = dataSource;
	}
	
	public DataSource getDataSource() {
		return this.dataSource;
	}
	
	public void setSessionFactory(SessionFactory sessionFactory) {
		this.sessionFactory = sessionFactory;
	}
	
	public SessionFactory getSessionFactory() {
		return this.sessionFactory;
	}
	
	public void setTableNameOut(String name) {
		this.tableNameOut = name;
	}
	
	public String getTableNameOut() {
		return tableNameOut;
	}

	public void setTableNameIn(String name) {
		this.tableNameIn = name;
	}
	
	public String getTableNameIn() {
		return tableNameIn;
	}

	public String getSchema() {
		if(schema!=null && schema.length()>0)
			return schema+".";
		return "";
	}

	public void setSchema(String schema) {
		this.schema = schema;
	}

	public Connection getConnection(Session session) throws SQLException {
		return getDataSource().getConnection();
		//return ((SessionImplementor)session).connection();
	}														
	

/**
 * 
 * site_id
 * page_id
 * object_id
 * domain_id
 * content_id
 * 
 * 	
 * @param user_id
 * @return
 */
														   // ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
														   //    1,		      2,       3,          4,        5,	          6,       7,           8,           9,         10,              11,         12,         13,              14,         15  , 16        , 17     , 18   
	private String getAddInboundLogStatement() {           //  
		return "INSERT INTO " + getSchema()+getTableNameIn() + "(id,  domain_id, user_id,  user_name,  site_id,  site_title,  page_id,  page_type,  page_title,  content_id,  content_title, visit_time, session_id, render_milisecs, user_agent, content_oid, version, content_long_id) "
				  + "                                    VALUES (? ,          ?,       ?,          ?,        ?,           ?,        ?,           ?,          ?,           ?,              ?,          ?,          ?,               ?,          ?,    ?,         ?     , ?              )";
															
	}
																																					
	private String getAddOutboundLogStatement() {           //  
		return "INSERT INTO " + getSchema()+getTableNameOut() + "(id,  domain_id, user_id,  user_name,  site_id,  site_title,  page_id,  page_type,  page_title,  block_id,  block_title, view_id, view_title, view_type, view_link, view_site_id, view_content_id,  visit_time) "
		+ "                                               VALUES (? ,          ?,       ?,          ?,        ?,           ?,        ?,          ?,           ?,         ?,            ?,       ?,           ?,        ?,         ?,            ?,               ?,           ?)";
		
    }
	
	private SqlPlatform getSqlPlatform() {
		Connection connection = null;
		try {
			connection = getDataSource().getConnection();
			return SqlPlatformFactory.getPlatformFor(connection.getMetaData());
		}
		catch (SQLException e) {
			logger.error(e);
			throw new KbeeRuntimeException(e);
		}
		finally {
			if (connection!=null) {
				try {
					connection.close();
				}				
				catch (SQLException e) {
					logger.error(e);
					throw new KbeeRuntimeException(e);
				}
			}
		}
	}

}
