
archive=Archive
auditor=Auditor
corporate-auditor=Corporate Auditor
corporate-editor=Corporate Editor
domain-admin=Domain Admin
library=Library
monitor=Monitor
mytasks=My Tasks
support=Support
templates=Templates
user=User
root=Root
security=Security
external=External
information-model=Information Model
knowledge-base=Knowledge Base
mytasks-bulk-actions=My Tasks
mybox=My Resources
system-log=System Log
workflow=Business Process

recycle-bin=Recycle Bin


dataset-values=DataSet Values Admin
dataset-values-read=DataSet Values Read
dashboard=Dashboard

