

ROLE_USER = User
ROLE_DOMAIN_ADMIN = Domain Admin
ROLE_SUPPORT = Support 
ROLE_SECURITY = Security Admin
ROLE_INFORMATION_MODEL = Information Model Admin
ROLE_MONITOR = Task Monitor
ROLE_WORKSPACE = Workspace
ROLE_CONTENT_BASE = Library
ROLE_SYSTEM_LOG = System Logs
ROLE_WORKFLOW = Workflow
ROLE_ARCHIVE = Archive
ROLE_AUDITOR = Task Auditor
ROLE_FORMS_LIBRARY = Templates
ROLE_PORTAL_ADMIN = Portal Admin
Corporate = Corporate Auditor
CorporateAdmin = Corporate Admin