<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<artifactId>kbee</artifactId>
		<groupId>com.novamens</groupId>
		<version>8.5-SNAPSHOT</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>kbee-wfc-consoles</artifactId>
	<name>${project.artifactId}</name>

	<description>
		Apache Wicket based consoles. It uses services provided
		by kbee-wfc-wicket and kbee-services-classes.
		It does not see high level objects like Content, Domain
	</description>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<developers>
		<developer>
			<id>aferraria</id>
			<name>Alejo Ferraria</name>
			<email>aferraria@novamens.com</email>
		</developer>
		<developer>
			<id>atolomei</id>
			<name>Alejandro Tolomei</name>
			<email>atolomei@novamens.com</email>
		</developer>
	</developers>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>${maven-javadoc-plugin-version}</version>
				<configuration>
					<source>${java-version}</source>
					<release>${java-version}</release>

					<encoding>UTF-8</encoding>
					<notimestamp>true</notimestamp>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<scm>
		<connection>
			scm:git:ssh://alejo@git.hq.novamens.com/var/git/novamens/consoles.git
		</connection>
		<developerConnection>
			scm:git:ssh://alejo@git.hq.novamens.com/var/git/novamens/consoles.git
		</developerConnection>
	</scm>
	<dependencies>
		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-content-classes</artifactId>
			<version>${kbee-version}</version>
		</dependency>
		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-model-security</artifactId>
			<version>${kbee-version}</version>
		</dependency>
		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-services-classes</artifactId>
			<version>${kbee-version}</version>
		</dependency>
		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-dm-solr</artifactId>
			<version>${kbee-version}</version>
		</dependency>
		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-wfc-wicket</artifactId>
			<version>${kbee-version}</version>
		</dependency>
		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-util</artifactId>
			<version>${kbee-version}</version>
		</dependency>
	</dependencies>
</project>