
property.from=From
property.to=To

DateValidator.invalid-date=Date range must be 1 Jan 1900 to 31 Dec 2100 


DateValidator.invalid-date-low=Date must be after 1 Jan 1900
DateValidator.invalid-date-high=Date must be before 31 Dec 2100