references=References
menu.open = Open
menu.delete = Delete
menu.delete-confirmation = Confirm delete Dataset Value <b>{0}</b> ?
property.displayName = Name
property.lastModified = Modified
new-label = New
column.title = Name
column.modified = Modified
add-list=Add from list
bulk-creation=Bulk creation
