


firstname=FirstName
lastname=LastName



consoletitle=Title (Grid) 
externalid=External ID
open-tag-tool=Open tag tool

labels=Labels
bulk-creation=Bulk Creation

add-xlsx=Add from xlsx
add-list=Add from list


alert=Alert
billboard=Billboard

role=Role

settings-title=Settings

open-dataset=Open DataSet
used-by-classifier=Used by Classifier
description=Description

toomanyitems=Too many items


builtin-nocreate=This is a <b>Built-in</b> DataSet. Values must be added on the container DataSet <b>{0}</b> or imported from <b>{1}</b>
external=This DataSet is read only because it references external entity {0}
readonly=This DataSet is read only 
informationmodel.name = Dataset

console.label = Dataset Values
console.name=  Dataset Values

dataset.members=Dataset Values

hide-deleted=Hide Deleted
show-deleted=Show Deleted


settings=Settings

batch-creation=  Bulk Creation

dataset.action.create = New
dataset.action.delete = Delete
dataset.action.myfilters = My Filters

dataset.action.batchcreation=Batch Creation

dataset.hitpanel.modified = Modified: {0}. {1}
dataset.hitpanel.children = Children: {0} 

datasetconsole.contextmenu.open = Open
datasetconsole.contextmenu.home = Home
datasetconsole.contextmenu.edit = Edit
datasetconsole.contextmenu.delete = Delete
datasetconsole.contextmenu.restore = Restore
datasetconsole.contextmenu.audittrail = Audit Trail
datasetconsole.contextmenu.markasdeleted=Mark as Deleted
datasetconsole.column.builtinelements = {0} 
datasetconsole.column.builtincount = {0} <span class=\"ago\">(Number)</span>
dataset.advancedsearch.position=412
dataset.notification.position=194

name= NAMEEE

new=New


user-email-disabled-grid-export=You have disabled email notifications. <br />We will not be able to send you the export. <br />Please enable them back in <a class=\"btn-link\" href=\"/myaccount\" target="_blank">User Settings</a>, tab Account.


toomanyitems=Unfortunately your selection has <b>{1}</b> items.<br/>Your Profile has a limit of <b>{0}</b> items. <br /> Please narrow down yor grid. 
gridexport.confirm=Please confirm you want to export a grid of <b>{0}</b> items ?<br />You will receive an email with a .csv file that can be opened with Excel and other Spreadsheets.


datasetconsole.error.constraint = The object is referenced by other objects
													
													

												
datasetconsole.deleteconfirmation.securityhandler.message = <b>{0}</b> is a Security Handler, it will delete its Dependent Group and Rule.<br/> Confirm delete Dataset Value <b>{0}</b> ?
							
datasetconsole.deleteconfirmation.with-references.message = The Value <b>{0}</b> is referenced by other objects, and therefore it can not be removed completely. <br/> It will be marked as Deleted and made invisible in the grid. Please confirm.

datasetconsole.deleteconfirmation.message = Confirm delete Dataset Value <b>{0}</b> ?
 
dataset.action.tools = Tools
dataset.action.tools.relations = Attributes and Classifiers
 
datasetconsole.column.icon=Icon
datasetconsole.column.title = Name
datasetconsole.column.id = ID
datasetconsole.column.externalid = External ID
datasetconsole.column.modified = Modified Date
datasetconsole.column.modifiedby=Modified by
datasetconsole.column.user = Modified by
datasetconsole.column.references = Inbound Ref.
datasetconsole.column.status = St
datasetconsole.column.users=# Users
datasetconsole.column.email= EMail


datasetconsole.column.role=Role
datasetconsole.column.externaloid = External ID
datasetconsole.column.externalurl = External Url

datasetconsole.column.memberclass = Dataset Member Class
datasetconsole.column.securitygroup=Group


tools.archive=Archive
tools.bulkdelete=  Delete
placeholder=Search in {0}

has-references.title=Integrity Restriction
has-references.working=Working
has-references.done=The Dataset Member canót be removed because it has <b>{0}</b> references.


enabled=<span class="enabled">Enabled</span>
deleted=<span class="disabled">Deleted</span>
archived=<span class="enabled">Archived</span>
draft=<span class="enabled">Draft</span>


