rules = Periodic Tasks
newrule.label = Periodic Task 
newrule.button = Add
rule.label = Task
modified.label = Modified
status.label = State
lastexecution.label = Last Execution
nextexecution.label = Next Execution

menu.delete = Delete
menu.pause = Pause
menu.active = Activate

delete.confirmation.message = Delete the Periodic Task ?
delete.confirmation.text =

ENABLED = Active
ARCHIVED = Pause

rules-info=Reglas para crear Documentos e iniciar procesos de trabajo en forma periódica (mensual, trimestral, anual, etc.).