
cancel.label = Cancel

menu.delete = Remove role

property.user = User
property.email = EMail
property.phone = Phone

roles = Roles
noroles = No associated roles

remove-user.confirmation.message = ¿Confirm remotion of {0}?

confirm.label = Add