
deleted=Deleted
item-deleted=This element is marked as Deleted
link-user-title=User
link-user=To link this Person to an existing User click <a class="btn-link" href="/security/users/{0}">here</a>

user-linked = This Person is linked to user <a class="btn-link">{0}</a>
user-link = This Person is linked to user <a class="btn-link" href="/security/users/{0}" target="_blank">{1}</a>

built-in=Buit-in
UniquenessValidator=the name already exist
editor.info=Info

editor.externalid=External ID
editor.notes=Notes
editor.state = Status
editor.audit = Audit Trail
editor.account = User Account
editor.users = Users
editor.rules = Recurring Tasks
editor.roles = Roles
editor.permissions = Permissions
property.value = Name
property.archived = Archived
property.state = Status
property.note = Note
secured=Security Handler (creates a Group and a Security Rule).

property.external=
property.readonly=Readonly