authentication=Authentication
luser=Link with Existing User
property.linked=User
link-user-label=Link with existing User
user=User

creation-user=Create User
edit-user=User Info

creation-label=Create User
edit-label=Edit
create-label=Create
update-label=Save
cancel-label=Cancel		
property.email= Email address
help.mail= 
role.help=This refers to the main Role (whether a person is internal user or external user). <br/>For more detailed permissions you must open the Roles' section on the User's page

property.name= Name
property.role= Role
property.googleAuth= Google 
property.facebookAuth = Facebook 