addtodataset.label = Add to {0}
goto.label = View in {0}

contacts=The <b>Person DataSet</b> works as a Directory of contacts. <br/>A Person can optionally have a User associated, while other are just contacts and do not need a User.