help =  <p>Parameters: \
<ul> \
<li><b>source-url:</b>source api url.</li> \
<li><b>source-user</b></li> \
<li><b>source-password</b></li> \
<li><b>source-criteria: </b> IQL expression. Only domain(domainid) is tested</li> \
<li><b>source-domain:</b> source domain name.</li> \
<li><b>max-threads:</b> threads pool size. Default value is 3</li> \
<li><b>batch-size:</b> batch size. Default value is 65</li> \
<li><b>target-url</b></li> \
<li><b>target-user</b></li> \
<li><b>target-password</b></li> \
</ul> \
<ul>\
All moved content is logged in this table in execution server: \
	CREATE TABLE kb_Move ( \
		content_id bigint NOT NULL, \
		domain character varying(64), \
		status int, \
		error_message character varying(256), \
		CONSTRAINT move_id_pk PRIMARY KEY (content_id, domain) \
	) \
	WITH ( \
		OIDS = FALSE \
	)\
</ul>	 