managed-dataset-values=Managed DataSet Values
managedEntities=Managed DataSet Values

alert-text=Users with Role <b>{0}</b>( <i>{1}_X</i> ) <br />will be able to manage DataSet Values that have the Attribute <b>{1}</b> = <i>{1}_X</i>