
access-sections=Global Permissions
add-all=add all

main-sections=You can Enable or Disable <b>Access</b> to the main sections here. Note that the items and actions visible and available on each Section depend on the user's permissions.



role-entity-help=This Role we will grant permissions defined by the table below on Files that meet this Condition AND the Entity DataSet Value for each User.
role-general-help=This Role we will grant permissions defined by the table below on Files that meet this Condition


role-rights=Role Rights
entity-rule=Role Permissions 

entity=Dynamic
general=General

property.name = Name
property.id = Id
property.roleclass = Role Type
property.entitySet = Dynamic
property.classifier = Entity
property.general-rights=General Rights
property.description=Description
property.alias=Alias 
property.apiEnabled=API
property.isDefault=Is default  
isDefault.help=Select <b>Yes</b> if you want new users to have this Role
 

property.groupsList = Groups (users with this Role will belong to)
groupsList.help = Users with this Role will belong to these Groups.
 

property.groupsList = Groups (users with this Role will belong to)
groupsList.help = Users with this Role will belong to these Groups.


workflow=Workflow
content=Libraries
settings=Settings
admin=Admin
general=General
factory=Factory

