




content-permissions=Content 


main-sections=I think not used ???

role-rights=Role Rights
entity-rule=Role Permissions 

entity=Dynamic
general=General

property.name = Name
property.id = Id
property.roleclass = Role Type
property.entitySet = Dynamic
property.classifier = Entity
property.general-rights=General Rights
property.description=Description
property.alias=Alias 
property.apiEnabled=API
property.isDefault=Is default  
isDefault.help=Select <b>Yes</b> if you want new users to have this Role
 

property.groupsList = Groups (users with this Role will belong to)
groupsList.help = Users with this Role will belong to these Groups.
 

property.groupsList = Groups (users with this Role will belong to)
groupsList.help = Users with this Role will belong to these Groups.


workflow=Workflow
content=Libraries
settings=Settings
admin=Admin
general=General
factory=Factory

