members=Members
name = Person
group = (Group)
property.member = User
toadd=This panel is read-only. To add or remove Roles to users go to  <a href="/security/users" target="_blank" class="btn-link">Section Users</a>.
