
published-by=Published by
nohistory=There are no previous versions.
stop=Stop
archive=Archive
recycle=Recycle Bin
library=Library
date=Publish Date
versions=Previous Versions


version-title=Version  Info

version=Version
version-id=Version ID / OID

 
template=Content Template
source=Source
externalid=External ID
externaltime=External Timestamp
procedure=Business Process