inbounds = Inbounds
outbounds = Outbounds
column.source = Source
column.part = Part
column.target = Target
column.updated = Modificada

inbound-desc=Contents with <b>references to</b> this content
outbound-desc=Contents that <b>are referenced by</b> this content