

text-changes-label = Cambios en el texto de la ultima versión:
text-adds = Partes Agregadas
text-updates = Partes Modificadas
text-deletes = Partes Borradas
paragraphs-updates = Párrafos agregados o modificados:

column.title = Title

column.date = Title
column.version = Version
column.user = User and Date
by=by
