
to=To
text=Text
tomails=To Mails
tomails.help= tomails.help

alert-text= Generate a password-protected page.
password-protected=Password


property.link=Link
property.password=Password
password.help=Help

generate-link=Generate password protected link

copy-message = Copy link to Clipboard
copy-feedback = Copied
