
property.content=File
property.destinatary = To
property.destinatary.placeholder=Email address
property.text = Text

text.help=Files will be sent as attachments.

sendbyemailpanel.text = {0} has sent you this File:\n\n{1}\n{2}\n
modal.sendbyemail.title=Share
attachments = Files will be attached to the email.


ok=Send
cancel=Cancel


service-disabled=Emails has been disabled by the administrator. Admin users can enable the service in<a class="btn-link" href="/domain/{0}" target="_blank"> Settings</a>
disclaimer=Standard unencrypted email should never be used to transmit any document or file containing sensitive or confidential data. <br />Please review the content of your email, including any attachments, prior to transmission.

