
alert-text=Send email with a link to access the file. <br/> If the receiver is registered as a Person in the system -> they will be able to read the file and also open an account to access portals, or sign in if they already have an account. <br/> If the receiver is just an email address but the Person is not registered in the system, they will be able to read the file and nothing else.
 
ms=Sends an email with a link to access the file. You can select existing users and the system will use their registered email address, or just any email address.
title = File


to = Send to one or more people registered in the system
to.help= they will be able to read the file and also open an account to access portals, or sign in if they already have an account 

text = Message in the email

tomails = Send to email address <span style="font-weight: normal;">(for multiple addresses separate them with a <b> ; </b> )</span> 
tomails.help = For multiple addresses you have to separate them with a <b> ; </b> (example: <i>a@xx.com;b@xx.com</i> )




