progress=Progress
started=Started
status=Status
etc=Estimated time to complete
stop=Stop

title=Status
results=Results

terminated = Terminated
duration = Duration
comments = Comments
result = Result
result-details = Result details
loglabel = Log