

defaultpassword=The user will have be created with password: <b>{0}</b>. <br /> Default password can be set up in <a href="{1}" target="_blank">Domain Settings</a>
				
same-as.help=This field is non mandatory, you can set up Roles after creating the user. 

p_domains=Factory - Domains
p_dashboard=Factory - dashboard
p_api_dashboard=Factory - API dashboard
p_api_reports=Factory - API reports

p_mytasks=Workflow - My Tasks
p_monitor=Workflow - Monitor
p_library=Content - Library
p_users=Security - Users
p_pending=Workflow - Pending Tasks



same-as=Assign same Roles as User

property.startpage=Start Page
startpage=Start Page

newuser.rights=Security Rule
newuser.createrule=Add Custom Data Rights to this User


account=Account
general-permissions=Rights 
general-permissions-info=<b>My Tasks</b>, <b>Auditor</b>, <b>Enterprise Library</b>, <b>External Library</b> are default.

# <br />After creating the account you can edit them on 'Edit properties for this user'.
groups=Groups



property.firstName = First Name
property.lastName = Last Name
property.email = Email Address
property.userName = User Name

property.templates = Library Templates
property.archive = Archive
property.datasets_elements = DataSet Values (Manage)
property.datasets_elements_read = DataSet Values (Read)
property.information_model = Information Model
property.security = Security
property.domain_admin = Domain Admin

property.user_edit=User Can Edit Personal Info
property.user_email=User Can Email Files

property.secured_group = Read Secured Files
property.editor_group = Editor


userName.help=Lowercase, only letters and numbers. Do not include the <em>'@...'</em>. The form will check for availability. Account credentials will be <b><em>username</em></b>@{0}


property.domain = Domain
property.resetPassword = Send Welcome Email with link to Reset Password

newuser.message.sucess = The user was created successfully 

newuser.action.label = Next steps
newuser.action.return = <- Back to Users
newuser.action.create = Create Another User
newuser.action.edit = Edit Properties and Add Roles  


UsernameValidator.uniqueness=User Name already exists
UsernameValidator.characters=Invalid characters

newuser=New User
user=User

property.groups=Groups
groups.help=You can complete this later

clone-message=The new user will have the same Roles as <a href="{1}" class="btn-link" target="_blank">{0}</a>


