property.phone.help=This field is mandatory.
property.email.help=This field is mandatory.
property.lastName.help=This field is mandatory.
property.workPosition=Job Profile  

property.photoDomainLogo=Show logo over photo

account-disabled=The Adminstrator has disabled editing Personal Information.
person=Person

property.emailValidated=Email Validated
property.id=Person Id