

p_domains=Factory - Domains
p_dashboard=Factory - dashboard
p_api_dashboard=Factory - API dashboard
p_api_reports=Factory - API reports

p_mytasks=Workflow - My Tasks
p_monitor=Workflow - Monitor
p_library=Content - Library
p_users=Security - Users
p_pending=Workflow - Pending Tasks
	

account=User account

notifications=Alerta por Tarea asignada
ui=User Interface
account-disabled=The Adminstrator has disabled editing the account.

property.isclient=Billable  
isclient.help=<b>On</b> -> User belongs to the billing client <br /><b>Off</b> -> Root or Support user <i> <br />This field can only be edited by root user</i>

property.usereditaccount=User can edit
usereditaccount.help=User can edit account information

property.userchangepassword = User can change password
userchangepassword.help=User can change his own password

property.usersendemail=Share 
usersendemail.help=User can send files by email

property.enabled=Account Status
enabled.help=If the account is disabled the user can not sign in 



property.domain=Domain
property.userid=User ID
property.userName=User
property.locale=Language
property.firstName=First Name
property.domain=Domain
property.lastName=Last Name
property.email=Email

property.enabled=Enabled

property.editPersonEnabled=User can Edit Person information
property.phone=Mobile Phone
property.uitheme=Theme

property.startpage=Start page
property.id=User id

property.userName=Username
property.tipoftheday=Tip of the Day

property.emailNotifications=Task Received Alert  DELETEEEEEEEEEEE

emailNotifications.help=Send email notification when {0} receives a new Task

property.emailPendingNotifications=Pending Task  
emailPendingNotifications.help=Send email notification when there is a new Pending Task that the {0} can Take

property.emailRuleNotifications=Workflow Alerts 
emailRuleNotifications.help=Send email alert from Business Process Alerts: <br/> Task Action -> Post Termination Alert ("Send to") <br/> Task Timeout  Alerts <br/> Workflow Alerts (on event Publish/Pending)   


property.timezone=Timezone

property.password1=Password  
property.password2=Retype Password (Verification)
property.active = Active
property.minimunlength = Password must have at least 8 characters.

property.musthavecapitalletter   =  Password does not have capital letters, it must have at least 1 capital letter.
property.musthavedigit			 =Password does not have digits, it must have at least 1 digit.

property.password1.help=At least 8 characters, and must include 1 or more numbers
property.password1.placeholder=type new password
property.password2.placeholder=retype new password

minimunlength=The password must have at least 8 characters.
password1.help=Minimum 8 characters. Must have at least 1 capital letter and at least 1 digit.
password2.help=
changepassword=Change Password
password1=Password
property.emailNotifications=Task Assigned  
PasswordsValidator=Password and Verification do not match

musthavecapitalletter    = Password does not have capital letters, it must have at least 1 capital letter.
musthavedigit			 = Password does not have digits, it must have at least 1 digit.





