add=Add

assigned-roles=Assigned Roles
property.copy-user=Add Roles from user
copy-user.help=Add the Roles that the selected user has

remove-all=remove all
nt100=The maximum number of roles supported per user is 100