
attriibutes=Attributes
editor.relationships=Attributes
readonly=This panel is read only. Admin users can edit users' Attributes on <a class="btn-link" target="_blank" href="/security/users">Users</a>
