
email-rules=Workflow Alerts
dialog.delete.title=Confirm
dialog.delete.message=Delete Enoti Rule <b>{0}</b> ?
norules=
add-label=Add
enoti=Email Notification 

alert-note=NOOOOOOOOOOOOOO
NOTE. Email notifications on <b>Tasks assigned</b> to this User Account can be edited on tab <b>Account</b>.