norules=
readonly=This panel is read only. Custom Data Rights are assigned dynamically by the user's Roles
securityrules=Custom Data Rights
securityrules.text= <p>Each Rule Grants or Denies rights to the User or to one of the User's Groups.<p>