form.uploadTooLarge = Progress - File must be less than ${maxSize}.
form.uploadSingleFileTooLarge = Progress - Each of files must be less than ${fileMaxSize}.
form.uploadFailed = Progress - File failed to upload: ${exception.localizedMessage}