site=Portal
external=External

home=Home
results=Results
detail=Detail
about=About
explorer=Explorer


reports=Reports		 
kbase=Knowledge Base
dealroom=Deal Room
searcher=Searcher

library=Library
main-section=Main Section
area_search=Search
searcher=Block Search
news=News
updates=Updates
categories=Categories
info=Info
activity=Recent Activity
area_widgets=Area Widgets

dashboard-queries=Categories
Categories=Categories


