property.user=User
property.domain=Domain

property.password.placeholder=Password

forgot=Forgot your Password ?

errorcode-1=Authentication Error
errorcode-2=The domain is not Enabled. <br /> Please contact support.
errorcode-3=The account is not Enabled. <br /> Please contact support.

