
com.novamens.content.web.questionanswer.qaaboutpage.title=Question Answers About
com.novamens.content.web.questionanswer.qaaboutpage.keywords=About

com.novamens.content.web.questionanswer.qahomepage.title= Question and Answers
com.novamens.content.web.questionanswer.qahomepage.keywords= Question, Answers, Knowledge Sharing
com.novamens.content.web.questionanswer.qahomepage.description= Question and Answers site

