console.label = Admin


	
section=Factory
console.name = Commands
console.displayname = Commands

action.create = New Command
delete=Delete

new=New Command
toomanyitems=Unfortunately your selection has <b>{1}</b> items.<br/>Your Profile has a limit of <b>{0}</b> items. <br /> Please narrow down yor grid. 
 
cancelconfirmation.message = Do you want to delete the file <b>{0}</b> ?

title=Name
modified=Modified
relevance=Relevance
state=Status

commandsconsole.column.estiamted-end=Remaining Time (est) 
commandsconsole.column.name=Name
commandsconsole.column.id=Id
commandsconsole.column.status=Status
commandsconsole.column.scope=Scope
commandsconsole.column.duration=Duration

commandsconsole.column.started=Start
commandsconsole.column.terminated=End
commandsconsole.column.result=Result
commandsconsole.column.parameters=Parameters
commandsconsole.column.description=Description
commandsconsole.column.comment=Comment
commandsconsole.column.progress=Progress
commandsconsole.column.class=Class

contextmenu.open=Open
contextmenu.stop=Stop
contextmenu.remove=Remove

contextmenu.pause=Pause
contextmenu.resume=Resume

commandsconsole.column.total-items-processed=Processed
commandsconsole.column.total-items=Total Items

