
database-page=Database info
database-version = Database. Version
database-url = Database. URL
database-size = Database. Size
database-user = Database. User
render-time=Render time
db-la = DB CPU Load Average (1m 5m 15m)
sql-gateway=SQL Gateway