<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<parent>
		<artifactId>kbee</artifactId>
		<groupId>com.novamens</groupId>
		<version>8.5-SNAPSHOT</version>
	</parent>

	<modelVersion>4.0.0</modelVersion>
	<artifactId>kbee-wfc-tinymce</artifactId>
	<name>${project.artifactId}</name>
	<description />
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
	<developers>
		<developer>
			<id>aferraria</id>
			<name>Alejo Ferraria</name>
			<email>aferraria@novamens.com</email>
		</developer>


		<developer>
			<id>atolomei</id>
			<name>Alejandro Tolomei</name>
			<email>atolomei@novamens.com</email>
		</developer>

	</developers>
	<scm>
		<connection>
			scm:git:ssh://alejo@git.hq.novamens.com/var/git/novamens/tinymce.git
		</connection>
		<developerConnection>
			scm:git:ssh://alejo@git.hq.novamens.com/var/git/novamens/tinymce.git
		</developerConnection>
	</scm>
	<dependencies>
		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-wfc-wicket</artifactId>
			<version>${kbee-version}</version>
			<scope>compile</scope>
		</dependency>
		
		
		<!-- dependency>
			<groupId>org.apache.wicket</groupId>
			<artifactId>wicket-extensions</artifactId>
			<version>10.3.0</version>
			<exclusions>
				<exclusion>
					<artifactId>slf4j-api</artifactId>
					<groupId>org.slf4j</groupId>
				</exclusion>
			</exclusions>
		</dependency -->
		
	</dependencies>
</project>