report.name=Pre-Approval Correction Trends  
console.name=Pre-Approval Correction Trends  


section=Reports

console.label=Reports

modified = Modified
name = Name
relevance = Relevance

column.datepublish = Fecha Publicación
column.user = Apellido
column.user-firstname = Nombre
column.group = Grupo
column.dateread = Leído

report.description = <h3>Reporte de Acuse de Recibo</h3> <p>Notificaciones enviadas al momento de publicar un contenido que requieren "acuse de recibo" explícito por parte del usuario.</p><p>Para que la notificación sea marcada como "leída" el usuario que la recibe debe: <br /><br /> <ul> <li> - clickear en "marcar como leída"</li><li>- o bien abrir el detalle del contenido publicado</li></ul>.</p>
	