<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<artifactId>kbee</artifactId>
		<groupId>com.novamens</groupId>
		<version>8.5-SNAPSHOT</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<name>${project.artifactId}</name>
	<artifactId>kbee-dm-solr</artifactId>
	<scm>
		<connection>
			scm:git:ssh://alejo@git.hq.novamens.com/var/novamens/solr-indexer.git
		</connection>
		<developerConnection>
			scm:git:ssh://alejo@git.hq.novamens.com/var/novamens/solr-indexer.git
		</developerConnection>
	</scm>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
	<dependencies>
		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-services-spring</artifactId>
			<version>${kbee-version}</version>
		</dependency>
		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-dm-hibernate</artifactId>
			<version>${kbee-version}</version>
		</dependency>
		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-content-model</artifactId>
			<version>${kbee-version}</version>
		</dependency>
		<dependency>
			<groupId>com.novamens</groupId>
			<artifactId>kbee-dm-indexer-java</artifactId>
			<version>${kbee-version}</version>
		</dependency>

		<dependency>
			<groupId>org.apache.lucene</groupId>
			<artifactId>lucene-core</artifactId>
			<version>${lucene-core-version}</version>
		</dependency>

		<dependency>
			<artifactId>solr-solrj</artifactId>
			<groupId>org.apache.solr</groupId>
			<version>${solr-version}</version>

			<exclusions>
				<exclusion>
					<groupId>log4j</groupId>
					<artifactId>log4j</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>jcl-over-slf4j</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

	</dependencies>
</project>

<!-- uncomment for using solr embedded in class
com.novamens.solr.indexer.service.EmbeddedSolrCore 
  		<dependency>
			<artifactId>solr-core</artifactId>
			<groupId>org.apache.solr</groupId>
			<version>8.5.0</version>

			<exclusions>
				<exclusion>
					<groupId>jdk.tools</groupId>
					<artifactId>jdk.tools</artifactId>
				</exclusion>
				<exclusion>
					<groupId>log4j</groupId>
					<artifactId>log4j</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>jcl-over-slf4j</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.eclipse.jetty</groupId>
					<artifactId>*</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		-->
