property.subject=Title for the message
property.text=Your message
text.help= 
property.sendme=Send me a copy by email

property.KBFile=Upload Screenshot
property.screenshot=Upload Screenshot
report-issue=Report Issue
report-issue-info=Please fill in this form. Fields marked  * are required
send=send
