title=Export Contents
close=Close
too-big=The maximum allowed to your account is <b>{1} GB</b> and the files you want to export add up over <b>{0} GB</b>.<br /> You can try reducing the set by applying more filters. <br />Otherwise please contact support if you need more assistance. 
executing=The export process has started.<br /> We will send you an email with a link to download the zip file shortly. <br /> You can safely close this page.

email-disabled=Email Alerts are disabled. We need them to send a the link to download the export. Please enable them back on <a href="\settings\" target=\"_blank\">Settings</a>.