
property.name=Alias



editor.source = Source
editor.audit = Audit Trail
editor.state = Status
property.name = Name
rule.editor.cancel = Cancel
rule.editor.submit = Save
property.id = ID
