security.label = Security
console.name = Sources

sources = Sources

console.label =Sources

# Context Menu (actions applied to the selected content)
sourcesconsole.contextmenu.open=Open 
sourcesconsole.contextmenu.audittrail=Audit Trail


sourcesconsole.column.id = ID
sourcesconsole.column.created = Created
sourcesconsole.column.status = Status
sourcesconsole.column.modified = Modified
sourcesconsole.column.name = Name
sourcesconsole.column.displayname =Name
sourcesconsole.column.modifiedby = Modified by

modified = Modified
created = Created
status=Status


yes=Yes
no=No

new-source=New Source

deleteconfirmation.message = Please confirm to delete source <b>{0}</b> ?
error.constraint = Integrity Constraint. The source can't be removed 
contextmenu.delete = Delete

enabled=<span class="enabled">Enabled</span>
indexing=<span class="enabled">Indexing</span>
deleted=<span class="deleted">Deleted</span>
archived=<span class="archived">Archived</span>
draft=<span class="draft">Draft</span>

