batchcreation=Bulk upload
downloadTemplateBtn=Please download the Template (.xlsx) 

howitworks=<br /><br />Complete the downloaded spreadsheet and upload it back in the field below. <br /> After you execute the import the system will return a xlsx with all rows that have errors and were not imported.<br /><br />Items that do not exist in the System will be <b>created</b>. <br /> Items that exist in the System will be <b>edited</b>.

property.importFile=File
bulkImportTitle=Upload Spreadsheet
import=Import






