myaccount.name=User Settings
myaccount.notification.position=210
myaccount.reset=Reset Preferences
myaccount.edit=Edit
myaccount.title  = Reset Preferences
myaccount.explanation= Completed.

domains=Domains