savedqueries.form.submit=Save
savedqueries.form.cancel=Cancel

savedqueries.title=My Filters

savedqueries.table.edit=Edit

savedqueries.label.edit.ok=Save
savedqueries.label.edit.cancel=Cancel
