PasswordsValidator=the password and verification don't match


UsernameValidator.uniqueness=the name already exist
UsernameValidator.characters=invalid name
UsernameValidator.reservedname=this User Name is reserved


editor.person=Personal Info
editor.user=Account
editor.password=Password

editor.status=Status
editor.workflow=Business Process
editor.groups=Groups <span class="only-root">(root)</span>
editor.roles=Roles
editor.generalpermissions=Rights
editor.relationships=Attributes
editor.activity=User Activity
editor.audit=Audit Trail
editor.emailrules=Workflow Alerts
editor.securityrules=Custom Data Rights

property.firstName=First Name
property.domain=Domain
property.lastName=Last Name
property.email=Email Address

property.photo=Photo
photo.help=Upload your Photo here
property.enabled=Account Enabled
property.editPersonEnabled=User can edit Personal Info

property.role = Role
property.entity = Dynamic

phone.help=Last four digits are used in page <a class="btn-link" target="_blank" href="/forgotusername">Forgot Username</a>
property.phone=Mobile Phone
property.userName=User Name
property.locale=Language

property.password1=Enter New Password
property.password2=Retype New Password
property.groups=Groups
property.group=Group

