title = Parameters
property.content = File
apply=Search

property.from=Modified From <span class="ago">(MM/dd/yyyy)</span>
property.to=Modfified To <span class="ago">(MM/dd/yyyy)</span>

list=List of all Visits
aggregate=Aggregate of Users

property.aggregate-users = List type

version=v

