

batch-actions=Batch Actions
due-date=Due date
post-termination=Post Termination
send-to=Send to
batch-actions-page=Bacth actions page
resolution=Resolution
due-date=Due date
automatic-execution = Automatic Excecution
post-termination=Post Termination
router=Router
precondition=Pre-Condition
security=Security
action-editor=Action and Router - {0}  


enabled=Enabled
archived=Archived

property.event = Event
property.label = Action Name
property.enabled = Status


property.default = Is Default Action

property.description = Description

letter=Letter

property.enablePriority = Allow user to set Process Priority (Normal/High/Urgent)
enablePriority.help=User can set priority of the Workflow.

property.tokenValidation = Token validation
tokenValidation.help = Token validation to end the action


property.requiredResources = Resources are Required
requiredResources.help=At least one resource must be loaded

property.collaboration = "Send to" selector for next Task
collaboration.help=User can select a recipient, like in <b>Peer Review</b>. This field is used when there is no routing rule that applies.

property.collaborationGroups = "Send to" restricted to Roles

property.collaborationSet = "Send to" Person Set

property.groups = Roles

property.batch = Batch Actions
batch.help = Whether the Action is available in the Batch Actions Page.

property.mandatoryLetter = Letter is Mandatory  
 
property.css = Css for UI button
css.help=Css style to apply to the action button.

 
property.templates = Letter Templates (query)
templates.help=Filter that define the set of templates select from in this action.

property.classifiersrules = Set Classifier to
classifiersrules.help=Apply upon task execution.

property.classifier = Classifier
property.value = Value

property.condition = Enable Action (Script). The Action be Enabled when script evaluates true  
condition.help=Script applied to the File that must be true for this Resolution to be enabled. The action will be grayed out until this condition is true.


property.perms = Enable Action (RWD). The Action be Enabled when the User has rights on the File (Read / Write / Delete)
perms.help= Rights required (on the File) in order to have this Action available. Example: <b>Send to Library</b> may require the user have <b>Write</b> permissions. 

property.precondition = Submit Validator. When the user clicks "Submit" this IQL Condition must be true to proceed
precondition.help = When the user clicks "Submit" this IQL Condition is evaluated and it must be true to proceed

property.message = Message

property.infrequent=Send to right menu (for less relevant actions)

property.attributesrules = Set Attribute to 
attributesrules.help=Apply upon task execution.

property.attribute = Atributo
property.value = Valor

property.duedateAction = Due Date Action. Calculate, preserve received due date or set null
property.duedateExpressionType = Expression Type 
property.duedateExpression = Compute (this field is enabled when Due Date Action above is "Calculate") 

duedateExpression.help = <br />Case Expression: <b>CASE IQL THEN VALUE; ... DEFAULTCASE VALUE;</b><br /> Example: <br />\
CASE type(Bond ONLY - Move in) THEN 1; <br />\
CASE type(Market unit) THEN 1; <br />\
CASE type(HUD MI) THEN 1; <br />\
CASE type(HOME ONLY - Move in) THEN 1; <br />\
CASE type(RD Move In) THEN 1; <br />\
CASE type(Other Local Program - MI) THEN 1; <br />\
CASE type(TC Move In) THEN 1; <br />\
CASE type(Bond ONLY - Recert) THEN 2; <br />\
CASE type(TC Recert) THEN 2; <br />\
CASE type(HUD Annual) THEN 2;<br />\
DEFAULTCASE 2;

property.autoRunAfter = Auto Run After (Hs)


jSDuedateExpression.help = Case Expression: <b> javascript that returns a date value

IqlValidator = Invalid IQL

property.reasons = List of Reasons (optional)
reasons.help= List of reasons help !!!

reasons.help=Example: In Peer Review we can add a reason for ask for the collaboration. Reasons can be used to generate Reports  
property.code = Code
property.label = Label

DueDateExpressionValidator = Invalid Case
EventValidator = The event must be unique in the process definition

property.resolutionAction = Action

property.nextTask = Next Task

property.routerScript = Script

addNotification = Add
deleteNotification = Delete Notification
property.notificationText = Text
property.receivers = Receivers
property.roles = Roles

property.router = Router
property.router-publish = Router Publish
property.router-task = Router Task
property.router-return = Router Return
property.router-cancel = Router Cancel

condition.auditlabel = Action {0} of Task {1}:
									
router.1.help = <b>Task</b> After executing the Action the process will execute the next task selected below
router.2.help = <b>Publish</b> After executing the Action the Process ends and the File is Published. This action overrides the user's Permissions to Publish (<b>Write</b> Permission on the Content) 
router.4.help = <b>Cancel</b> After the Action is executed the Process ends and the checkout version is dropped  
router.3.help = <b>Return to Caller Task</b> after the Action is executed the Process will execute a new instance of the previous Task as next Task
router.5.help = <b>Script</b> Javascript script that evaluates the context and returns the id of the next Task. Example: <i>if ( !financial_burden && verification=='Completed Ok') 'ado_review'; else 'legal_review'</i> 


property.template = Template

property.script = Script


property.triggerType = Trigger
triggerType.help = The Security Trigger defines who starts the task and how
