
delete.confirmation.message = Confirm the removal of Launcher {0} ?
launcher.newlink = Add Launcher
launcher.name = Process Launcher
launcher.description = Description

launcher.context = Applies to
mytask.context = My Tasks
library.context = Library
mobile.context = Mobile

"--

delete.menuitem = Delete
add-launcher = Add Launcher