
procedure.label = Procedure

procedure-name= Info - {0}

procedure=Business Process
property.id = Id
property.icon = Icon
property.name = Name
property.key = Alias
property.displayName=Name
displayName.help=This field is readonly. The Procedure name is taken from the Launcher name.

property.classifiersrules = On Start -> set Classifier

property.attributesrules = On Start ->  set Attribute
attributesrules.help=For Date Attributes Today is:  <b>${.now?string["yyyy-MM-dd"]}</b>



property.scriptrule = On Start -> execute Script

property.value = Value

property.roles = Workflow Role (W-Role)</span>
roles.help= ROLES HELP

property.phases = Procedure Phases

start=On Start

property.label = Label

property.code =Alias

property.subprocedure = Subprocess

task-table-help= Click on the (i) for help
add-task=Add Task

task-table-help-window=<div class="col-lg-12 panel"><h2>Name</h2><p>Name<i>(initial)</i> -> the initial task when the Workflow starts.</p></div> \
<div class="col-lg-12 panel"><h2>Security Trigger</h2><p>Task starting strategy. Whether the new task is sent to Pending or assigned to last user who did the same task before, or sent to user with right Role ...). Initial Task is special case, the trigger is manual</p></div>\
<div class="col-lg-12 panel"><h3>Round Robin</h3> Assign the task to the user/s that have the Workflow Role (W-Role) assigned via Security Roles. If there is more than one user the assign policy is round-robin.</div>\
<div class="col-lg-12 panel"><h3>Other</h3> There are more triggers available see here.</div>\
<div class="col-lg-12 panel"><h2>Action</h2><p>Action that terminates the Task -> routing strategy for the action</p></div> \
<div class="col-lg-12 panel"><h2>Workflow Role (W-Role)</h2><p>Workflow Role to assign to the user that executes the Task </p></div> \
<div class="col-lg-12 panel"><h2>Precondition</h2><p>IQL Condition that must be true for the Task to Start. If it is not true, the Task is sent to Pending</p></div>
