task.auditname = Audit

open-email-template = open email template
send-test-email = send me test email
task-alerts = Alerts

property.dueDateAlerts = Days before due date
dueDateAlerts.help = Time expressed in days with values separated by ';'

property.maxTimePending = Max Time Pending (days)
maxTimePending.help = Time expressed in days. Values equal to or less than zero indicate unlimited time. When the limit is reached, users with monitoring permission are notified.

property.maxTimeRunning = Max Time Running (days)
maxTimeRunning.help = Time expressed in days. Values equal to or less than zero indicate unlimited time. When the limit is reached, users with monitoring permission are notified.
