intial=Initial
name=Task
actions=Action -> Router
trigger=Security Trigger
role=Workflow Role (W-Role)
description=Description

precondition=Precondition
enabledroles = Task Permissions in Role 
tasks=Tasks
confirmation.DeleteTask = Delete <b>{0}</b> task?
task-table-help=click on the (i) for help 

add-task = Add Task
add-forktask = Add Fork Task

publish=Publish
return-caller=Return to Caller
js-script=JS Script
if-condition-falis=if condition fail
thread-end=Return
initial=Initial
description=Description
initial=Initial
precondition=Precondition 
tasks=Tasks
confirmation.DeleteTask = Delete <b>{0}</b> task?
task-table-help=click on the (i) for help
subprocedure = Subprocess
 
new-task=New Task
