task.auditname = {0} Task:
property.precondition = Task IQL Precondition (must be true to start the Task)
property.taskOnPreconditionFail = Failover Task when precondition is false
failover=Failover Task