
structure=Task Structure
related-queries=Queries

property.multiplicity = Multiplicity
property.element = Element
property.type = Type
property.ordered = Ordered
property.visible = Visible
property.MetadataSubtitle=Subtitles
property.readOnly = Readonly
property.source = Input
property.accessibility = Selector Strategy (Classifier)
property.type = Type
property.label = Label
property.name = Name
property.selectionScript = Script for Selection
property.calculationScript = Script for Calculation

selectionScript.help = The returned value must be the display name of the selected value

property.panel = 
property.enabled = Enabled

editor.task = Task Info
editor.threads = Threads

confirmation.DeleteCondition = Delete <b>{0}</b> condition?