
js-script=JS Script
library=Library
other=Other
security=Security
events=Events
task-info = Task Info
property.id = Id
id.help=Task id can not be changed if there are Processes under execution for this Procedure
property.name = Name
property.description = Task Description
property.routerScript = Router
property.initial = Is initial Task ?
initial.help=Intial Task when the Process start

property.phase = Phase  
phase.help=Select 'none' to inherit the value from the context.

property.cancelEnabled = User can Abort Process
cancelEnabled.help=The User can Abort the Process from this Task (Drop checkout and terminate the workflow).

property.state = State

property.role =Workflow Role (W-Role) 
role.help=The user executing the Task will be assigned this Workflow Role (W-Role)

property.onStart = On Start Execute	
	
take-label = Take
backup-label = Backup

task.auditname = {0} Task:

IdValidator =  Id must be unique