
contingency=Backup Task
resolution-letter=Resolution Letter


timeout=(Timeout Action)
action-router=(Action and Router)
structure=Task Structure
related-queries=Queries
editor.forms=Forms
editor.alerts=Alerts

property.knowledgeCriteria = Knowledge Base Query
knowledgeCriteria.help = Click on (i) icon to see help on IQL Sentences

property.relatedCriteria = Related Files Query
relatedCriteria.help= Click on (i) icon to see help on IQL Sentences



property.section = Name
property.multiplicity = Multiplicity
property.element = Element
property.structure = Elements
property.type = Type
#property.default = Default
property.ordered = Ordered
property.visible = Visible
property.MetadataSubtitle=Subtitles
property.inherited = Inherit all in Dependent Relations
property.readOnly = Readonly
property.classifier = Classifier
property.classifiers = Classifiers
property.attributes = Attributes
property.multiplicity = #Elements
property.source = Input
property.accessibility = Selector Strategy (Classifier)
property.metadataSubtitle =Subtitles
property.type = Type
property.canonical = System
property.label = Label
property.attribute = Attribute
property.abstract = Public Notes/Abstract
property.subsection = Subsection
property.name = Name
property.valuesCriteria = IQL 
property.selectionScript = Script for Selection
property.calculationScript = Script for Calculation

selectionScript.help = The returned value must be the display name of the selected value

property.includeCallerForms = Include Forms from Caller Task
includeCallerForms.help=Forms included in the caller task are also included in this Task. This is normally used for tasks like Peer Review. 


property.form = Form
property.forms = Task Forms
property.panel = 
property.enabled = Enabled

editor.task = Task Info
editor.structure = Structure

editor.related-queries=Related Queries
menu.down = Down
menu.up = Up
menu.delete = Delete

confirmation.DeleteCondition = Delete <b>{0}</b> condition?


