
js-script=JS Script
return-caller=Return to Caller
library=Library
due-date=Due date
letters=Resolution Letter
other=Other
add-action=add action
failover=Failover
security=Security
actions=Actions and Routers
events=Events
task-info = Task Info
property.id = Id
id.help=Task id can not be changed if there are Processes under execution for this Procedure
property.name = Name
property.description = Task Description

property.initial = Is initial Task ?
initial.help=Intial Task when the Process start

property.phase = Phase  
phase.help=Select 'none' to inherit the value from the context.

property.timeLimit = Task Duration (1st time)
timeLimit.help = Time allowed in full days. 0 for no limit.

property.knowledgeCriteria = Knowledge Base Query
knowledgeCriteria.help = Click on (i) icon iql sentence

property.relatedCriteria = Libraries Query
relatedCriteria.help= Click on (i) icon iql sentence

property.precondition = Task IQL Precondition (must be true to start the Task)
property.taskOnPreconditionFail = Failover Task when precondition is false

property.cancelEnabled = User can Abort Process
cancelEnabled.help=The User can Abort the Process from this Task (Drop checkout and terminate the workflow).

property.enableProgressNotes = Task Progress Notes Enabled

property.state = State

property.resolutionAction = What to do with Resolution Letter (if received) 
resolutionAction.help=If the Task receives a Letter -> <b>Pass through</b>: to next Task, this is for intermediate Tasks between the Analyst and Submitter. <b>Archive</b>: Convert to a pdf Resource

property.enableEditingAllResources = User can Edit Resources
enableEditingAllResources.help=Attachments from previous tasks are editable or read only.

property.editableTitle = User can Edit Title
editableTitle.help=Note that if you select <b>YES</b> the ContentTemplate must have title edit enabled (see {0}) 

property.triggerType = Trigger (Strategy to start the Task)
triggerType.help = The Security Trigger defines who starts the task and how

property.role =Workflow Role (W-Role) 
role.help=The user executing the Task will be assigned this Workflow Role (W-Role)

property.enabledGroups = Enabled Groups
enabledGroups.help = Enabled groups for the manual assignment of this task

property.enablePublicLink = Public link

property.enableLabels = Enable tags on the title (a label with a color icon) 

property.enabledRoles = Users that can be Reassigned the Task (<i>Reassign Task</i>) or can be selected for Collaboration (<i>Peer Review</i>)  

property.roles = Roles

property.maxTimePending = Max Time Pending
maxTimePending.help = Time expressed in days. Values equal to or less than zero indicate unlimited time. When the limit is reached, users with monitoring permission are notified.

property.maxTimeRunning = Max Time Running
maxTimeRunning.help = Time expressed in days. Values equal to or less than zero indicate unlimited time. When the limit is reached, users with monitoring permission are notified.

all = Yes (all are editable) 
just-this-task= No (only the Task´s Resources)

property.duedateAction = Due Date Action. Calculate, preserve received due date or set null
property.duedateExpression = Compute (this field is enabled when Due Date Action above is "Calculate")

dueDateJsExamples = <div class="panel col-lg-12"><p class="text col-lg-12">Examples: </p> \
	<div class="panel" style="margin-top:10px;float:left;"> \
	<p class="text col-lg-12 ago" style="font-style: italic;">content.getDateTime('duedate')</p> \
	</div></div>

property.version = Version

property.taskPage = Task Page Factory
	
	
property.onStart = On Start Execute	
	
take-label = Take
backup-label = Backup

condition.label = Action
condition.router = Router
condition.enabled = Enabled
condition.precondition = IQL Precondition 

task.auditname = {0} Task:

IqlValidator = Syntax Error
IdValidator =  Id must be unique
