property.event = Event
property.label = Action Name
property.enabled = Is Enabled

property.note = Note

property.classifiersrules = Set Classifier to
classifiersrules.help=Apply upon task execution.

property.classifier = Classifier
property.value = Value

property.precondition = Precondition
property.condition = Condition
property.message = Message

property.infrequent=Infrequent

property.attributesrules = Set Attribute to
attributesrules.help=Apply upon task execution.

property.attribute = Attribute
property.value = Value

property.duration = Duration
duration.help = In Business Days