
none = None

property.triggerType = Trigger (Strategy to start the Task)
triggerType.help = The Security Trigger defines who starts the task and how


trigger.manual.help = <p>The Task is sent to Pending. Users with 'Take' permissions (as assigned by Security Roles) can take it.</p> 
trigger.manual-lastuser.help = <p>1st time -> Pending. 2nd and following times, last user who executed the task.</p>


trigger.userautomaic.help = <p>The Task is assigned to a specific user</p>


trigger.userautomaic-lastuser.help =
trigger.role.help =
trigger.collaborator.help =<p>The Task is assigned to the Collaborator selected in the Task Action</p>
trigger.1task.help = 


trigger.manual.help = Task is not started but stays in <b>Pending</b> waiting to be taken by a user with <b>Take</b> permissions (for this Task) as defined by the <a class="btn-link" href="/security/roles" target="_blank"></b>Security Roles</b></a>. <br />Example: When a Site Submits a File and the File goes to Pending to wait for an Analyst to Take. 
trigger.manual-lastuser.help = <b>1st time</b>: the task is assigned to the User that creates the File (for new Files) or sent to Pending | <b>2nd and following times</b>: the Task is initiated automatically and assigned to the user that executed the task in the last iteration. <br /> Example: A <b>File Review</b> that goes to Pending the first time, but once an Analyst takes it, the next iterations it goes to that user.


take-label = Take
backup-label = Backup