contextmenu.open=Open


console.section = Audit

console.label = Find a File
console.name = Find a File
console.displayname=Find a File

systemlog = User Activity
emaillog = Email
xplorer = Resources
contentlog = Find a File


audit.title=Audit {0}


eventtypecolumn=Event
objectclasscolumn=Object Class
eventactioncolumn=Action
descriptioncolumn=Description


titlecolumn = Title
datecolumn = Modified Date
taskcolumn = Task
idcolumn = OId - version - Id
pathcolumn=File System
sizecolumn=Size
crc32column=CRC32
sha256column=SHA 256
usercolumn=User
iconcolumn=Icon


executedcolumn=Date 

eventcolumn=Event
usercolumn=User
actioncolumn=Action
resultcolumn=Result
fromcolumn=From
tocolumn=To
textcolumn=Text
attachmentscolumn=Attachments
kbeeclasscolumn=Internal Class
domaincolumn=Domain
urlcolumn=URL

taskprioritycolumn=Priority
workspacecolumn=Workspace

audit.title=Audit {0}
modal.sendbyemail.title=Share


