property.oid=OId
property.cid=Id
property.title=Title

property.from-date=From
property.to-date=To

apply=Search


property.range=Date Range
property.executedfrom=From (MM/DD/YYYY)
property.executedto=To (MM/DD/YYYY)


1minute = 1 minute
5minutes = 5 minutes
15minutes = 15 minutes
1hour = 1 hour
1hour = 4 hour
1day = 1 day
2day = 2 days
3day = 2 days
1week = 1 week
1month = 1 month
3months = 3 months
1year = 1 year
2year = 2 years
3year = 2 years
all = All

