



cronexpression=Next / Frequency (CronExpression)
group=Group
user=User

startpub=From
endpub=To


new-alert=New

yes=Yes
no=No

html-yes=<span class="yes">Yes</span>
html-no=<span class="no">No</span>

total-read=Total Read 
work-notes=Billboard and Manual Alerts
console.label = Billboard and Manual Alerts
console.name = Billboard and Manual Alerts
console.displayname = Billboard and Manual Alerts   
section=Settings

new = New 
tools=Content

name = Note
audittrail=Audit Trail
receivers=Send to
reports=Reports

contextmenu.edit=Edit
contextmenu.delete=Delete

contextmenu.mark-as-read=Mark as read
contextmenu.mark-as-unread=Mark as unread
note-editor-title=Work Note Editor

column.unread=
delete.confirmation.message=Please Confirm you want to delete the Note: <b>{0}</b>  
 
 
 alert-type=Type
 worknotes.markall=Mark as Read
 billboard=Billboard
 alert=Alert
 alerts=Alerts
 email=Email
 icon=Icon
 
created=Created
modified=Modified


description=Description
console-description=<section><h3>Alerts and Billboards</h3><p>Regular Alerts (top bell) and Billboard Alerts</p></section>
 