console.name=File Server

column.size=Size
column.rights=Rights
modified=Modified


iconcolumn=Icon
contextmenu.download=Download
column.name=Name

file-server=File Server

column.type=Type
thcolumn=Thumbnail

upload=Upload
create=Create
opendir=Open Directory
edit=Edit
sendrecycle=Send to Recycle Bin
delete=Delete