
file-server= back to File Server
upload-file=Upload File
close=Close
folder=Folder
uploaded=Uploaded

form.uploadTooLarge = Progress - File must be less than ${maxSize}.
form.uploadSingleFileTooLarge = Progress - Each of files must be less than ${fileMaxSize}.
form.uploadFailed = Progress - File failed to upload: ${exception.localizedMessage}

localfile=Select Local File
