
remember-query=Remember Filters Applied 
grid=Grid
list=List
tree=Tree


COLLOQUIAL=Standard  
COLLOQUIAL_AGO=Standard (ago)
DATE=mm d yyyy
FULL=mm d yyyy · h:mm a
TIMESTAMP=mm d yyyy · hh:mm:ss zzz



date-format=Date format
rows-per-grid=Rows per page

date-grid=Date format
grid-rows=Items per page
modal.grid-config.title = Page settings


working=loading

compact-view=Compact View
comfortable-view = Comfortable View

grid-settings=Grid Settings
cell-borders=Cell Borders
grid-reset-defaults=Reset to default settings
background-odd=Background odd rows