reorder = Drag & Drop Elements to Reorder
menu.up = Move Up
menu.down = Move Down
property.page-size=Lines per Page

page-size.property=Lines per Page
property.icon-mode=Image

property.date-format=Date Format

COLLOQUIAL=Standard  
COLLOQUIAL_AGO=Standard (ago)
DATE=mm d yyyy
FULL=mm d yyyy · h:mm a
TIMESTAMP=mm d yyyy · hh:mm:ss zzz




move-to-first=Move to first
move-to-last=Move to last
