action=Actions
action-short= 
error-msg = <p>The grid can not be rendered due to an application problem. <br /> Please contact support.</p><p>More info: <br />


insert-column-right=Insert column (right)
hide=Hide column
move-left=Column Move left
move-right=Column Move right
increase-10=Increase column width 20%
reduce-10=Reduce column width 20%

move=Move column
width=Column width

right=right
left=left