
texy_general_right-title =
texy_general_right-text =
 
texy_general_left-title = 
texy_general_left-text =

texy_aniversary_right-title = Happy Aniversary
texy_aniversary_right-text =

texy_aniversary_left-title = Happy Aniversary
texy_aniversary_left-text =

texy_christmas_right-title = Merry Christmas and Happy Holidays
texy_christmas_right-text = Our best wishes from the RPDOC Team!

texy_christmas_left-title = Merry Christmas and Happy Holidays
texy_christmas_left-text = Our best wishes from the RPDOC Team!

texy_hi_left-title =
texy_hi_left-text =

texy_hi_right-title =
texy_hi_right-text =
		
texy_realpage_right-title= 
texy_realpage_right-text=

texy_realpage_left-title = 
texy_realpage_left-text = Hi. I am Texy, the new RPDOC mascot. <br /> You will see me around.

texy_4july_right-title = 
texy_4july_right-text = Hi. I am Texy, the new RPDOC mascot. <br />  You will see me around.

texy_4july_left-title =  
texy_4july_left-text = Have a happy 4th of July !

texy_help_right-title =
texy_help_right-text = Have a happy 4th of July ! 

texy_help_left-title =
texy_help_left-text = 


texy_new_year_right-title = 
texy_new_year_right-text = Happy New Year !

texy_new_year_green_right-title = 
texy_new_year_green_right-text = Happy new Year !
	
texy_paper_right-title  = Paper 
texy_paper_right-text =

texy_paper_left-title = Paper 
texy_paper_left-text =


texy_thanksgiving_left-title = Happy Thanksgiving ! 
texy_thanksgiving_left-text = 

texy_thanksgiving_green_left-title = Happy Thanksgiving !
texy_thanksgiving_green_left-text =  


texy_thanksgiving_gray_left-title = Happy Thanksgiving !
texy_thanksgiving_gray_left-text = 
	
texy_tools_right-title =
texy_tools_right-text =

texy_tools_left-text =
texy_tools_left-text =	 
	 

texy_training_right-title = 
texy_training_right-text =

texy_training_left-title =
texy_training_left-text =
	
texy_welcome_left-title = Welcome to RPDOC !
texy_welcome_left-text = I am Texy, the new RPDOC mascot. <br /> You will see me around.
					
texy_welcome_right-title = Welcome to RPDOC !
texy_welcome_right-text = I am Texy, the new RPDOC mascot. <br /> You will see me around.

texy_new_version_left-title =  
texy_new_version_left-text = We just installed a new version. <br /> See what is new here.
					
					
					
					
					