

search-in=Search in 

console-description = Abstract Console description
console-name=Console name

group=Group
user=User

modal.sendbyemail.title=Share

tools.grid.export.csv=Download Grid (.csv)
tools.grid.export.xls=Download Grid (.xlsx)
									
tools.grid.setasdefaultpreferences=Set as Default Preferences


gridexport.tooManyItems=Too many item to export. <br /> Items to export: <b>{0}</b> <br /> Limit: <b>{1}</b> items


yes=Yes
no=No

yeshtml=<span class="yes">Yes</span>
nohtml=<span class="no">No</span>


modified-desc=Modified (desc)
modified-asc=Modified (asc)
title-desc=Title 