modal.treefilecreation.title = Importar Árbol de Archivos
button.previous = Volver
button.next = Continuar
button.confirm = Confirmar
confirmation-message = Se importará el árbol de archivos contenido en <b>%1</b> con puntos de entrada en los archivos <b>%2</b>
error-message = Se debe seleccionar al menos un punto de entrada para el sistema