info = File Information
warning-owner = Only <b>{0}</b> can edit forms and execute actions.
task-is-pending = The task is Pending. <br/>Only authorized users can Take it.
take-action-help = When you take the task the file is moved to your working area
take-action-label = Take