
edit-title=Edit title
add-tag=Add tag

not-editable=The Content Template has title set to not-editable (see template <a target="_blank" href="{0}">{1}</a>)
title = Title
cancel = Cancel
save = Save
close = Close
edit = Edit
new=New
enable-rule=Apply Rule
view-rule=View Rule