orlabel = o
help1 = Eligible users must have an active account and be enabled for business processes (see user account). 
help2 = The selectable users are those belonging to the groups {0}. In addition, users must have an active account and be enabled for business processes (see user account)
help3 = The selectable users are those belonging to the group {0}. In addition, users must have an active account and be enabled for business processes (see user account)