editor.general-info=General
editor.home-info=Home 
editor.about-info=About
editor.contact-info=Contact
editor.iql=Portal Contents
editor.state=Status

property.state=Status
editor.filters=Filters

editor.attributes=Attributes
editor.audit=Audit