property.iql=Iql
property.title=Title
property.subtitle=Subtitle
property.maxElements=Max items
property.includeMetadata=Display item subtitle

property.sort=IQL ResultSet order by 
property.orderSet=Order items in Panel by 
 