area=Organizational Area
interest-group=Interest Group 
standalone=Standalone
external=External


general=General 
drbit=Dr bit
home=Home
directory=Directory
kbase=Knowledge Base
dealroom=Deal Room
	
