

project=Project
minisite=Minisite

kbase=Knowledge Base
general=General
home=Home
dealroom=Deal Room

simple-submit=Simple submit
internal=Internal
tutorial=Tutorial
help=Help
external=External



interest-group=Interest Group Site 
subject=Subject 
area=Area Site
directory=Directory

blog=Blog
application=Application
global-elements=Global Elements
event=Event


portal=Portal Web
social=Red Social
ecommerce=Comercio Electrónico
search=Buscador
video=Videos
music=Música
gov=Gobierno y Sector Público

	

general_dasboard=One page Dashboard  	
simple-submit=Submit Site
internal=Internal
library=Library			


institutional=Institutional
