new-action = New
ClassificationAction = Add Tag
RemoveClassificationAction = Remove Tag
NotificationAction = Send Alert
ArchiveAction = Archive File
DeleteAction = Delete (Send to Recycle bin)
LaunchAction = Launch Process