
console-description=Action Rules
console.name = Time Based Alerts
rules = Time dependent Actions
console.label = Time Based Alerts

# Context Menu (actions applied to the selected content)
rulesconsole.contextmenu.open = Open 
rulesconsole.contextmenu.audittrail = Audit

rulesconsole.column.status=St
rulesconsole.column.name = Name
rulesconsole.column.id = ID
rulesconsole.column.key = Alias
rulesconsole.column.status= Status
rulesconsole.column.modified = Modified
rulesconsole.column.modifiedby = Modified by
rulesconsole.column.criteria = Condition (IQL)
rulesconsole.column.content = Content
rulesconsole.column.execdate = Execution Date
rulesconsole.column.order = Order

modified = Modified
created = Created
status=Status
totalcontents=Total Contents

yes=Yes
no=No

deleteconfirmation.message = Please confirm to delete Rule <b>{0}</b> ?
error.constraint = Integrity Constraint. The Rule can't be removed 
contextmenu.delete = Delete

enabled=<span class="enabled">Enabled</span>
indexing=<span class="enabled">Indexing</span>
deleted=<span class="deleted">Deleted</span>
archived=<span class="archived">Archived</span>
draft=<span class="draft">Draft</span>

searchplaceholder=Search in Rules

user-email-disabled-grid-export=You have disabled email notifications. <br />We will not be able to send you the export. <br />Please enable them back in <a class=\"btn-link\" href=\"/myaccount\" target="_blank">User Settings</a>, tab Account.
modifieduser=User
