actions = Actions
editor.rule = Time Based Alert
editor.audit= Audit Trail
rule.editor.cancel = Cancel
rule.editor.submit = Save
editor.users = Members
editor.state = Status
editor.useradmin = User Admin
IqlValidator = Syntax error

property.id=Id
property.name = Name
property.condition = Condition
property.content=Content
property.executionDate=Execution date
delete=Delete
+ 