type = Add or Remove Tag
remove-type = Remove Tag

property.type = Action
type.help=What to do when a File meet the Condition

property.classifier = Classifier
classifier.help=This selector includes just Classifiers (it does not include String or Date Attributes) 


property.values = Tags
property.value = Tag Value
