actions = Action
editor.rule = Time Based Alert
editor.audit= Audit Trail
property.name = Name
rule.editor.cancel = Cancel
rule.editor.submit = Save
property.id=Id
editor.users = Members
editor.state = Status
editor.useradmin = User Admin
property.condition = Condition

invalid-date.message = Date {0} is invalid
condition.help = Ingresar 1 fecha por renglón con formato <b>dd/MM</b> (para repetir todos los años) o <b>dd/MM/yyyy</b> (para 1 ejecución)

delete=Delete

ENABLED = Active
ARCHIVED = Pause