type = Process Launch

property.type = Action
type.help=What to do when a File meet the Condition

property.launcher = Launcher
launcher.help = Lanzadores de procesos habilitados para Api y Reglas

property.note = Nota

test-link.message = test-link.message = Crear Documento e Iniciar Proceso
launcher-link.message = Ver Lanzador 

test-ok.message = Se creó ->  <a target="_blank" class="btn-link" href="{0}">{1}</a>.<br/> Ver en el <a target="_blank"  class="btn-link" href="/monitor">Monitor</a>	

triggers-msg= El Documento será asignado según las Estrategia de Inicio de las Tareas del Procedimiento seleccionado