error.required = {0} is Required
error.mail_not_unique = Email address already registered

newuser.message.sucess = The user was created successfully 

newuser.action.label = Next steps
newuser.action.return = <- Back to Users
newuser.action.create = Create Another User
newuser.action.edit = Edit Properties and Add Roles  
