token=Security Code
check=Check
sms=My Mobile Phone
property.phone=Mobile Phone
property.tokenValidation=Please enter the <b>Security Code</b> received

phone.help=Enter the number including country code (Examples. <b>US</b>:1 <b>Argentina</b>:54)

info-sms=The phone number is used for digital signatures.
test-sms=Send Security Code  

test-sms-title=Send a Test SMS


sec-token = kbee Security Code: {0}
token-sent=<span>Security Code sent -> <b>{0}</b></span>
remember-country-code=Please note that the phone number must include the country code (eg US:1, Argentina: 54, etc.)
