personal-info.label = Person
error.required = <b>{0}</b> es requerido
error.not_number = <b>{0}</b> debe ser numérico		
error.mail_not_unique = Mail ya registrado
error.mail_not_valid = Mail no válido