

property.phone.help=This field is mandatory.
property.email.help=This field is mandatory.
property.lastName.help=This field is mandatory.
property.workPosition=Job Profile  

property.photoDomainLogo=
property.photoDomainLogo=Domain logo over photo <span style="font-weight:normal; text-transform: none"> \
( see field <i>LOGO</i> in <a class="btn-link" target="_blank" href="/domain/settings">General Settings</a> )</span> 


account-disabled=The Adminstrator has disabled editing Personal Information.
person=Person

property.emailValidated=Email Validated
property.id=Person Id 
id.help= Readonly

system-user-title=System Acount
system-user-text=This account does not belong to a regular user. It is used by the System for internal processes such as workflow, portals and resource management.
