


property.emailNotifications	=   Task Assigned
emailNotifications.help  =	Enviar alerta al usuario <i>{0}</i> cuando recibe una Tarea


property.emailPendingNotifications	= Pending Task  
emailPendingNotifications.help = Enviar alerta al usuario <i>{0}</i> cuando hay una nueva Tarea Pendiente que puede tomar
emailPendingNotifications-myaccount.help = Enviarme alerta cuando hay una nueva Tarea Pendiente que puedo Tomar

property.emailRuleNotifications	= Alertas por Reglas 
emailRuleNotifications.help	= Enviarme una alerta por una Regla

property.alertRuleNotification = Alertas por Reglas
alertRuleNotification.help = Enviarme una Notificación en el panel por una Regla

property.emailProgressNoteNotification = Notas de Avance de Tarea
emailProgressNoteNotification.help = Enviarme una alerta cuando haya una nueva Nota de Avance de Tarea

property.alertProgressNoteNotification =  Notas de Avance de Tarea
alertProgressNoteNotification.help = Habilitar notificación en panel cuando haya una nueva Nota de Avance de Tarea

property.whatsAppEnabled = WhatsApp
 
channels = Canales

my-subscriptions=Seguimiento
my-alerts-settings=Configuración general
my-email-alerts=Alertas (correo electrónico, Whatsapp)
email-rules=Alertas por Reglas 
dialog.delete.title=Confirme
dialog.delete.message=Borra Regla de Notificación {0}
norules=No hay reglas
add-label=Agregar
enoti=Alerta por Regla {0}
alert-note=Reglas para que el sistema envíe correo electrónico. Nota: El selector "Alertas por Reglas" de arriba tiene que estar habilitado para que se envíen los correos.

subscriptions-message=Contenidos seguidos. En el <a class="btn-link" href="/monitor" target="_blank">Monitor de Procesos</a> puede suscribirse/desuscribirse a cada contenido
subscriptions-message-myaccount=Contenidos seguidos. En el <a class="btn-link" href="/monitor" target="_blank">Monitor de Procesos</a> puede suscribirse/desuscribirse a cada contenido


#-- NOTA: Las notificaciones por <b>Tareas Asignadas</b> a su usuario se configuran en el editor de <a targat="_blank" href="/myaccount?tab=account" class="btn-link">Cuenta de Usuario</a>.
#--------------

whatsAppEnabled.help=Send me Alerts by WhatsApp

subscriptions-message = Contents monitored
property.emailNotifications = Task Received
emailNotifications.help = Send email notification when {0} receives a new Task
emailNotifications-myaccount.help = Send me an email notification when I receive a new Task

property.emailPendingNotifications = Pending Task  
emailPendingNotifications.help = Send email notification when there is a new Pending Task that the {0} can take
emailPendingNotifications-myaccount.help = Send me alert when there is a new Pending Task that I can take

property.emailRuleNotifications = Alerts by Rules 
emailRuleNotifications.help = Enable email alerts by rules defined in section EMAIL ALERTS below  

property.alertRuleNotification = Alerts by Rules 1
alertRuleNotification.help = Enable internal alerts by rules defined in section EMAIL ALERTS below

property.emailProgressNoteNotification = Task Progress Notes
emailProgressNoteNotification.help = Send me email alert when there is a new Progress Note that I can read

property.alertProgressNoteNotification = Task Progress Notes
alertProgressNoteNotification.help = Enable notifications in panel when is a new Progress Note


my-alerts-settings=Settings
email-rules=Email Alerts

my-subscriptions=Subscriptions
my-email-alerts=Rules

dialog.delete.title=Confirm
dialog.delete.message=Delete Rule <b>{0}</b> ?
norules=
add-label=Add
enoti=Email Notification {0} 

alert-note=Self service rules to receive email or internal notification when a File that has certain tags is <b>Published</b> or has there is a new <b>Pending Task</b>.


channels = channels
emailNotifications-myaccount.help	=Send me alert when I receive a new Task