
linkedAccounts=Linked Accounts
noLinkedAccounts=No accounts are linked yet.

add-google=Add login with Google
add-apple=Add login with Apple
add-facebook=Add login with Facebook

property.googleAuth = Google Login
property.googleUserPlatformId=Google Email Account 

property.facebookAuth =Facebook Login
property.facebookUserPlatformId=Facebook Email Account

externalLogin=External Login Options
property.enableGoogleLogin=Google Login

property.enableFacebookLogin=Facebook Login

enableGoogleLogin.help=Allow login using Google Account.
enableFacebookLogin.help=Allow login using Facebook Account.


googleUserPlatformId=Must be a Google email account (either gmail.com or managed by Google)