

accessvaliditydate=Access Validity Date


set-groups-modal.title=Set Rights 
reset-password-modal.title=Reset Password 

yes=<span class="yes">Yes</span>
no=<span class="no">No</span>

users=Users

gridexport.confirm=Please confirm you want to export a grid of <b>{0}</b> items ?<br />You will receive an email with a .csv file that can be opened with Excel and other Spreadsheets.
toomanyitems=Unfortunately your selection has <b>{1}</b> items.<br/>Your Profile has a limit of <b>{0}</b> items. <br /> Please narrow down yor grid. 

user-email-disabled-grid-export=You have disabled email notifications. <br />We will not be able to send you the export. <br />Please enable them back in <a class=\"btn-link\" href=\"/myaccount\" target="_blank">User Settings</a>, tab Account.

security.label = Security
console.name = Users
console.label=Security

show-deleted=Show Deleted
hide-deleted=Hide Deleted

usersconsole.contextmenu.forceLogOut.sessionsKilled=Sessions killed for user %s

bulk-creation=  Creation

edit=edit
usersconsole.new-user-label = New User

new = New User
archive=Archive

searchplaceholder=Search in Users

enabled=<span class="enabled">Enabled</span>
disabled=<span class="disabled">Archived</span>

usersconsole.action.create = New
usersconsole.action.delete = Delete 
usersconsole.order.modification = Date Modified
usersconsole.order.name = Name
usersconsole.order.relevance = Relevance


usersconsole.contextmenu.forceLogOut=Force Logout
usersconsole.contextmenu.createfrom=Create New User with the same roles
usersconsole.contextmenu.markasdelete=Mark as Deleted
usersconsole.contextmenu.restore=Restore


usersconsole.contextmenu.open = Open
usersconsole.contextmenu.disable = Archive
usersconsole.contextmenu.disabling = Working...
usersconsole.contextmenu.delete = Delete
usersconsole.contextmenu.resetpassword = Send email to Reset Password
usersconsole.contextmenu.resetpasswordbymail = Send email with link to reset password
usersconsole.contextmenu.enable = Enable
usersconsole.contextmenu.enabling = Working...
usersconsole.contextmenu.audittrail = Audit Trail
usersconsole.contextmenu.clone = Clone
usersconsole.contextmenu.reindex = Repair Workspace
usersconsole.contextmenu.reindexing = Working
usersconsole.contextmenu.resetpreferences = Reset preferences
usersconsole.contextmenu.resetingpreferences = Working
usersconsole.column.lastname=Last name
usersconsole.contextmenu.working = Working
usersconsole.contextmenu.impersonate = Sign in as this user
usersconsole.contextmenu.addto = Add to {0}

labels=Labels


usersconsole.column.device = Mobile Device

usersconsole.column.lastpasswordchange=Last Password change
usersconsole.column.name = Name
usersconsole.column.firstname = First Name
usersconsole.column.lastname = Last Name
usersconsole.column.active = Active
usersconsole.column.name = Name
usersconsole.column.username = User Name
usersconsole.column.id = ID
usersconsole.column.externalid = OneSite ID
usersconsole.column.language = Language
usersconsole.column.email = Email
usersconsole.column.status = Status
usersconsole.column.status-shrot = St
usersconsole.column.modified = Modified
usersconsole.column.modifieduser = User
usersconsole.column.groups=Groups
usersconsole.column.email-pending=Email Pending
usersconsole.column.notifications=Email Tasks
usersconsole.column.modifieduser=Modified by
usersconsole.column.phone=Mobile Phone
usersconsole.column.photo=Photo
usersconsole.column.emailnoti=Workflow Alerts
usersconsole.column.groups=Groups
usersconsole.column.emailnotistatus=Alerts
usersconsole.column.timezone=Time Zone
usersconsole.column.displayname=Lastname, Firstname
usersconsole.column.rules = Custom Data Rights
usersconsole.column.activeSessions=Active Sessions
usersconsole.column.lastlogin = Last Login
usersconsole.column.profiletype = Profile Type

usersconsole.column.roles=Roles
usersconsole.column.generalpermissions=Rights

usersconsole.cleanindex.title = Clean Index {0}
usersconsole.reindex.title = Reindex {0}

userconsole.resetpassword.title = Reset Password
userconsole.resetpassword.working = Sending...
userconsole.resetpassword.done = We sent a email notification to <b>{0}</b> <br />with the instructions.

usersconsole.deleteconfirmation.message = Delete user <b>{0}</b> ?
usersconsole.error.constraint = The object is referenced by other objects

usersconsole.mail.subject = Reset password: {0} ({1})
usersconsole.mail.text = The user admin has sent you this link to reset your account password.\nPlease visit the link below and follow the instructions.\n{0}.\nFor security reasons, you will need to click on the link within 1 hour from when the request was made. You can safely ignore this email if you do not want to change your password.\n\nThanks. The {1} Team.
usersconsole.mail.fromemail = noreply <{0}>

usersconsole.status.enabled = Enabled
usersconsole.status.disabled = Archived

 quotalimit=Users Quota completed
 

