open=Open

userid=User ID: 
name=User Name:
email:Email:
phone=Mobile Phone:
active=Active:
notifications=Task notifications:
notifications-rule=Email Rule notifications:
pending-notifications=Pending Task notifications:

groups=Groups:
modified=Modified:

yes=Yes
no=No



