billing=Billing
property.isclient=Billable
 
isclient.help=<b>On</b> -> User belongs to the billing client <br /><b>Off</b> -> Root or Support user <i> <br />This field can only be edited by root user</i>
