add=Add

assigned-roles=Assigned Roles
property.copy-user=Add Roles from user
copy-user.help=Add the Roles that the selected user has

role-selector = Select Role

remove-all=remove all
nt100=The maximum number of roles supported per user is 100

roles-text= Roles grant permissions. The permissions of a particular user are the sum of the permissions granted by all the user's roles. <br/>Roles are defined in section <a href="/security/roles">Roles</a>