

password=Password

password-last-time =The Last time this password was changed was: <b>{0}</b>.<br /> For your protection, we require that the password has <b>8 characters or more</b>, must include <b>one or more digit</b> and <b>one or more capital letter</b>.

password-edition-disabled=Password edition for this account has been disabled by the Administrator.



changepassword=Enter new password

property.password1.placeholder=New Password
property.password2.placeholder=Retype New Password


property.password1=Password  
property.password2=Retype Password (Verification)
property.active = Active
property.minimunlength = Password must have at least 8 characters.

text-hidden=show/hide

property.musthavecapitalletter   =  Password does not have capital letters, it must have at least 1 capital letter.
property.musthavedigit			 =Password does not have digits, it must have at least 1 digit.

property.password1.help=At least 8 characters, and must include 1 or more numbers
property.password1.placeholder=type new password
property.password2.placeholder=retype new password

minimunlength=The password must have at least 8 characters.
password1.help=Minimum <b>8 characters</b>. Must have at least <b>1 capital letter</b> and at least <b>1 digit</b>
password2.help=Must match <b>"Enter New Password"</b> 
changepassword=Change Password
password1=Password
property.emailNotifications=Task Assigned  
PasswordsValidator=Password and Verification do not match

musthavecapitalletter    = Password does not have capital letters, it must have at least 1 capital letter.
musthavedigit			 = Password does not have digits, it must have at least 1 digit.




