
sqlgateway=SQL Gateway
external-resources=External Resources
relevance=Relevance

process-launcher=Process Launcher
sections=Sections
display-level=Display
subsection=Subsection
reverse=Reverse
information-model-home = Information Model Home
system=System
my-published=Published by me

only-admin=This panel is only for admin users

hashome = Mini Site
no-items=no items
password=Password

all-items=Total: <b>{0}</b>
draft-resources=Resources
home=Home
mywork=My Workspace
mydocuments=Mis Documentos
entity-mini-site=Mini Site

recently-modified-library=<b>{0}</b> most recents 
recently-modified=Modified recently - <b>{0}</b> of <b>{1}</b>
recent-activity=Recent Activity
my-queries=My Queries
dataset-member=DataSet Value

used-by=Used by
info=Info
modifiedby=Last modified by
st=St
alert-management=Alert Management
resource=Resource


new-file=New File
mynotifications=Notifications
mymessages= My Alerts
alert-settings=Alert Management

time-based-alerts=Time based Alerts
file-alerts=Workflow  Alerts
billboards=Billboards


impersonate = Sign In as this user
new=New
size=Size
title=Title
icon=Icon
open=Open
modified=Modified
id=id
labels=Labels
contents=Contents
predicate=IQL Predicate
alias=Alias
key=Alias
contentclass=Content Template


not-authorized-title=Not authorized

content-template=Content Template
task=Task
procedure=Business Process

vigent = Valid Version


audit.integration=Integration
audit.tree=Tree Resources
audit.email=Emails
audit.file=Find File
audit.activity=User Activity
audit.resources=Resources
audit.content=Content Audit


mytasks=My Tasks
library=Library

checkout = Create Working Copy
restore = Restore
archive=Archive
delete=Delete
unarchive= Send to Library


enabled=Enabled
archived=Archived

bc.launchergroups = Launcher Groups



menu=Menu
search-in=Search in {0}

mytasks=My Tasks
pending=Pending Tasks
monitor=Monitor
workload=Dashboard
taskbatchcreation=Bulk Upload
dashboard=Dashboard




lists=Lists
mylists=My Lists


clear-all=clear all

bc.account=My Account
bc.user-settings=User Settings
bc.my-notes=My Notes
bc.user-alerts=My Alerts


.property.description=Description

mydocuments=My Documents
mainmenu.domain.facets = Search Filters
objectstorage=Object Storage
thumbnail=Thumbnail



#--------------------------------------------------------------------------------------------------------------
#
# BreadCrumb
#
#

bc.dashboard=Dashboard
bc.service-monitor=Information

domain-recycle-bin=Domain Recycle Bin
bc.domain-recycle-bin=Domain Recycle Bin
bc.domains=Domains
bc.system-info=Service Metrics 
 
bc.service-management=Service Management
bc.data-management=Data Management
bc.scheduler=Scheduler
bc.file-server=File Server
bc.commands=Commands


bc.reports=Reports
bc.reports-home=Reports
bc.reportsubscription=Report Subscriptions

bc.api=API

bc.api.reports= Requests Report
bc.api.reports.soap= SOAP Report


# 1 --------------------------------
#
bc.myaccount = User Settings

# 2 --------------------------------
#
bc.settings = Settings
bc.generalsettings = General Settings
bc.libraries = Libraries
bc.forms = Forms
bc.emailtemplates=Email Templates
bc.facets = Search Filters
bc.sources = Sources
bc.file-server=File Server
bc.enoti = Workflow Alerts

# 3 --------------------------------
#
bc.security = Security
bc.audit = Audit
bc.users = Users
bc.groups = Groups
bc.rules =  Custom Data Rights



bc.tagmanagementtool= Tag Management tool
bc.actionrules = Time Based Alerts
bc.entityrules = Recurring Tasks
bc.retentionpolicy=Retention Policy


bc.roles = Roles
bc.billboard=Billboards

# 4 --------------------------------
#


bc.tasks-section=Tasks
bc.tasks=Tasks


bc.workspace = My Tasks
bc.mybox = My Resources
bc.pendingtasks = Pending Tasks
bc.monitor = Monitor
bc.dashboard=Dashboard
bc.bulkupload=Bulk Upload
mybox=My Resources 
bc.dataset.members=DataSet Values
bc.dataset.members.home=DataSet Values Home



# 5 --------------------------------
#
bc.content = Content
bc.contentsection=Content
bc.archive = Archive
archive-verb=Archive
bc.recyclebin = Recycle Bin

bc.contentbase = Libraries

# 6 --------------------------------
#
bc.datasetmembers = DataSet Values
datasetmembers = DataSet Values
datasetmember  = DataSet Value




bc.site=Portal

bc.site-home=Home
bc.site-editor=Info
bc.site-tags=Tags
bc.site-pages=Pages
bc.site-contents=Contents
bc.site-reports=Reports
bc.site-security=Security


classifier=Classifier
attribute=Attribute


# 7 --------------------------------
#
bc.informationmodel = Information Model
bc.templates = Content Templates
bc.datasets = DataSets
bc.attributes = Attributes
bc.classifiers = Classifiers
bc.contentclasses=Content Templates
bc.emailtemplates=Email Templates
bc.launchergroups=Procedure Groups
bc.resourcetags=Resource Tags

# 8 --------------------------------
bc.domain-section=Domain
bc.integration=Integration


# 9 --------------------------------
bc.labels = Labels
bc.worknotes = Billboard and Manual Alerts
bc.file-explorer=File Explorer

bc.home = Home
bc.systeminfo=System Info
bc.systemdm=Data Management
bc.datamanagement=Data Management
bc.exportcontents=Export Contents
bc.batchclassify=Classify
bc.membersbatchcreation=Create
bc.uploadandcreate=Bulk Upload  
bc.batchactions=Actions
bc.batchdatasetvaluesdelete=Batch delete
bc.sites=Portals
bc.portal=Portal

mainmenu.domain.facets = Search Filters
mainmenu.domain.actionrules = Time-dependent Actions

mainmenu.enotirules=Workflow Alerts



