

property.locale=Language
property.timezone=Timezone


save=Save
cancel=Cancel

property.name=Name 
name.help=Lowercase, only letters and numbers, no spaces. Do not include the <b>'@'</b>

domain=Domain

admin-user=Client admin user

property.organization=Organization
organization.help=The name of the Company

property.externalid=OneSite Id

property.rootemail=Root email
property.createmembers=Add DataSet Values

property.password1=Root Password
property.password2=Retype Root Password

password1.help=Minimum 8 characters, must have digits and capital letters
 

property.password1.placeholder=Password
property.password2.placeholder=Retype Password

property.domaintype=Domain Type
property.template=Template

property.noreplyemail=No Reply Email Address

minimunlength=Password must be 8 characters or more
check=Check if the name is available
musthavecapitalletter   = Password does not have capital letters, it must have at least 1 capital letter.
musthavedigit			 = Password does not have digits, it must have at least 1 digit.

property.test-result=
NameValidator.invalid_chars=Invalid characters (enter just letters and numbers, and no spaces)
NameValidator.domainexists=Domain already exists


PasswordsValidator=Password and Retype Password do not match


property.onesite = OneSite API
property.informationmodel = Type
property.admin-name = Firstname
property.admin-lastname = Lastname
property.admin-email = Email
property.admin-notify = Send email notification to Reset Password
admin-notify.help=Send email to Admin user with instructions to create a password and Sign In.

property.admin-username=Username

admin-username.help=Lowercase, only letters and numbers, no spaces. Do not include the <b>'@'</b>

