

alerts-email=Alerts and Email

property.name=Name
name.help=Domain name can not be modified

property.vanityurl=Vanity URL
vanityurl.help=Note that the system uses the following macro for vanity urls -> {0}  <br /> config dir properties -> server,  port,  vanity-server,  vanity-port

property.vanityUrl=Vanity URL
vanityUrl.help=Note that the system uses the following macro for vanity urls -> {0}  <br /> config dir properties -> server,  port,  vanity-server,  vanity-port 



property.oauth=Enable External Authentication (OAuth)
oauth.help=Google and other authentication providers

musthavecapitalletter    = Password does not have capital letters, it must have at least 1 capital letter.
musthavedigit			 = Password does not have digits, it must have at least 1 digit.
minimunlength			 = The password must have at least 8 characters.

service.enabled = Enabled
service.disabled = Disabled
organization=Organization
externalId=External Id
emailservice=Alerts and Emails
consoles=Consoles
description=Description
tipoftheday=Tip of the day
portal=Portal module
type=Type

other=Other
calendar=Calendar

globaltipoftheday.help=Applies to all users
property.globaltipoftheday=Tip of the Day

cabinet=Cabinet


property.defaultpassword=Default Password
defaultpassword.help=Default password for new Users (leave blank if you want to force users to enter a new Password). <br />If not blank this field must have \
a minimum of <b>8 characters</b>, must have at least <b>1 capital letter</b> and at least <b>1 digit</b>.

property.locale=Language

property.CabinetTemplate=Templates
property.CabinetKnowledgeBase=Knowledge Base
property.CabinetExternal=External
property.logo=Logo
logo.help=The logo should have 45px height.

property.portalLibrary=Portals

property.externalId=External Id
property.storageType=Default Storage
property.encryptFiles=Encrypt Files
property.integrationService=Integration Service

property.timezone=Time Zone
timezone.help=Required for task due date and other calculations.

api-storage=API and File Storage

externalid.helptext=Domain Id used by External applications.
portals=Portals