

property.starthour=Workable day - Start hour (0-23)
property.endhour=Workable day - End hour (0-23)

calendar=Calendar

property.logo=Corporate Logo
property.calendarSettings=Non Workable Days



calendarSettings.help=List of dates <b>month/day/year</b> or <b>month/day</b> separated by <b>;</b> If the year is omitted, the software assumes it is valid for all years. <br />These values are useb by the workflow engine to calculate <b>Due Dates</b>.<br />Example: <b>1/1; 12/24; 12/25; 11/23/2018</b> 
note=Task Due Dates are computed based on the <b>Domain Time Zone</b> (Settings tab) and excluding <b>weekends</b> and <b>non workable days</b>.



property.cutoffTime = Cutoff Time for Due Date
cutoffTime.help = This value is used to decide if the first workable day is when the event happened (if workable) or the next workable day.