
 
domain_name=Domain Name
domain_id=Domain ID

usage=Internal Storage Used
usageper=Percentage Used
grate=Internal Storage Growth Rate (est) 
quota=Storage Allocation 

remaining=Storage Remaining
remainingper=Percentage Remaining

contents=Files
resources=Resources
users=Users
created=Date Created
modified=Last Modified
readonly=This panel is read only.
type=Type


title=Storage

storage=Storage
api=API
activity=Dashboard