
signas=Sign as
gridexport.confirm=Please confirm the export of the Domain grid. We will send a .csv file by email

domains-recycle-bin=Domain Recycle Bin

recentconsoleactivity=checkin/day (mean)  

totalcontents=Total Contents
totalfiles=Total Resources
section=Domains 
console.label = Domain
console.name = Domains
yes=<span class="no">Yes</span>
no=<span class="yes">No</span>

modal.acl.title = ACL
modal.sendbyemail.title = Share

open=Open
name=Organization
new=New Domain

console.recycle-bin.label=Recycle Bin
contextmenu.restore=Restore

domain=Domain
organization=Organization
type=Type
status=Status
quota=Quota
harddisk=Hard Disk Usage (Stored)
gatewayharddisk=Hard Disk Usage (Gateway)
monthlyusage= Monthly Avg (est)
created=Created
modified=Modified Date
user=User
id=ID
username=User
percentage=Usage %
template=Domain Class
totalActiveSessions=Total Active sessions
usersWithActiveSessions=Users With Active sessions

archive=Set Status: <span class="archived">Archived</span>
enable=Set Status: <span class="enabled">Enabled</span>

resetrootpassword=Reset Root Password

type.enterprise=Set Type: <span class="enterprise">Enterprise</span> 
type.express=Set Type: <span class="express">Express</span>


template.enable=Set Class: <span class="template">Template</span>
template.disable=Set Class: <span class="standard">Standard</span>

is-template =<span class="template">Template</span>
is-standard = <span class="standard">Standard</span>

deleteconfirmation.message=Please confirm you want to delete this Domain

contextmenu.delete=Delete (Send to Recycle Bin)




