

cabinet=Cabinet

property.CabinetAll=All
property.CabinetStandard=Standard
property.CabinetTemplate=Templates
property.CabinetKnowledgeBase=Knowledge Base
property.CabinetExternal=External


property.CabinetTemplateName= Display name
property.CabinetKnowledgeBaseName= Display Name 
property.CabinetExternalName=  Display Name
property.CabinetStandardName=  Display Name
property.CabinetAllName=  Display Name



property.CabinetExternalReadOnly=Read Only
property.CabinetTemplateReadOnly=Read Only
property.CabinetKnowledgeBaseReadOnly=Read Only

