property.domain = Domain
property.location = Location
property.remote = Server
property.user = User
property.password = Password
property.templates = Templates
property.emailtemplates = EMail Templates
property.users = Users
property.files = Files
property.criteria = Criteria
property.datasets = DataSets
property.values = Values
property.rules = Rules
property.classifiers = Classifiers
property.attributes = Attributes
property.resourcetags = Resource Tags
property.launchergroups = Procedure Groups
property.structures = Structures
property.maxfiles = MaxFiles
property.roles = Roles
property.libraries = Libraries
property.groups = Groups
property.settings = Settings
property.facets = Facets
property.force = Force Update
