property.server = Server
property.domain = Domain
property.templates = Templates
property.users = Users
property.files = Files
property.criteria = Criteria
property.datasets = DataSets
property.values = Values
property.rules = Rules
property.classifiers = Classifiers
property.maxfiles = Max Files
property.groups = Groups
property.freeze = Freeze Files