no-alerts=<wicket:message key="add" />
reminder=Timed Alerts 
add=Add
no-alerts-msg=There are no Timed Alerts for this Content.


console-alerts=Para dar de baja, cambiar estado y ver la auditoría ir a consola <a href="/actionrules" class="btn-link">Acciones por Reglas temporizadas</a>