modal.sendbyemail.title=Share


tab.internalinfo=Internal Information
tab.main = Main
tab.history = Version History
tab.links = Links
tab.versioncontrol = Version Control
tab.audit = Audit


tab.supporting=Other Services
time-based-notifications=Alerts with deadline

