
not-pending=Task is not Pending

in-workspace=The Task is in {0}'s Workspace

share=Share
task-owner=Task - Owner
business-process=Business Process
pending=Pending


editor.resolution = {0} Letter
editor.task = Task
editor.actions = Actions
editor.resources = Resources
editor.history = History
editor.progressnotes = Task Progress Notes
editor.links = Links
editor.abstract = Notes
editor.private = Internal Information
editor.audit = Audit Trail
editor.roles = Workflow Profiles
editor.workflow=Workflow
editor.supporting = Support
editor.time-based-notifications=Time based Actions

tab.kbase = Knowledge Base
tab.related = Related Files

button.submit = Send
button.submiting = Sending...

editor.info=Info
info=Info
showtask=Show Task
hidetask=Hide Task

editor.customattributes=Custom Tags
info=Info

file-info=Process Info

past-due-title=Due Date
past-due=Task <b>overdue</b>, due date is <b>{0}</b>
due-today=Task is due <b>Today</b> 
due-tomorrow=Task is due <b>{0}</b>

show-workflow=Workflow panel (on/off) 