
pwdtitle=Password Protected
pwdtext=This is a password-protected page.<br/>Please enter the password provided by the sender of the link to access the content.

property.password.placeholder=Password
property.password=Password
apply=Apply

alert-text=Text
alert-title=Title