emaillog.console.name = SystemLog

emaillog.column.event = Event
emaillog.column.object = Object
emaillog.column.id = ID
emaillog.column.version = Version
emaillog.column.time = Date
emaillog.column.user = User
emaillog.column.description = Description

emaillog.column.result = Result
emaillog.column.action=Action
emaillog.column.from = From
emaillog.column.to = To
emaillog.column.subject = Subject
emaillog.column.text = Text
emaillog.column.attachments = Attachments
emaillog.column.domaincolumn=Domain

emaillog.contextmenu.audittrail = Audit Trail
emaillog.contextmenu.view = Open (Object version) 

emaillog.action.myfilters=My Filters
emaillog.action.myfilters.clear=clear filters

emaillog.advancedsearch.position=407
emaillog.notification.position=192
 