systemlog.console.name = SystemLog

systemlog.column.event = Event
systemlog.column.object = Object
systemlog.column.id = Class - id / version 
systemlog.column.version = Version
systemlog.column.time = Time
systemlog.column.user = User
systemlog.column.description = Description

systemlog.contextmenu.audittrail = Audit Trail
systemlog.contextmenu.view = Open (Object version) 

systemlog.action.myfilters=My Filters
systemlog.action.myfilters.clear=clear filters

systemlog.advancedsearch.position=407
systemlog.notification.position=217
 