property.externalId=External Id
property.text=Text in Request
property.requestText=Text in Request
property.responseText=Text in Response
property.json=Show Request
property.status=Status
property.range=Date time
property.domain=Domain

apply=Apply
