sort.alpha_asc=Sort A to Z
sort.alpha_desc=Sort Z to A 
sort.relevance_desc=Sort by Relevance


typeahead.showMore=Show more
typeahead.showingResults=<i>Showing <b>{0}</b> results. </i>
typeahead.showingAllResults=<i>Showing all <b>{0}</b> results.</i>