

false=No
true=Yes

menu.up = Up
menu.down = Down
menu.delete = Remove
menu.edit = Edit

add=Add

property.groups=Groups
property.group=Group


property.classifier=Classifier
property.standardGroups=Groups
property.general-rights=General Rights
