
	

false=No
true=Yes
	


menu.up = Up
menu.down = Down
menu.delete = Remove
menu.edit = Edit

add=Add

true.value = Yes
false.value = No

property.groups=Groups
property.group=Group

property.standardGroups=Groups
property.general-rights=General Rights