property.task = Task
property.title = Content



property.formeruser = Owned by

property.user = To User
user.help=
 

property.note = Note
assignation.form.submit=Save
assignation.form.cancel=Cancel
assignation.form.comment=Comment
assignation.form.title=Content
user.help=Admin users can assign without restrictions, all other users who have reassign rights can only select users allowed by the business process to execute the task.
 


