property.user = To User
property.note = Note
ok-message = The action was executed successfully. 
errors-message = The action was executed with errors.


button.submit = Send
button.submiting = Sending
actions = Action
tabtitle = Selected Tasks
cancel = Cancel
execute = Reassign
executing = Working
abort = Cancel
action = Action
reassign=Reassign

error.denied = You must have Reassign rights on the task/s being reassigned. Also note that Pending Tasks can not be Reassigned.
error.enabled = The User want to assign the Task/s is not authorized to perform that task.
 



 

