save-my-tasks=Save in My Tasks and Close
submit=Add Comment and Submit File
comments=Comments
workflow.endcondition.cancel= Cancel  
task-resolution=Task Resolution
task=Task
property.task=Task
property.note=Note
property.resolution=Resolution
property.priority=Priority
property.collaborator=Send to
property.template=Letter
property.reason = {0} Type

actions=Actions

edit=Edit
preview=Preview
after-termination=After Termination
pre-condition=Pre condition

LetterValidator = The resolution letter must be edited

workflow-rules = Workflow Rules

error.workflow = Workflow Error: {0}
