
taskinfo.action.take.working=working
taskinfo.action.take=Take

taskinfo.message.reassignedfrom=FFFFFFFFFFFFF
taskinfo.action.reassigntome==FFFFFFFFFFFFF
taskinfo.action.reassign=FFFFFFFFFFFFF


