 
process.procedure=Business Process
process.started=Started
dialog.cancel.title=Confirm
dialog.cancel.message=Do you want to delete the file <b>{1}</b> ?

dialog.cancel.button=Delete
button.cancel=Cancel

terminate-process=Delete
notitle=title