history = Process History
by = by
resolution = Res.
audit-trail = Audit Trail
process.history.message.reassignedTo = Reassigned to {0} by {1}
history=Process History

date=Date
task=Task
user=User

resolution=Task Resolution