modal.audit.title = Audit
modal.assignation.title = Re Assign Task
property.task = Task
button.reassign = Re Assign
task.error.nolonger = The task whas been taken by another user
task.error.required = <b>{0}</b> is Required
task.error.resources = At least one File is Required
task.error.validity = <b>{0}</b> is After <b>{1}</b>
task.resolution = Resolution
modal.audit.title = Audit {0}


process.procedure=Business Process
process.started=Started
dialog.cancel.title=Confirm
dialog.cancel.message=Do you want to delete the file <b>{1}</b> ?
dialog.cancel.button=Delete
button.cancel=Cancel
