notsametask-message = In order to execute the Action <span class="highlight">Procedure. Task</span> must be the same for all items. Please check the Selection in the table below. 
ok-message = The action was executed successfully. 
errors-message =The actions was executed with errors.
button.submit = Send
button.submiting = Sending
actions=Actions
tabtitle=Selected Tasks
back= < Back to My Tasks

grid.title=Title
grid.task=Process. Task
grid.class=Content Templates
