property.statement=IQL Expression
data-provider-info=This Block is automatically populated by a IQL query.

property.abstract=Abstract (Freemaker macro)
property.expander=Expander
property.sort=Sort Criteria



