UserValidator = El colaborador seleccionado no tiene una cuenta se usuario creada
collaborators = DataSet {0}
edit.label = Edit
help1 = The selectable users are those belonging to the groups {0}
help2 = The selectable users are those belonging to the group {0} 
personset.help = El recepetor de la tarea es seleccionable dentro de las personas incluidas en el dataset {0}
