
first-task=History is empty because this is the first Task in the Process.
task=Task
task-action=Action
start=Start
end=End
business-hours=Business hours
history = History
by = by
resolution = Res.
audit-trail = Audit Trail
process.history.message.reassignedTo = Reassigned to {0} by {1}
history=History

date=Date
task=Task
user=User

resolution=Task Resolution
due=Due date