notes = Task Progress Notes
edit.label = Edit
delete.label = Delete
publish.label = Publish
addresource.label = Add Resource
state.label = {0}
new-note= New Note

save.label=Save
save-close.label=Save and Close
close.label=Close

menuresource.delete = Delete
resourcecopied.message = The file {0} was copyed in {1}
menuresource.copyToTag = Copy to {0}


notes-msg=Las Notas de Tarea es donde los usuarios pueden interactuar durante la ejecución del proceso editorial. <br/>No es necesario ser el dueño de la Tarea para agregar una Nota de Tarea.\
Cuando se crea una Nota de Tarea el sistema envía notificaciones a los usuarios que tienen permiso de <b>Auditoría</b> sobre el Proceso de Trabajo (definido en los <a href="/security/roles">Roles</a> de cada usuario) o que <b>Siguen el Proceso</b>.