
due-date=Task Due Date

workflow=Workflow

task-reason=Reason
content-type=Type
id-info=Id / OId
type=Type
version=Version
file=File
status=Status
info=Info
thread = Thread
threads = Threads

property.task-started = Task Started
property.task-previous = Previous Task
property.task-by = by
property.comment = Comment from
property.duedate=Due Date

taskinfo = Task Info
workspace = Workspace
task = Task
reason = Reason

taskinfo.action.reassign = Reassign
taskinfo.action.reassigntome = Reassign to Me
taskinfo.action.reassigntome.working = Reassigning...
taskinfo.action.take = Take
taskinfo.action.take.working = Taking...

taskinfo.message.reassignedby = Reassigned by 
taskinfo.label.by = by

taskinfo.error.notask = Content not longer in Workspace
taskinfo.error.nolonger = The task was taken by another user

pending = Pending
priority = Priority

procedure.name=Business Process
task.process.started=Process Started
not-started=Not Started
contenttemplate=Content Template

previous-task-user=Previous Task user
