

mytasks=My Tasks
pending=Pending Tasks
monitor=Monitor
workload=Dashboard
dashboard=Dashboard

photo=Photo
lastname=User
status=Status


yes=<span class="yes">Yes</span>
no=<span class="no">No</span>

console.name=Domain Recycle Bin


totaltasks=Total Tasks
#-------------------------------
duedate-today=Due Today
duedate-plusone= {0}
duedate-plustwo= {0}
duedate-plusthree=  {0}
duedate-plusmore=  {0} or after
duedate-plusfourormore = {0} or later

#-------------------------------
duedate-past=Past Due
#-------------------------------
duedate-none=No Due Date
column.name = Name

console.label=Tasks



gridexport.confirm=Please confirm you want to export a grid of <b>{0}</b> items ?<br />You will receive an email with a .csv file that can be opened with Excel and other Spreadsheets.
toomanyitems=Unfortunately your selection has <b>{1}</b> items.<br/>Your Profile has a limit of <b>{0}</b> items. <br /> Please narrow down yor grid. 



edit=edit

searchplaceholder=Search in Recycle Bin

enabled=<span class="enabled">Enabled</span>
disabled=<span class="disabled">Disabled</span>

enabled=<span class="enabled">Enabled</span>
deleted=<span class="deleted">Deleted</span>
archived=<span class="archived">Archived</span>
draft=<span class="draft">Draft</span>

 

