editor.rule = Workflow Alert
editor.audit= Audit Trail
editor.state= Status
property.name = Name
property.state=Status
property.type = On Event
property.type.0 = Publish
property.type.1 = Pending

property.principal = Group or User