

yes=Yes
no=No

dataset.name = Workspace

enotirule.console.section=Workflow Alerts
enotirule.console.name=Workflow Alerts

enotirule.console.action.create = New
enotirule.console.action.delete = Delete

enotirule.console.contextmenu.open = Open
enotirule.console.contextmenu.delete = Delete

enotiruleconsole.column.name=Name
enotiruleconsole.column.id=Id
enotiruleconsole.column.condition=Condition (IQL)
enotiruleconsole.column.modified=Modified Date
enotiruleconsole.column.event=Event
enotiruleconsole.column.status=Status
enotiruleconsole.column.email=Email 
enotiruleconsole.column.alert=Alert


column.name=Name
column.id=ID
column.modified=Modified
column.condition=Condition (IQL) 
column.acl=ACL
column.event=Event

new-enoti=New System Email Notification
enotirule.console.contextmenu.open=Open
enotirule.console.contextmenu.audittrail=Audit Trail
enotiruleconsole.column.receiversColumn=Send to
enotiruleconsole.column.emailtemplate=Email Template


user=user
group=group



deleteconfirmation.message=Please confirm to delete Rule

description=<section><h3>Email Notifications</h3><p>Alert notifications can internal (on the bell at the top toolbar) or email. <br/>Email notifications  use Email Templates for the email. <br />Section <a href= \"/emailtemplates\" target=\"_blank\">Email Templates</a></p></section>

