payment.amount=Amount
payment.status=Status
payment.approvalDate=Approval Date
payment.processDate=Process Date
payment.platform=Platform
payment.conceptDetail=Description
payment.trxReference=Transaction Reference
payment.payer=Payer


payment.reprocess=Reprocess


PaymentCouldNotBeConfirmed=Payment could not be confirmed.
PaymentConfirmed=Payment have been confirmed.