paymentDetails=Payment Details



payment.amount=Amount
payment.status=Status
payment.approvalDate=Approval Date
payment.processDate=Process Date
payment.platform=Platform
payment.conceptDetail=Description
payment.trxReference=Transaction Reference
payment.payer=Payer