property.displayName = Name
property.key=Alias 
property.description=Description
property.readers = Readers
property.listOrder = List Order
property.suggester = Include in Suggesters

id.help=Used by the Search Platform