editor.facet = Filter
editor.audit = Audit Trail
editor.state = Status
editor.visibility = Published in
property.name = Name
rule.editor.cancel = Cancel
rule.editor.submit = Save
property.id = ID
property.state = State