

searchplaceholder=Search in Facets
security.label = Security
console.name = Search Filters

facets = Search Filters

console.label = Search Filters


facetsconsole.contextmenu.open=Open 
facetsconsole.contextmenu.audittrail=Audit Trail

facetsconsole.column.name = Name
facetsconsole.column.id = ID
facetsconsole.column.type = Type
facetsconsole.column.status= Status
facetsconsole.column.modified = Modified
facetsconsole.column.modifiedby = Modified by

facetsconsole.facetype.classifier = Classifier
facetsconsole.facetype.attribute = Attribute
facetsconsole.facetype.canonical = System

yes=Yes
no=No
