
publish=Publish

workspace = My Tasks
monitor = Monitor
contentbase = Library
archive = Archive
portals = Portals
pending = Pending Tasks
mydocs = My Documents

visibility.templates = Templates
visibility = Is Grid Column in Section


visibility.standard=Enterprise
visibility.templates=Templates
visibility.external=OneSite
visibility.kbase=Knowledge Base
visibility.all=All
visibility.pending=Pending