menu.setdefaults = Set as Attributes Defaults
menu.settingdefaults= Working
menu.cleardefaults = Clear Defaults
menu.clearingdefaults = Working
edit = Edit
tag = Tags
set-defaults = Defaults
close = Close
collapse=Collapse
NumericValidator.not-number = Numerical values only
