content.status = Library
content.version = Version 

content.status.recycled = Recycle Bin
content.status.versioned = Previous Version
content.status.enabled=Library
content.status.archived=Archive
content.status.templates=Templates
				
content.status.templates.enabled=Templates
content.status.contentbase.enabled=Library

headversion=Current
previousversion=
