
draftresources=Draft Resources
mywork=My Workspace
task=Task 
content=Content
settings=Settings
security=Security
logs=Logs
audit=Audit
reports=Reports
info=Info
datamanagement=Data Management
api=API
home=Home
sites=Portals
domains=Domains
general=General
integration=Integration

searcher=Search Portal
payments=Payments
support=Support
mini-site=Mini Site