<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<artifactId>kbee</artifactId>
		<groupId>com.novamens</groupId>
		<version>8.5-SNAPSHOT</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<name>${project.artifactId}</name>
	<artifactId>kbee-model-security</artifactId>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java-version>11</java-version>
	</properties>

	<scm>
		<connection>
			scm:git:ssh://alejo@git.hq.novamens.com/var/novamens/security.git
		</connection>
		<developerConnection>
			scm:git:ssh://alejo@git.hq.novamens.com/var/novamens/security.git
		</developerConnection>
	</scm>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<release>${java-version}</release>
					<fork>true</fork>
					<!--executable>C:\Program Files\Java\jdk-11.0.2\bin\javac</ executable -->
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>