

archive.name = Archive
action.create = New
action.sendtobase = Send to Library
action.delete = Delete

archive.contextmenu.movetolibray= Move to Library
archive.contextmenu.open = Open
archive.contextmenu.audit = Audit Trail
archive.contextmenu.sendtobase = Send to Library
archive.contextmenu.delete = Delete (to Recycle Bin)
archive.contextmenu.sendbyemail = Share


archive.action.myfilters.clear=clear filters
archive.action.myfilters=My Filters

export.confirm=Please confirm you want to export {0} files from the grid.
