
content-template=Content Template
task=Task
procedure=Business Process

vigent = Valid Version


audit.integration=Integration
audit.tree=Tree Resources
audit.email=Emails
audit.file=Find File
audit.activity=User Activity
audit.resources=Resources
audit.content=Content Audit


mytasks=My Tasks
library=Library

checkout = Create Working Copy
restore = Restore
archive=Archive
delete=Delete
unarchive= Send to Library


enabled=Enabled
archived=Archived

bc.launchergroups = Launcher Groups

menu=Menu
search-in=Search in {0}

mytasks=My Tasks
pending=Pending Tasks
monitor=Monitor
workload=Dashboard
taskbatchcreation=Bulk Upload
dashboard=Dashboard




lists=Lists
mylists=My Lists


clear-all=clear all

bc.account=AccountSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
bc.user-settings=User Settings
bc.my-notes=My Notes
bc.user-alerts=My AlertsAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa


.property.description=Description

mainmenu.domain.facets = Filters



#--------------------------------------------------------------------------------------------------------------
#
# BreadCrumb
#
#

bc.domains=Domains
bc.system-info=Service Metrics 
 
bc.service-management=Service Management
bc.data-management=Data Management
bc.scheduler=Scheduler
bc.file-server=File Server
bc.commands=Commands

bc.api=API

bc.api.reports= Requests Report
bc.api.reports.soap= SOAP Report


# 1 --------------------------------
#
bc.myaccount = User Settings

# 2 --------------------------------
#
bc.settings = Settings
bc.generalsettings = General Settings
bc.libraries = Libraries
bc.forms = Forms
bc.emailtemplates=Email Templates
bc.facets = Filters
bc.sources = Sources
bc.file-server=File Server
bc.enoti = Workflow Alerts

# 3 --------------------------------
#
bc.security = Security
bc.audit = Audit
bc.users = Users
bc.groups = Groups
bc.rules =  Custom Data Rights



bc.tagmanagementtool= Tag Management tool
bc.actionrules = Time Based Alerts
bc.retentionpolicy=Retention Policy


bc.roles = Roles
bc.billboard=Billboards

# 4 --------------------------------
#
bc.tasks-section=Tasks
bc.tasks=Tasks
bc.workspace = My Tasks
bc.pendingtasks = Pending Tasks
bc.monitor = Monitor
bc.dashboard=Dashboard
bc.bulkupload=Bulk Upload
bc.dataset.members=Dataset Values



# 5 --------------------------------
#
bc.content = Content
bc.contentsection=Content
bc.archive = Archive
bc.recyclebin = Recycle Bin

bc.contentbase = Libraries

# 6 --------------------------------
#
bc.datasetmembers = DataSet Values




bc.site=Portal

bc.site-home=Home
bc.site-editor=Info
bc.site-tags=Tags
bc.site-pages=Pages
bc.site-contents=Contents
bc.site-reports=Reports
bc.site-security=Security



# 7 --------------------------------
#
bc.informationmodel = Information Model
bc.templates = Content Templates
bc.datasets = DataSets
bc.attributes = Attributes
bc.classifiers = Classifiers
bc.contentclasses=Content Templates
bc.emailtemplates=Email Templates

# 8 --------------------------------
bc.domain-section=Domain
bc.domains=Domains


bc.integration=Integration


# 9 --------------------------------
bc.labels = Labels
bc.worknotes = Billboard and Manual Alerts
bc.file-explorer=File Explorer

bc.home = Home
bc.systeminfo=System Info
bc.systemdm=Data Management
bc.datamanagement=Data Management
bc.exportcontents=Export Contents
bc.batchclassify=Actions
bc.membersbatchcreation=Create
bc.uploadandcreate=Bulk Upload  
bc.batchactions=Actions
bc.sites=Portals
bc.portal=Portal

mainmenu.domain.facets = Search Filters
mainmenu.domain.actionrules = Time-dependent Actions

mainmenu.enotirules=Workflow Alerts



