contentconsole.titlelabel = Title
contentconsole.modifiedlabel = Modified Date
contentconsole.modifiedasclabel = Modified Date (asc)
contentconsole.modifieddesclabel = Modified Date (desc)
contentconsole.sendbyemail.message = {0} has sent you this content,\n\n{1}\n\n{2}.


contentclasscolumn=Content Template