
recyclebin.name=Recycle Bin

recyclebinconsole.action.delete=Delete 
recyclebinconsole.action.empty=Empty Bin


recyclebin.contextmenu.audit = Audit Trail
recyclebin.contextmenu.open = Open
recyclebin.contextmenu.restore= Restore
recyclebin.contextmenu.delete = Delete for ever
recyclebin.contextmenu.history = History

recyclebin.action.myfilters=My Filters
recyclebin.action.myfilters.clear=clear filters
recyclebin.advancedsearch.position=420
recyclebin.notification.position=211

recyclebin.window.title=Recycle Bin
recyclebin.window.text=Are you sure you want to empty the Recycle Bin?