execute=Execute
title=Parameters

property.domain=Domain

property.from=Modified From <span class="ago">(MM/dd/yyyy)</span>
property.to=Modfified To <span class="ago">(MM/dd/yyyy)</span>

property.domain=Domain
