menu.save = Save
hierarchy=Structure
switch-sides=Intercambiar paneles (izq/der)
action=Actions
action-short= 
error-msg = <p>The grid can not be rendered due to an application problem. <br /> Please contact support.</p><p>More info: <br />
