 
com.novamens.kbee.modules=kbee, solr, services, hibernate, content
 
jdbc.driverClassName=org.postgresql.Driver
#jdbc.driverClassName=oracle.jdbc.OracleDriver
#jdbc.url=jdbc:postgresql://localhost:5432/test
#jdbc.url=jdbc:oracle:thin:@localhost:1521:xe
#jdbc.username=kbee
jdbc.username=postgres
#jdbc.password=kbee
jdbc.password=sa
solr.dir=c:/eclipse-kepler/projects/novamens-content-web/web/index

# email server
#com.novamens.kbee.mail.server=smtp.gmail.com
#com.novamens.kbee.mail.port=465
#com.novamens.kbee.mail.username=erivero@novamens.com
#com.novamens.kbee.mail.password=egdr666
#com.novamens.kbee.mail.auth=true	
	
# email 
com.novamens.service.email.queue.dir = work/pqueue
com.novamens.service.email.numworkerthreads=10
com.novamens.service.emailsender.worker.mode=NOSEND
 
# Content File Server	
com.novamens.kbee.database.fileserver.root  = fsrepository/db
com.novamens.kbee.database.fileserver.cache = fsrepository/cache
#com.novamens.kbee.database.fileserver.bufferSize = 8192
com.novamens.kbee.database.fileserver.cacheenabled = yes	

com.novamens.kbee.database.fileserver.fscache.root = fscache
com.novamens.kbee.database.fileserver.fscache.size = 4000
com.novamens.kbee.database.fileserver.fscache.time-to-idle-secs = 86400 
 	
# Thumbnail Server	
com.novamens.content.thumbnailserver.root = e:/thumbnails/db

#OCR Server
# com.novamens.ocr.server.servermode = 
com.novamens.ocr.server.numWorkers 1
com.novamens.ocr.server.txtextractionratio = 10.0
com.novamens.ocr.server.txtextractionratio.txtextraction = yes
com.novamens.ocr.server.queue.workdir = work/server
com.novamens.ocr.server.queue.serverbufferqueue = 10
com.novamens.ocr.server.queue.serversleeplimit = 300
com.novamens.ocr.server.queue.debugdir = work/debug/ocr
com.novamens.ocr.server.lang = eng 

# OCR Client
com.novamens.ocr.client.queuelimit=30
com.novamens.ocr.client.sleeplimit=20

com.novamens.ocr.client.connection.user = postgres
com.novamens.ocr.client.connection.password = novamens
com.novamens.ocr.client.connection.url = jdbc:postgresql://localhost/test














 
 
 
