property.emailContact=Contact Email
property.title=Title
property.id=Id

property.URI=Relative URL
URI.help=Lowercase without spaces. Example: if you enter <b>lib</b> and the server is at <b>https://novamens.com</b> the site's url will be <b>https://rpdd.realpage.com/portal/lib</b>   

property.subtitle=Subtitle
property.description=Description


UrlValidator.not-available=URL not available
UrlValidator.characters=Invalid characters

property.advancedSearchForm=Advanced Search Form
property.searchForm=Search Form
property.public=Access

public=Public
private=Private



