automatic=Automatic 
timer=Timer 
manual=Manual (Pending) 
manual-lastuser=Manual (Pending) or Last User 
userautomaic=Round Robin 
userautomaic-round-robin=Round Robin 
userautomaic-lastuser=Round Robin or Last User
userautomaic-role=Round Robin and Role or Round Robin 
role=Workflow Role (W-Role) 
collaborator=Collaborator (User Selector) 