console.toolbar.expanded-mode = Content
console.toolbar.condensed-mode = List
 
onsole.toolbar.order-action = Sort
console.toolbar.content-layout = Content
console.toolbar.view-mode-action=View

 
 navigation.filtersapplied = Filters