editor.cabinet = Library
editor.audit = Audit Trail
editor.state = Status
property.name = Name
rule.editor.cancel = Cancel
rule.editor.submit = Save
property.id = ID
property.state = State
e
editor.roles=Used in Roles 
