

portal=Portal
about=About
security.label = Security
console.name = Libraries

libraries = Libraries
library = Library

console.label =Libraries




# Context Menu (actions applied to the selected content)
librariesconsole.contextmenu.open=Open 
librariesconsole.contextmenu.audittrail=Audit Trail

librariesconsole.column.name = Name
librariesconsole.column.id = ID
librariesconsole.column.key = Alias
librariesconsole.column.status= Status
librariesconsole.column.modified = Modified
librariesconsole.column.modifiedby = Modified by
librariesconsole.column.criteria = Criteria
librariesconsole.column.order = Order
librariesconsole.column.total_contents = Contents
modified = Modified
created = Created
status=Status
totalcontents=Total Contents


yes=Yes
no=No

deleteconfirmation.message = Please confirm to delete Library <b>{0}</b> ?
error.constraint = Integrity Constraint. The library can't be removed 
contextmenu.delete = Delete

enabled=<span class="enabled">Enabled</span>
indexing=<span class="enabled">Indexing</span>
deleted=<span class="deleted">Deleted</span>
archived=<span class="archived">Archived</span>
draft=<span class="draft">Draft</span>

searchplaceholder=Search in Libraries

user-email-disabled-grid-export=You have disabled email notifications. <br />We will not be able to send you the export. <br />Please enable them back in <a class=\"btn-link\" href=\"/myaccount\" target="_blank">User Settings</a>, tab Account.
