

open-portal=Open Library's Portal
how-to-criteria=How to write a Criteria
searchplaceholder=Search in Libraries
'property.state=Status

property.key=Alias 
property.name = Name
property.displayName=Name

property.description=Description
description.help=This description is displayed when the user clicks on the library's grid (i) icon and on the Homepage of the Library's portal. 
property.readers = Readers
property.listOrder = List Order
property.page = Page

property.statement = Criteria (IQL)
statement.help = Click on the <b>(i)</b> icon to list available Predicates

statement.helptext =  <div class="panel col-lg-12"><p class="text col-lg-12">Criteria can be expressed as logical expressions using predicates.<br/> \
Logical operators are <b>AND</b>, <b>OR</b> and <b>-</b> (which represents NOT). </p>	<p> Available predicates are:	 \
<ul class="col-lg-12" style="margin-bottom:20px; margin-top:0px;"> \
<li class="col-lg-12"><span class="predicate">isTemplate</span><span class="ago"> ( true | false )</span></li> \
<li class="col-lg-12"><span class="predicate">isExternal</span><span class="ago"> ( true | false )</span></li> \
<li class="col-lg-12"><span class="predicate">source</span><span class="ago"> ( source_name | source_id )<span></li> \
</ul> </p> \
<p class="col-lg-12 text"> Examples:\
<ul class="col-lg-12" style="margin-bottom:20px; margin-top:0px;"> \
<li class="col-lg-12"><span class="predicate">source<span class="ago"> ( sap ) </span></li>\
<li class="col-lg-12"><span class="predicate">source<span class="ago"> ( leasestar ) </span><span class="logical-operator"> or </span><span class="predicate">source</span><span class="ago"> ( onesite ) </span> \
<li class="col-lg-12"><span class="predicate">isTemplate<span class="ago"> ( false ) </span><span class="logical-operator"> and </span><span class="predicate">isExternal</span><span class="ago"> ( false ) </span> \
</ul> \
</p> </div> 

iscanonical = Canonical Library

property.readOnly = Read Only
z|
IqlValidator.invalid-domain = Invalid Domain id
invalid-domain = Invalid Domain id
IqlValidator = syntax error