

console-description = Email Templates
 

contextmenu.open=Open
contextmenu.audittrail=Audit
contextmenu.delete=Delete

deleteconfirmation.message=Please confirm  

console.name=Email Templates

key=Alias 
name=Title
modified=Modified

status=Satus
created=Created
order=Order
id=Id

error.constraint=Error Constraint
lang=Language

from=From
subject=Subject
text=Text
language=Language
