
parameters.help=Enter parameters as <b>key</b> = <b>value</b> pairs, 1 per line <br /> For <b>Person</b>, <b>Content</b> or <b>Rule</b> use their id. Example: content=23222334, rule=334345, person=4545544 <br /> \
for <b>Domain</b> use their name. Example: domain=windsor <br /> \
You can  leave this field empty and the form will use default parameters (Content from the users' Workspace, Rule from user's Rules, other parameters will be taken from the context or just invented for the test). 


 

test=Test


property.title=Title
property.key=Alias 
property.id=Id
property.language=Language
property.description=Description
property.parameters=Parameters

property.subject=Subject
property.stringTemplate=Text