property.key=Alias 
property.id=Id
property.language=Language
property.description=Description
property.title=Title
property.default=Default value

property.subject=Subject
subject.help=Click the <b>( i )</b> on the right to list available macros

property.stringTemplate=Text
stringTemplate.help=Click the <b>( i )</b> on the right to list available macros


#template-example_1=${from-displayname} has assigned the following task:\nTask: ${task-name}\nFile: ${title}\nPlease go to ${mytasks-link}\nto retrieve additional information about this file.\nFile Data:\n${file-attribute.property}\n${file-attribute.file type}\n${file-attribute.effective date}\n${file-attribute.status}\nComment: ${comment}
#template-example_2=${person-display-name} has published: ${file-title}\n ${file-attributes} \nView the file here: ${file-library-url}\n or go to Library at ${library-url} to retrieve additional information.

la-en=Open English version
la-es=Open Spanish version


macros-help= Every template can use the macros of some or all of these areas: \
<b>General</b>, <b>Content</b>, <b>Workflow</b>, <b>Email Rule</b> <br /> \
Macros by area <br /> <b>General</b>  <br /> {0} <br/> \
<b>Content</b>  <br /> {1} <b>Workflow</b> <br /> {2} <br/> \ <b>Rule</b> <br /> {3} <br /> \ <b>Context</b> <br /> {4}


 
