search-in-archive=Search in Archive

console.label = Content

console.name = Archive

delete=Delete

archive.batch.sendtobase =  Send to Library
archive.batch.delete =  Delete
archive.batch.class = Content
archive.batch.return=< Back to Archive

archive.contextmenu.movetolibray= Move to Libray
archive.contextmenu.open = Open
archive.contextmenu.audittrail = Audit Trail
archive.contextmenu.download = Download
archive.contextmenu.sendtobase = Send to Library
archive.contextmenu.sendtobase.working = Sending...
archive.contextmenu.delete = Delete 
archive.contextmenu.delete.working = Deleting... 

archive.tools.sendtobase = Send to Library

export.confirm=Please confirm you want to export the result set.

toomanyitems=Unfortunately your selection has <b>{1}</b> items.<br/>Your Profile has a limit of <b>{0}</b> items. <br /> Please narrow down yor grid. 

