contextmenu.open=Open
contextmenu.download=Download


sha256column=SHA256
console.section = Audit
console.label =Resources
console.name = Resources
console.displayname=Resources


systemlog = Activity
emaillog = Email
xplorer = File Server

audit.title=Audit {0}

titlecolumn = Title
datecolumn = Modified Date
taskcolumn = Task
idcolumn = ID
pathcolumn=URL
sizecolumn=Size
crc32column=CRC32
usercolumn=User
iconcolumn=Icon
domaincolumn=Domain
urlcolumn=URL
contentcolumn = Content
taskprioritycolumn=Priority
workspacecolumn=Workspace

audit.title=Audit {0}
modal.sendbyemail.title=Share


bucketnamecolumn=Bucket
objectnamecolumn=ObjectName

kbfstypecolumn=KBFS Type
namecolumn=Name 

yes=<span class="yes">Yes</span>
no=<span class="no">No</span> 
