favorites=Favorites

contentconsole.titlelabel = Title
contentconsole.modifiedlabel = Modified
contentconsole.modifiedasclabel = Modified (asc)
contentconsole.modifieddesclabel = Modified (desc)
contentconsole.sendbyemail.message = {0} has sent you this content,\n\n{1}\n\n{2}.

titlecolumn = Title
datecolumn = Modified Date
taskcolumn = Task
idcolumn = ID
taskprioritycolumn=Priority
workspacecolumn=Workspace
iconcolumn=Thumbnail
lockedcolumn=
contentclasscolumn=Template
modifieduser=Modified by

duedatecolumn=Due Date

processstartcolumn=Process Start

taskstartcolumn=Task Started


audit.title=Audit {0}
modal.sendbyemail.title=Share

workspace = My Tasks
pending = Pending Tasks
monitor = Monitor


content=Libraries
templates=Templates
archive=Archive
recycle=Recycle Bin

gridexport.confirm=Please confirm you want to export a grid of <b>{0}</b> items ?<br />You will receive an email with the export attached.


user-email-disabled=You have disabled email notifications. <br />We will not be able to send you the link to download the export. <br />Please enable them back in <a class=\"btn-link\" href=\"/myaccount\" target="_blank">User Settings</a>, tab Account.
user-email-disabled-grid-export=You have disabled email notifications. <br />We will not be able to send you the export. <br />Please enable them back in <a class=\"btn-link\" href=\"/myaccount\" target="_blank">User Settings</a>, tab Account.

