console.label = Content

console.name = Templates

contentbase.action.myfilters = My Filters
contentbase.action.myfilters.clear =clear list

contentbase.action.tools = Tools
contentbase.action.tools.checkout = Create Working Copy
contentbase.action.tools.archive = Archive
contentbase.action.tools.exportlist = Export list
contentbase.action.tools.export=Export

contentbase.batch.delete =Delete  
contentbase.batch.archive = Archive 
contentbase.batch.checkout = Create Working Copy
contentbase.batch.class = Content

delete=Delete

contentbase.name = Library

contentbase.contextmenu.audit=Audit 
contentbase.contextmenu.inportal=Open in Portal
contentbase.contextmenu.gallery=Image Viewer
contentbase.contextmenu.open = Open
contentbase.contextmenu.openandedit=Create Working Copy and Edit
contentbase.contextmenu.audittrail = Audit Trail
contentbase.contextmenu.start = Start
contentbase.contextmenu.checkout = Create Working Copy
contentbase.contextmenu.preview = Preview
contentbase.contextmenu.history = History
contentbase.contextmenu.gallery = Gallery View
contentbase.contextmenu.clone = Clone
contentbase.contextmenu.delete = Delete  
contentbase.contextmenu.sendbyemail = Share
contentbase.contextmenu.sendtoarchive = Send to Archive
contentbase.contextmenu.sendtoarchive.working = Sending...
contentbase.contextmenu.acl = Access Rights
contentbase.contextmenu.openinportal = Open in Portal

contentbase.contextmenu.delete.working = Working

modal.acl.title = ACL
modal.sendbyemail.title = Share

tools.export = Export
tools.checkout = Create Working Copy
tools.archive = Archive
tools.delete = Delete