

console-description=Authorized users can view <b>My Tasks</b> of other users, and reassign tasks.

toomanyitems=Unfortunately your selection has <b>{1}</b> items.<br/>Your Profile has a limit of <b>{0}</b> items. <br /> Please narrow down yor grid. 
export.confirm=Please confirm you want to generate a <b>zip</b> file with <b>{0}</b> files from the grid.

console.label = Tasks
console.name = Monitor
monitor.name =Monitor
mytasks=My Tasks
pending=Pending Tasks
monitor=Monitor
workload=Dashboard

export.confirm=Please confirm you want to export a grid of <b>{0}</b> items ?<br />You will receive an email with a .csv file that can be opened with Excel and other Spreadsheets.
gridexport.confirm=Please confirm you want to export a grid of <b>{0}</b> items ?<br />You will receive an email with the export attached.

monitor.contextmenu.sendbyemail=Share

monitor.contextmenu.audittrail = Audit Trail
monitor.contextmenu.open = Open
monitor.contextmenu.download=Download
monitor.contextmenu.take = Take
monitor.contextmenu.take.working = Reassign...
monitor.contextmenu.forcedactions = Force Termination
monitor.contextmenu.take-assignation = Take and Reassign
monitor.contextmenu.assignation-tome = Reassign to Me
monitor.contextmenu.assignation = Reassign
monitor.contextmenu.acl = Access Rights
monitor.contextmenu.fix = Fix
monitor.contextmenu.subscribe = Subscribe
monitor.contextmenu.unsubscribe = Unsubscribe
monitor.contextmenu.restartprevious = Retract (Restart {0})
monitor.error.alreadyinyourworkspace=The File is already in your Workspace

monitor.assigned-column-name = Taken/Pending Since

monitor.assigned = Taken/Pending Since (desc)
#Taken/Pending Since

monitor.assigned-asc = Taken/Pending Since (asc)
# Taken/Pending Since (desc)

monitor.assignedBy = From
monitor.workspace = Workspace
monitor.task = Task
monitor.priority = Priority

reassign=Reassign

monitor.reassignedfrom = Reassigned from 
monitor.by = by

take=Take
monitor.batch.take = Take
monitor.batch.reassign = Reassign  
monitor.batch.class = Tasks
monitor.batch.return = < Back

monitor.action.myfilters  = My Filters
monitor.action.myfilters.clear = clear filters

monitor.error.nolonger = Content not longer in Workspace

toomanyitems=Unfortunately your selection has <b>{1}</b> items.<br/>Your Profile has a limit of <b>{0}</b> items. <br /> Please narrow down yor grid. 

unreadcolumn=