console.name = Pending Tasks
console.label = Tasks

pendingtasks.batch.take=Take
pendingtasks.batch.class=Tasks

pendingtasks.name = Pending Tasks
pendingtasks.task = Task
pendingtasks.time = Pending from
pendingtasks.assignedBy = From
pendingtasks.priority = Priority

pendingtasks.contextmenu.open = Open
pendingtasks.contextmenu.take = Take
pendingtasks.contextmenu.take-and-reassign=Take and Reassign
pendingtasks.contextmenu.audit = Audit Trail
pendingtasks.contextmenu.take.working  = Taking...

pendingtasks.error.nolonger = The task was taken by another user

mytasks=My Tasks
pending=Pending Tasks
monitor=Monitor
workload=Dashboard
