console.label = Content

console.name = Recycle Bin

recyclebin.batch.delete = Delete
recyclebin.batch.restore = Restore
recyclebin.batch.class = Content
recyclebin.batch.title = Title
recyclebin.batch.source = Source
recyclebin.batch.contentclass = Content Template

recyclebin.source.workspace = My Tasks
recyclebin.source.content = Library / Archive
recyclebin.source.template = Templates

recyclebin.column.title = Title
recyclebin.column.source = Deleted From
deletedbycolumn=Deleted By

recyclebin.contextmenu.open = Open
recyclebin.contextmenu.restore.workspace = Restore to My Tasks
recyclebin.contextmenu.restore.content = Restore to Library
recyclebin.contextmenu.restore.template = Restore to Templates
recyclebin.contextmenu.restore.working = Restoring
recyclebin.contextmenu.audittrail = Audit Trail
recyclebin.contextmenu.download=Download
recyclebin.contextmenu.delete = Delete
recyclebin.contextmenu.delete.working = Deleting

recyclebin.deleteconfirmation.message = Delete file <b>{0}</b> ?
recyclebin.emptyconfirmation.message = Please confirm that you want to delete all files in the Recycle Bin ?

recyclebin.empty.title = Empty Recycle Bin 
recyclebin.empty.confirmation = Are you sure to permanently delete the documents in the recycle bin?
recyclebin.empty.execution = Emptying the Recycle Bin
recyclebin.empty.close = Close 
recyclebin.empty.execute = Start 
recyclebin.empty.cancel = Cancel 
recyclebin.empty.ok = Ok 

recyclebin.error.newversion = The File can not be restored because there are newer versions in the Library
recyclebin.error.locked = The File can not be restored because head version is locked
recyclebin.error.state = Content is not deleted

recyclebin.tools.restore = Restore
recyclebin.tools.empty = Empty Bin