console.label = Libraries 
console.name = Libraries
section=Content
library=Library


subtitle=Subtitle
criteria=Criteria
description=Description
settings-title=Library Settings 
open-settings=You can edit the text of this panel on this Library's Settings (field Description): 



toomanyitems=Unfortunately your selection has <b>{1}</b> items.<br/>Your Profile has a limit of <b>{0}</b> items. <br /> Please narrow down yor grid. 

export.confirm=Please confirm you want to generate a <b>zip</b> file with <b>{0}</b> files from the grid.

gridTagTool.tooManyItems=To many items to open in tag tool. <br /> Items: <b>{1}</b> <br /> Limit: <b>{0}</b> items
information=Information


locked=File is Locked
not-authorized=Not Authorized
readonly = Is Readonly

contentbase.action.tools = Tools
contentbase.action.tools.checkout = Create Working Copy
contentbase.action.tools.archive = Archive
contentbase.action.tools.exportlist = Export list
contentbase.action.tools.export=Export


contentbase.batch.delete =  Delete  
contentbase.batch.archive =  Archive 
contentbase.batch.checkout =  Create Working Copy
contentbase.batch.class = Content
delete=Delete
archive=Archive
checkout=Create Working Copy

contentbase.name = Library

contentbase.contextmenu.audit=Audit 
contentbase.contextmenu.inportal=Open in Portal
contentbase.contextmenu.gallery=Image Viewer
contentbase.contextmenu.open = Open
contentbase.contextmenu.openandedit=Create Working Copy and Edit
contentbase.contextmenu.audittrail = Audit Trail
contentbase.contextmenu.start = Start
contentbase.contextmenu.checkout = Create Working Copy
contentbase.contextmenu.preview = Preview
contentbase.contextmenu.history = History
contentbase.contextmenu.gallery = Gallery View
contentbase.contextmenu.clone = Clone
contentbase.contextmenu.delete = Delete  
contentbase.contextmenu.sendbyemail = Share
contentbase.contextmenu.share = Share
contentbase.contextmenu.download = Download
contentbase.contextmenu.sendtoarchive = Send to Archive
contentbase.contextmenu.sendtoarchive.working = Sending...
monitor.contextmenu.subscribe = Subscribe
contentbase.contextmenu.acl = Access Rights
contentbase.contextmenu.openinportal = Open in Portal

contentbase.contextmenu.delete.working = Working

modal.acl.title = ACL
modal.sendbyemail.title = Share

tools.checkout = Create Working Copy
tools.archive = Archive
tools.delete = Delete
tools.export= Export
tools.openInTagTool=Open Tag tool  

tools.grid.export.files=Export Files

favorites=Favorites

contentconsole.titlelabel = Title
contentconsole.modifiedlabel = Modified
contentconsole.modifiedasclabel = Modified (asc)
contentconsole.modifieddesclabel = Modified (desc)
contentconsole.sendbyemail.message = {0} has sent you this content,\n\n{1}\n\n{2}.

titlecolumn = Title
datecolumn = Modified Date
taskcolumn = Task
idcolumn = ID
taskprioritycolumn=Priority
workspacecolumn=Workspace
iconcolumn=Thumbnail
lockedcolumn=
contentclasscolumn=Template
modifieduser=Modified by

duedatecolumn=Due Date

processstartcolumn=Process Start

taskstartcolumn=Task Started


audit.title=Audit {0}
modal.sendbyemail.title=Share

workspace = My Tasks
pending = Pending Tasks
monitor = Monitor


content=Libraries
templates=Templates
archive=Archive
recycle=Recycle Bin

gridexport.confirm=Please confirm you want to export a grid of <b>{0}</b> items ?<br />You will receive an email with the export attached.


user-email-disabled=You have disabled email notifications. <br />We will not be able to send you the link to download the export. <br />Please enable them back in <a class=\"btn-link\" href=\"/myaccount\" target="_blank">User Settings</a>, tab Account.
user-email-disabled-grid-export=You have disabled email notifications. <br />We will not be able to send you the export. <br />Please enable them back in <a class=\"btn-link\" href=\"/myaccount\" target="_blank">User Settings</a>, tab Account.


