
labels=Lists


console-description=My Tasks is a custom inbox where each user creates new content, receives and executes tasks consisting of editing, reviewing, approvals, etc.
 


toomanyitems=Unfortunately your selection has <b>{1}</b> items.<br/>Your Profile has a limi
t of <b>{0}</b> items. <br /> Please narrow down yor grid. 


export.confirm=Please confirm you want to generate a <b>zip</b> file with <b>{0}</b> files from the grid.


console.label = Tasks
console.name = My Tasks
console.displayname = My Tasks




mytasks=My Tasks
pending=Pending Tasks
monitor=Monitor
workload=Dashboard



workspace.action.create = New

workspace.labels=Labels
workspace.actions=Task Execution 
workspace.batch.classify = Edit

batch-create=Bulk Upload
delete=Delete



worknotes.markall=Mark as Read

workspace.batch.delete = Delete
workspace.batch.class = Tasks
workspace.batch.delete.return=< Back to My Tasks
workspace.batch.deleteanchor=
toomanyitems=Unfortunately your selection has <b>{1}</b> items.<br/>Your Profile has a limit of <b>{0}</b> items. <br /> Please narrow down yor grid. 
 

# Context Menu (actions applied to the selected content)
workspace.contextmenu.open = Open
workspace.contextmenu.openandedit = Open and Edit
workspace.contextmenu.audittrail = Audit Trail
workspace.contextmenu.assignation = Assign
workspace.contextmenu.clone = Clone
workspace.contextmenu.preview = Preview
workspace.contextmenu.gallery = Gallery View
workspace.contextmenu.sendtobase = Send to Library (check in)
workspace.contextmenu.sendtoformslibrary= Send to Templates Library (check in)
workspace.contextmenu.sendtoarchive = Send to Archive
workspace.contextmenu.delete = Delete/Drop Working Copy
workspace.contextmenu.cancel = Delete 
workspace.contextmenu.share = Share
workspace.contextmenu.applylabel = Apply label 
workspace.contextmenu.adminlabels= Admin My Labels
workspace.contextmenu.download=Download
workspace.contextmenu.labels = Labels
workspace.contextmenu.priority=Priority

workspace.contextmenu.notauthorized=Not Authorized

workspace.unreadtask=New Task (unread)


workspace.column.unread = 
workspace.column.title = Title
workspace.column.icon = Thumbnail
workspace.column.task = Task
workspace.column.priority = Priority
workspace.column.date = Modified Date
workspace.column.id = ID
workspace.column.contentclass=Content Template

workspace.order.assigned = Taken (desc)
workspace.odrer.assigned-asc = Taken (asc)
workspace.order.assignedBy = From
workspace.order.assigned-asc=Assigned (asc)

workspace.error.nolonger = Content not longer in Workspace
workspace.cancelconfirmation.message = Do you want to delete the file <b>{0}</b> ?

modal.sendbyemail.title=Share