
condition-label = Condition
send-test-email = Send me test email
events = Events
receivers = Receivers
rule-type = Type
conndition-label = Condition

editor.rule = Rule
editor.audit= Audit Trail

property.name = Name

property.key = Alias
key.help=Used by Email Templates

property.type=Type
type.help=<b>Publish</b> -> when a File is published in the Library. <b>Pending</b> -> when a File is sent to Pending. 

property.type.0 = Publish
property.type.1 = Pending

property.publishEvent = Publish
property.progressNoteEvent = Progress Note
property.taskStartEvent = Task Start

property.requireConfirm = ACK Reception 


events.help = Events list that trigger the rule

property.receivers = Send to (User or Group) 
receivers.help = Users must have <b>Read</b> permission on the Content to get the Email Notification. 
property.roleReceivers = Send to (Role)
  
property.roles = Roles 

property.isemail = Email
isemail.help=Send email notification

isemail.text=<b>Publish</b> Email Template -> {0}    |   <b>Pending</b> Email Template -> {1} 

property.isalert = Alert
isalert.help=Internal Alert (My Alerts)

condition.help=We will send an Alert when the Event below occurs on a File that meets this condition.

alert-msg =Alerts will be sent to <b> {0} </b>.<br/> You can change your email address in <a class="btn-link" href="/myaccount?tab=info" target="_blank">User Settings</a>.</span></div>