
eform-title=Form {0}
label=Label
type=Type
model=Model
components=Components
property.titleVisible = Title visible
property.id = Id
property.name = Name
property.displayName = Display Name
property.cssClass = Css
property.type = Type
property.classifier = Classifier
property.attribute = Attribute
property.tag = Tag
property.text = Text
property.required = Required
property.relation = Relation
property.readOnly = Read Only
property.cssClass = Css
property.label = Label
property.sublabel = SubLabel
property.script = Script
property.message = Message

property.toolbar = Toolbar

property.formAccessLevel = Form Access Level
#property.form Usage = Form Usage

property.useInline = Use Inlinee
property.fileContainer = Is File Container
property.condition = Condition
property.accessibility = Accessibility
property.calculation = Calculation
property.onUpdate = On Update
property.valueTemplate = Value Template
property.infoTemplate = Info Template
property.iql = Iql
property.editor = Editor
calculation.help = A script to set the field value
new-component = New 


property.targetTag = Target Tag
property.doneTag = Done Tag
 
template-structure=The components of the form are a subset of the <a href="{1}" class="btn-link">Structure of {0}</a>


autocomplete=AutoComplete
autocomplete-panel=AutoComplete (Panel)
boolean=Boolean
check=Check
combo=Combo
date=Date
html=HTML
html-struct= HTML Struct
list=List
number=Number
relation=Relation
resource=Resource
resource-system=Resource System
resource-systemv2 = Resource System (v2)
resource-systemv3 = Resource System (v3)
resource-distribution = Resource Distribution
resources=Resources
external-resources = External Resources
row=Row
section=Section
static-text=Static Text
string=String
string-list=String List
table=Table
text=Text
title=Title
timestamp=Timestamp
