system.status.title= Server Information
system.status.section.application=Application
system.status.section.platform=SolR
system.status.section.server =Server

meta.title = Server Information
meta.keywords = Knowledge Sharing, Question, Answers 
