DROP SEQUENCE hibernate_sequence 
DROP SEQUENCE domainid_sequence
DROP SEQUENCE lock_sequence
DROP SEQUENCE log_sequence
DROP SEQUENCE query_sequence
DROP SEQUENCE objectid_sequence
DROP SEQUENCE resourceid_sequence
DROP SEQUENCE contentid_sequence
DROP SEQUENCE entityid_sequence
DROP SEQUENCE classificationid_sequence
DROP SEQUENCE security_sequence
DROP SEQUENCE scheduler_sequence
DROP SEQUENCE qaid_sequence
DROP SEQUENCE propertyid_sequence
DROP SEQUENCE workflow_sequence
DROP SEQUENCE portalid_sequence
	


DROP TABLE Domain CASCADE CONSTRAINTS;
DROP TABLE Users CASCADE CONSTRAINTS;
DROP TABLE Entity CASCADE CONSTRAINTS;
DROP TABLE Person  CASCADE CONSTRAINTS;
DROP TABLE Profile  CASCADE CONSTRAINTS;
DROP TABLE Principal CASCADE CONSTRAINTS;
DROP TABLE KGroup CASCADE CONSTRAINTS;
DROP TABLE KGroupMember CASCADE CONSTRAINTS;
DROP TABLE Authorities CASCADE CONSTRAINTS;
DROP TABLE Acl CASCADE CONSTRAINTS;
DROP TABLE AclEntry CASCADE CONSTRAINTS;
DROP TABLE SecurityRule CASCADE CONSTRAINTS;
DROP TABLE UserProfile CASCADE CONSTRAINTS;
DROP TABLE KLock CASCADE CONSTRAINTS;
DROP TABLE KB_ENotiRule CASCADE CONSTRAINTS;
DROP TABLE KB_ENotiRule_Principal CASCADE CONSTRAINTS;
DROP TABLE LogEvent CASCADE CONSTRAINTS;
DROP TABLE SavedQuery CASCADE CONSTRAINTS; 
DROP TABLE Scheduler CASCADE CONSTRAINTS;
DROP TABLE Organization CASCADE CONSTRAINTS;
DROP TABLE ResourceGroup  CASCADE CONSTRAINTS;
DROP TABLE KResource CASCADE CONSTRAINTS;
DROP TABLE KFile CASCADE CONSTRAINTS;
DROP TABLE ExternalResource CASCADE CONSTRAINTS;
DROP TABLE HTMLText CASCADE CONSTRAINTS;
DROP TABLE ResourceFile CASCADE CONSTRAINTS;
DROP TABLE ContentClass CASCADE CONSTRAINTS;
DROP TABLE ContentTemplate CASCADE CONSTRAINTS;
DROP TABLE ContentTemplateResourceGroup CASCADE CONSTRAINTS;
DROP TABLE Content CASCADE CONSTRAINTS;
DROP TABLE ContentRelation CASCADE CONSTRAINTS;
DROP TABLE Property CASCADE CONSTRAINTS;
DROP TABLE OrganizationalText CASCADE CONSTRAINTS;
DROP TABLE Activity CASCADE CONSTRAINTS;
DROP TABLE Tool CASCADE CONSTRAINTS;
DROP TABLE banner CASCADE CONSTRAINTS;
DROP TABLE ContentResource CASCADE CONSTRAINTS;
DROP TABLE DataSet CASCADE CONSTRAINTS;
DROP TABLE DatasetMember CASCADE CONSTRAINTS;
DROP TABLE Classifier CASCADE CONSTRAINTS;
DROP TABLE ClassifierContent CASCADE CONSTRAINTS;
DROP TABLE classification CASCADE CONSTRAINTS;
DROP TABLE ClassifierTemplate CASCADE CONSTRAINTS;
DROP TABLE DataSetClassifier CASCADE CONSTRAINTS;
DROP TABLE MemberClassification CASCADE CONSTRAINTS;
DROP TABLE AttributeTemplate CASCADE CONSTRAINTS;
DROP TABLE idoc CASCADE CONSTRAINTS;
DROP TABLE IDOCSection CASCADE CONSTRAINTS; 
DROP TABLE IDOCSectionResource CASCADE CONSTRAINTS;
DROP TABLE Notification CASCADE CONSTRAINTS;
DROP TABLE Drb_Question CASCADE CONSTRAINTS;
DROP TABLE Drb_Answer CASCADE CONSTRAINTS;
DROP TABLE KComment CASCADE CONSTRAINTS;
DROP TABLE Vote CASCADE CONSTRAINTS;
DROP TABLE Report CASCADE CONSTRAINTS;
DROP TABLE ContentStat CASCADE CONSTRAINTS;
DROP TABLE ContentProperties CASCADE CONSTRAINTS;
DROP TABLE Gallery CASCADE CONSTRAINTS;
DROP TABLE GalleryFile CASCADE CONSTRAINTS;
DROP TABLE OrgChart CASCADE CONSTRAINTS;
DROP TABLE kb_Subscription CASCADE CONSTRAINTS;
DROP TABLE WorkflowActivity CASCADE CONSTRAINTS;
DROP TABLE entitymatching CASCADE CONSTRAINTS;
DROP TABLE UserLabel CASCADE CONSTRAINTS;

DROP TABLE INQ CASCADE CONSTRAINTS;
DROP TABLE OUTQ CASCADE CONSTRAINTS;
DROP TABLE QUEUE CASCADE CONSTRAINTS;
DROP TABLE OCRLOG CASCADE CONSTRAINTS;

DROP TABLE RioProfile CASCADE CONSTRAINTS;

DROP PROCEDURE createDomain;

DROP TABLE USERLABEL CASCADE CONSTRAINTS;
DROP TABLE RIOPROFILE CASCADE CONSTRAINTS;
DROP TABLE ENTITYCLASSIFICATION CASCADE CONSTRAINTS;
DROP TABLE ENTITYCLASSIFIER CASCADE CONSTRAINTS;





