-- Email Templates-----------
delete from kb_email_template;
INSERT INTO kb_email_template (id, lastmodifieduser,  state, domain_id, lang, xkey, title, fromstr, subject, strtext) VALUES (1, 1, 1, 1, 'en', 'welcome', 'Welcome to RPDM', '${domain-noreply}' , 'Welcome to RealPage Document Management - ${domain-name}', '<p>${person-displayname},</p><p>Welcome to <b>RealPage Document Management (RPDM)</b>!. RPDM is an enterprise document management solution designed to meet the enterprise document management needs of any size property management company. RPDM allows you store documents for all areas of your business while having the ability to restrict access by user so you can give view only access to investors and auditors or control access by document type. Never lose a document again, RPDM superior search functionality will help you find in seconds any document ever stored.</p><p>Your username is: <b>${username}</b></p><p>To set up your account password, please visit the link below and follow the instructions:</p><p>${url}</p><p>To view training on this product, please visit the link below:<br /><br /> https://www.realpagelearning.com/v5/ </p>');
INSERT INTO kb_email_template (id, lastmodifieduser,  state, domain_id, lang, xkey, title, fromstr, subject, strtext) VALUES (8, 1, 1, 1, 'en', 'forgot-username', 'Forgot Username','${domain-noreply}'  , 'Username for ${domain-name} - RPDM'  , '<p>${person-displayname},</p><p>We have received your request to send your RPDM username. <br/>We have the following user account associated to the email address and phone:</p><p>Email: ${person-email-address}<br/>Phone: ${person-phone-last-four-digits}</p><p>User Account: ${user-username}</p>');
INSERT INTO kb_email_template (id, lastmodifieduser,  state, domain_id, lang, xkey, title, fromstr, subject, strtext) VALUES (9, 1, 1, 1, 'en', 'admin-sends-reset-password', 'Password Reset', '${domain-noreply}' , 'Password Reset for ${domain-name} - RPDM', '${person-displayname},<br/><p>The Admin user has sent you this link to reset your account password. Please visit the link below and follow the instructions:</p><p>${url}</p> <p>For security reasons, this link will expire in 72 hours after your initial request was made.</p>');
INSERT INTO kb_email_template (id, lastmodifieduser,  state, domain_id, lang, xkey, title, fromstr, subject, strtext) VALUES (7, 1, 1, 1, 'en', 'forgot-password',   'Password Reset'  , '${domain-noreply}', 'Password Reset for ${domain-name} - RPDM','<p>${person-displayname},</p><p>We have received your request to reset your account password. Please visit the link below and follow the instructions to reset your password:</p><p>${url}</p><p>For security reasons, this link will expire in 72 hours after your initial request was made. If you did not request to reset your password, you can safely ignore this email.</p>');
INSERT INTO kb_email_template (id, lastmodifieduser,  state, domain_id, lang, xkey, title, fromstr, subject, strtext) VALUES (2, 1, 1, 1, 'en', 'send-email', 		 'Send by Email'   , '${from}',      '${title} - RPDM'  , '${text}');
INSERT INTO kb_email_template (id, lastmodifieduser,  state, domain_id, lang, xkey, title, fromstr, subject, strtext) VALUES (6, 1, 1, 1, 'en', 'alert-rule-publish',  'Alert Notification'  , '${domain-noreply}', '${event-name} - ${file-title} - RPDM'  , '<p>${person-display-name} has published: ${file-title}</p> <p>Please go to Library at ${url} to retrieve additional information about this file.</p>');
INSERT INTO kb_email_template (id, lastmodifieduser,  state, domain_id, lang, xkey, title, fromstr, subject, strtext) VALUES (3, 1, 1, 1, 'en', 'assign-task',  'New Task'  , '${from}'  , '${title} - ${task-name} - RPDM'  , '<p>${from-displayname} has assigned the following task:</p><p>Task: ${task-name} <br/> File: ${title}.</p><p>Please go to <a href="${url}">My Tasks</a> to retrieve additional information about this file.</p><p>Comment:<br/>${comment}</p>');
INSERT INTO kb_email_template (id, lastmodifieduser,  state, domain_id, lang, xkey, title, fromstr, subject, strtext) VALUES (4, 1, 1, 1, 'en', 'reassign-task-receiver',   'Reassign task receiver'          , '${from}'  , '${task-name} - ${title} - RPDM'  , '<p>{from-displayname} has assigned the following task: ${task} - ${title}.<br/>Please go to My Tasks at ${url} to retrieve additional information about this file.</p><p>Comment:<br/>${comment}</p>');
INSERT INTO kb_email_template (id, lastmodifieduser,  state, domain_id, lang, xkey, title, fromstr, subject, strtext) VALUES (5, 1, 1, 1, 'en', 'reassign-task-former-owner',  'Reassign task former owner'   , '${from}'  , '${task-name} - ${title} - RPDM'  , '<p>{from-displayname} has assigned the following task: ${task} - ${title}.<br/>Please go to My Tasks at ${url} to retrieve additional information about this file.</p><p>Comment:<br/>${comment}</p>');
INSERT INTO kb_email_template (id, lastmodifieduser,  state, domain_id, lang, xkey, title, fromstr, subject, strtext) VALUES (10, 1, 1, 1, 'en', 'db-export',   'DB Export'  , '${domain-noreply}', 'DB Export for ${domain-name} - RPDM','<p>${person-displayname},</p><p>Your database export is ready.<br />You can download it as a zip file from this link:</p><p>${url}</p><p>For security reasons, this link will expire in 10 days after your initial request was made.</p>');																												
INSERT INTO kb_email_template (id, lastmodifieduser,  state, domain_id, lang, xkey, title, fromstr, subject, strtext) VALUES (11, 1, 1, 1, 'en', 'newdomain',  'New Domain'  , '${from}', 'New Domain ${domain-name} - RPDM','<p>${person-displayname},</p><p>New Domain created: ${domain-name}</p>');



