
default=Default
default-subject=Default

reassign-task-former-owner=Task - reassigned former user
reassign-task-former-owner-subject=${content.title} - ${task-displayname} - Reassign - ${application-name}

assign-task=Task - Assigned
assign-task-subject=${content.title} - ${activity.task.displayname} - ${application-name}

task-progress-note=Task - Progress Note
task-progress-note-subject=Note - ${content.title} - ${activity.task.displayname} - ${application-name}


pending-task=Task - Pending
pending-task-subject=${content.title} - Pending - ${application-name}

timeout-task=Task - Expired
timeout-task-subject=${content.title} - Task Expired - ${application-name}
			
send-email=Content - Send by email
send-email-subject=${content.title} - ${application-name}

welcome=Security - Welcome
welcome-subject=Bienvenido a ${application-fullname} - Information

forgot-password=Security - Forgot Password
forgot-password-subject=Reset password - ${application-name}

forgot-username=Security - Forgot Username
forgot-username-subject=Forgot Username - ${application-name}


admin-sends-reset-password=Security - Reset Password - Admin
admin-sends-reset-password-subject=Reset Password - ${application-name}

register-device=Security - Register Mobile Device
register-device-subject=${application-name} - Register mobile device

alert-rule-publish=Content - Publish
alert-rule-publish-subject= Publish - ${application-name}

newdomain=Factory - New Domain
newdomain-subject=New Domain ${domain-name} - ${application-name}

send-token=Security - Security Code
send-token-subject=${application-name} - Security Code


db-export=Content - Export
db-export-subject=${application-name} - Export DB



due-date-notification-task=Task - Due Date
due-date-notification-task-subject=Due Date - ${content.title} - ${activity.task.displayname} - ${application-name}











xassign-task={"name":"Modelo","type":"COMPOUND","dataSet":null,"description":"Modelo del template para la generación de la notificación de un evento de inicio de tarea","multiplicity":null,"elements":[ \
		{"name":"activity","type":"ACTIVITY","dataSet":null,"description":null,"multiplicity":null,"elements":[]},\
		{"name":"content","type":"CONTENT","dataSet":null,"description":null,"multiplicity":null,"elements":[]},\
		{"name":"previousactivity","type":"ACTIVITY","dataSet":null,"description":null,"multiplicity":null,"elements":[]},\
		{"name":"receiver","type":"USER","dataSet":null,"description":null,"multiplicity":null,"elements":[]}]}

xtask-progress-note={"name":"Modelo","type":"COMPOUND","dataSet":null,"description":"Modelo del template para la generación de la notificación de un evento de una nueva nota de avance en una tarea en ejecución","multiplicity":null,"elements":[\
		{"name":"activity","type":"ACTIVITY","dataSet":null,"description":null,"multiplicity":null,"elements":[]},\
		{"name":"content","type":"CONTENT","dataSet":null,"description":null,"multiplicity":null,"elements":[]}]}

xpending-task={"name":"Modelo","type":"COMPOUND","dataSet":null,"description":"Modelo del template para la generación de la notificación de una nueva tarea pendiente a los usuarios con permiso de tomarla","multiplicity":null,"elements":[\
		{"name":"task","type":"TASK","dataSet":null,"description":null,"multiplicity":null,"elements":[]},\
		{"name":"previousactivity","type":"ACTIVITY","dataSet":null,"description":null,"multiplicity":null,"elements":[]},\
		{"name":"content","type":"CONTENT","dataSet":null,"description":null,"multiplicity":null,"elements":[]},\
		{"name":"receiver","type":"USER","dataSet":null,"description":null,"multiplicity":null,"elements":[]}]}
	
xsend-email={"name":"Modelo","type":"COMPOUND","dataSet":null,"description":"Modelo del template para la generación del texto para el email de envío de documento","multiplicity":null,"elements":[\
		{"name":"content","type":"CONTENT","dataSet":null,"description":null,"multiplicity":null,"elements":[]},\
		{"name":"comment","type":"STRING","dataSet":null,"description":null,"multiplicity":null,"elements":[]},\
		{"name":"sender","type":"USER","dataSet":null,"description":null,"multiplicity":null,"elements":[]}]}	



xnewdomain					=	{"name":"Modelo","type":"COMPOUND","dataSet":null,"description":"forgot-password","multiplicity":null,"elements":[]}
xforgot-password				=	{"name":"Modelo","type":"COMPOUND","dataSet":null,"description":"forgot-password","multiplicity":null,"elements":[]}
xwelcome						=	{"name":"Modelo","type":"COMPOUND","dataSet":null,"description":"welcome","multiplicity":null,"elements":[]}
xreassign-task-former-owner	=	{"name":"Modelo","type":"COMPOUND","dataSet":null,"description":"reassign-task-former-owner","multiplicity":null,"elements":[]}
xtimeout-task				=	{"name":"Modelo","type":"COMPOUND","dataSet":null,"description":"timeout-task","multiplicity":null,"elements":[]}
xadmin-sends-reset-password	=	{"name":"Modelo","type":"COMPOUND","dataSet":null,"description":"admin-sends-reset-password","multiplicity":null,"elements":[]}
xalert-rule-publish			=	{"name":"Modelo","type":"COMPOUND","dataSet":null,"description":"alert-rule-publish","multiplicity":null,"elements":[]}

xregister-device={"name":"Modelo","type":"COMPOUND","dataSet":null,"description":"Variables y macros para el armado del texto del mail que se envía para el registro de un dispositivo","multiplicity":null,"elements":[\
		{"name":"device","type":"DEVICE","dataSet":null,"description":null,"multiplicity":null,"elements":[]}]}	
	

		
	