

iql=Files to publish in Portal
home=Home
info=Info
pages=Pages
content=Content
menus=Menus
security=Security
reports=Reports
integrations=Integrations
search=Search
status=Status
audit=Audit
topsection=Top Section
bottomsection=Bottom Section


