
home=Home
sections=Site Sections
add-page=add page
site-sections=Site Sections
open-site-sections=Open Site Sections
pages=Pages
not-buildable=<span class="highlight">read only</span>
									
									
									
									
									
									
