notsameclass-message = In order to execute a Bulk Edit all selected contents must execute the same <b>Precedure.Task</b> and belong to the same <b>Content Template</b>. <br />Please check the selection in the table below. 
contents = Contents
classifiers = Attributes
close = Close
execute = Execute
grid.title = Title
classify = Edit Contents
actions=Actions
back=< Back to My Tasks

howitworkstitle=How it Works
howitworks=<p>If you select Attributes, it will assign the chosen value to each file you have selected.<br />If you select <i>Leave Existing Values</i>, it will leave the previously selected values for that file.<br />If you have not selected a value, it will display <i>None</i>. <br />Attributes that depend on other attributes will be updated automatically.</p>



grid.title=Title
grid.task=Business Process. Task
grid.class=Content Template