



alert=Alert
alerts=Alerts

role=Role
library=Library
dataset=DataSet
template=Content Template

template-reference = Content Template {0}
role-reference = Role {0}
dataset-reference = DataSet {0}
alert-reference = Alert {0}
library-reference = Library {0}

