
signin=Login
lastname=Last Name
firstname=First Name
username=Username
login=Login
publish=Publish
taskstart=Task Start
taskend=Task End
lasttaskend=Last Task End Date
edit=Edit
downloadgrid=Download Grid
