property.dataSet=Dataset
subset=1. Values

property.condition=Set of Dataset Values to tag (IQL Condition)
tag.help=This selector includes all Tags from the Dataset selected above
tag-member.help=This selector includes Tags (Attributes and Classifiers) from the Dataset selected above