
execute=Execute
apply=2. Action

property.condition=Items to tag (IQL Condition)  
condition.help=Items that evaluate true to the IQL Condition will be edited 

property.datasetMember=Value
property.tag=Tag

property.classifier=Tag

datasetMember.help=New Value to by applied by the command  

property.actionSelector=Action Type
execute=Execute

contents=Files 
members=Dataset Values
users=Users

override=Replace
append=Add

howto-criteria=How to express a Criteria

requiredvalidator.message=
not-number = Numerical values only
IqlValidator = Syntax error


tag.help=This selector includes all Tags from the Content Template/DataSet selected above
apply.help=Replace: Replace existing value. Add: Add value to existing value/s. Remove: Remove selected tag
