actionName=Change Attribute or Classifier

property.macroSwitch=Use Macro (Advanced)
property.tagOperation=Action
action.help=<b>Replace</b>. Replace existing value/s with "Tag Value" selected above.<br/> <b>Add</b>. Add "Tag Value" selected above to existing value/s. <br/><b>Remove</b>. Remove all existing values.
tag.help=This selector includes all possible Attributes and Classifiers

property.tagType=Tag Type
property.tagValue=Value