

mainmenu.tag-management-tool=Tag Management tool
mainmenu.retention-policy-rules=Retention Policy
mainmenu.time-depemdant-actions=Time Based Alerts


mainmenu.time-dependent-actions=Time Based Alerts


mainmenu.home = Home


mainmenu.email-templates=Email Templates

mainmenu.tasks = Tasks
mainmenu.tasks.mytasks = My Tasks
mainmenu.tasks.monitor = Monitor

mainmenu.tasks.pendings = Pending Tasks

mainmenu.tasks.uploadandcreate = Bulk Upload
mainmenu.tasks.dashboard=Dashboard

mainmenu.integration=File Server


mainmenu.settings = Settings

mainmenu.management = Service Management

mainmenu.content = Content
mainmenu.content.library = Libraries
mainmenu.content.archive = Archive
mainmenu.content.recyclebin = Recycle Bin

mainmenu.datasetvalues = Dataset Values
mainmenu.scheduler=Scheduler

mainmenu.file-explorer=File Explorer
mainmenu.deploy-management=Deploy Manager

			
mainmenu.integration = Integration
mainmenu.file-server = File Server

mainmenu.reports=Reports

mainmenu.settings=Settings

mainmenu.model = Information Model
mainmenu.model.datasets = DataSets
mainmenu.model.classifiers = Classifiers
mainmenu.model.attributes = Attributes
mainmenu.model.classes = Content Templates

mainmenu.security = Security
mainmenu.security.users = Users
mainmenu.security.groups = Groups

mainmenu.systemlogs.treeexplorer=Tree Resources
mainmenu.security.rules = Custom Data Rights
mainmenu.security.roles = Roles

mainmenu.systemlogs = Audit
mainmenu.systemlogs.user = User
mainmenu.systemlogs.content = Find a File
mainmenu.systemlogs.activity = User Activity
mainmenu.systemlogs.email = Email Sent
mainmenu.systemlogs.explorer = Resources
mainmenu.systemlogs.xexplorer = Tree Resources
mainmenu.systemlogs.api=API Integration


mainmenu.portal=Portals
mainmenu.portal.sites = Portal Directory

mainmenu.portal.home = Home
mainmenu.library.home = Knowledge Base Portal

mainmenu.domains = Domain Management
mainmenu.domains.console = Domains
mainmenu.domains.datamanagement = Data Management
mainmenu.domains.commands = Commands

				
mainmenu.domains.scheduler = Scheduler
mainmenu.domains.api=API
mainmenu.domains.info.api.dashboard=API Dashboard
mainmenu.domains.api.soap.report=SOAP Report
mainmenu.domains.api.requests.report=Requests Report

mainmenu.domains.system = System Info
mainmenu.domains.recycle = Domain Recycle Bin

mainmenu.reports.reportsubscriptions=Report Subscription
