
property.to-date = To 
property.from-date = From 
property.from = Sent from 
property.to = Sent to

property.text = Text
property.result = Result

property.range = Sent
property.domain = Domain
apply = Search

1minute = 1 minute
5minutes = 5 minutes
1hour = 1 hour
1day = 1 day
1week = 1 week
1month = 1 month
3months = 3 months
1year = 1 year
all = All