cancel=Close
submit=Submit
sending=Sending

property.name=Name
property.email=Your email
property.message=Message

subject=Contact: 
sent=Your message was sent.
all_fields=Please complete all fields.

email_body=Message from: <b> {0}</b> ({1})\n 	{2}\n\n

