
users=Users

username=Username
email=Email Address

phone=Mobile Phone
device=Device App

mainmenu.loggedas=Signed in as <strong>{0}</strong>
home=My Dashboard

user-workspace=Workspace
workspace-dashobard=Dashboard
