editor.resolution = {0} Resolution
editor.resources = Resources
editor.history = Process History
editor.abstract = Notes
editor.private = Internal Information
editor.audit = Audit Trail
editor.roles = Workflow Profiles

button.submit = Send
button.submiting = Sending...

editor.info=Attributes
 
showtask=Show Task
hidetask=Hide Task

editor.customattributes=Custom Tags


 
