editor.resources = Resources
editor.abstract = Notes
editor.private =  Internal Information
editor.audit = Audit Trail
button.submit = Send
button.submiting = Sending...

editor.process.history=Process History


editor.info = Attributes
editor.history = Version Control
editor.version.control=Version Control
editor.library=Library
showtask=Show Task
hidetask=Hide Task
 


modal.audit.title=Audit {0}

editor.customattributes=Custom Tags


editor.history = Version Control