
section=Factory
systemdm=Data Management
system=System
sql=SQL
solr=SolR

reindex=Reindex (Sync)
command=Command
command-bean=Command Bean
ldap=LDAP
export=Export
reindexcommand=Reindex Commands

domaincreation=Domain Creation
file-server-command=File Server Commands

config=Config
cache=Caché
scheduler=Scheduler
log=Log
