contextmenu.restore=Restore


domains-recycle-bin=Domains Recyle Bin

console.label = Domain
console.name = Recycle Bin
console.recycle-bin.label=Recycle Bin

modal.acl.title = ACL
modal.sendbyemail.title = Share

open=Open
name=Name


domain=Domain
organization=Organization
type=Type
status=Status
quota=Quota
harddisk=Hard Disk Usage (local)
monthlyusage= Monthly Avg (est)
created=Created
modified=Modified Date
user=User
id=ID
username=User
percentage=Usage %
template=Domain Class
yes=<span class="no">Yes</span>
no=<span class="yes">No</span>


archive=Set Status: <span class="archived">Archived</span>
enable=Set Status: <span class="enabled">Enabled</span>

resetrootpassword=Reset Root Password

type.enterprise=Set Type: <span class="enterprise">Standard</span> 
type.express=Set Type: <span class="express">Express</span>


template.enable=Set Class: <span class="template">Template</span>
template.disable=Set Class: <span class="standard">Standard</span>

is-template =<span class="template">Template</span>
is-standard = <span class="standard">Standard</span>
