
version=Version
configuration=Configuration
system.parameters=System Parameters
properties=JVM Properties
mainmenu.api.dashboard=Tablero de Control API
mainmenu.api.dashboard=API Dashboard
mainmenu.hardware.os=Hardware and OS
systeminfo=System Information
property.name=Name

settings=Settings
content-type=Document Type
entities=Entities
switch-sides=Switch sides
relevance=Relevance

phone=Mobile Phone
my-app=Mobile App

disabled=Disabled
lastexecution.label = Last Execution
nextexecution.label = Next Execution

edit=Edit
save=save
recurrent-rule=Recurrent Task
recurrent-rules=Recurrent Tasks
system-parameters=System Parameters
system-monitor=Ping

database=Database
search-platform=Search Platform
search=Search
execute=Execute
sign-as-root=Sign as root
quick-links=Quick links
tools=Tools
my-email-alerts=My Email Alerts
my-roles=My Roles
user-workspace=Workspace
my-subcriptions=My Subscriptions
subscribe=Subscribe to alerts
unsubscribe=Unsubscribe

signature=Signature
add-tag=Add tag
modal.audittrail.title=Audit
reassign-to-me=Reasign to me
reassign=Reassign
download=Download
share=Share
priority=Priority
activity = User activity

eform=Form
audit=Audit


css=Css
open-portal=Open portal
actions=Actions 
support=Support


draft-folder=My Resources
my-draft-folder=My Resources
draft-folder-public=Shared Resources
 
search-in-public-drafts=Search in Shared Resources 


alerts=Alerts
sites=Portals
eforms=Forms
yes=Yes
no=No

publish=Publish
return-caller=Return to Caller
js-script=JS Script
if-condition-falis=if condition fail
initial=Initial
new-task=New Task



user-or-group=User or Group
readonly=read-only

cancel=Cancel
task-actions=Task actions
custom-tags=Custom tags
control=Control
info=Info
content=Content


externalid=External ID
close=close
cache=Cache
thumbnail=Thumbnail
view=View
show-deleted=Show Deleted
built-in=Built in
references=References


cronjobs=Cronjobs
execute-request=Execute Request

scheduler=Scheduler
reindex=Reindex
not-authorized-text=Not authorized
emailtemplate=Email Template
emailtemplates=Email Templates
role=Role
contenttemplates=Content Templates
alert=Alert
billboard=Billboard
working=Working

dataset.batchcreation=Dataset Batch Creation

command.recentactivity=Dashboard
command.sql=SQL Client
command.cleanindex=Clean Index
command.commands=Commands
command.execute.name = Execute Command
command.solr=Solr Client
command.cache=Cache
command.serverinfo=Server Info
command.scheduler=Scheduler

sysmessage.sysmessages = System Messages
sysmessage.add =Add

#--------------------------------------------------------------------------------------------------------------
#Main menu

mainmenu.mynotes=My Notes
mainmenu.directory=Directorio de Sitios
mainmenu.portalhome=Portada
mainmenu.work-notes=Billboard and Manual Alerts
mainmenu.workspace = My Tasks
mainmenu.contentbase = Library
mainmenu.pendings = Pending Tasks
mainmenu.templates=Templates
mainmenu.monitor = Monitor
mainmenu.recyclebin = Recycle Bin
mainmenu.scheduler=Scheduler
mainmenu.templates = Templates
mainmenu.archive = Archive
mainmenu.all = All
mainmenu.datamanagement=Data Management
mainmenu.datamanagement.deprecated = Data Management (deprecated)

domains=Domains
mainmenu.domains=Domains
mainmenu.domains-recycle-bin=Domain Recycle Bin

mainmenu.reports=Reports

mainmenu.domains.commands=Commands

mainmenu.sqlgateway=SQL Gateway
mainmenu.settings=Settings
mainmenu.domain.settings=General Settings
mainmenu.domain.emailtemplates=Email Templates
mainmenu.domain.cabinets = Libraries 

mainmenu.domain.sources = Sources
mainmenu.tag-management-tool=Tag Management tool

grid-configuration=Grid Configuration

mainmenu.domaininformation=Domain Information



mainmenu.informationmodel = Information Model
mainmenu.informationmodel.enotirules = My Email Notification Rules
mainmenu.informationmodel.domainsettings=General
mainmenu.informationmodel.datasets = DataSets
mainmenu.informationmodel.classifiers = Classifier
mainmenu.informationmodel.domains = Domains
mainmenu.informationmodel.templates = Content Template

mainmenu.reports=Reports

mainmenu.analytics = Analytics
mainmenu.exit = Log Out

mainmenu.datasets = Dataset Values
mainmenu.domainsettings = Domain Settings
mainmenu.domain = Domain
mainmenu.general=General
mainmenu.settings=Settings

mainmenu.filedit=Local File Edit
mainmenu.domains=Domains
mainmenu.commands=Commands

mainmenu.sysmessages=System Messages
mainmenu.sysadmin = Admin

mainmenu.systeminfo = System Information
mainmenu.datamanagement = Data Management
mainmenu.support=Support

mainmenu.filedit=Edit local file

mainmenu.domains.api.soap.report= SOAP Report
mainmenu.domains.api.requests.report= Requests Report
mainmenu.domains.api=API

mainmenu.domains.api.dashboard=Dashboard
mainmenu.domains.info.api.dashboard=API Dashboard


mainmenu.domains.api.requests.stats=Daily Stats

bc.labels=Labels
mainmenu.domainadmin=Labels
mainmenu.labels=Labels

mainmenu.security = Security
mainmenu.security.users = Users
mainmenu.security.groups = Groups
mainmenu.security.rules = Custom Data Rights
mainmenu.security.roles = Roles


mainmenu.systemlogs = System Logs

mainmenu.systemtools.commands=Commads
mainmenu.systemtools.sysmessages=System Messages
mainmenu.systemtools = System Tools
mainmenu.systemtools.recyclebin = Recycle Bin

mainmenu.systemtools.systemlog = Audit
mainmenu.systemtools.emaillog = Email
mainmenu.systemlog = Audit
mainmenu.systemtools.resourceexplorer=Resources 
mainmenu.systemtools.sites=Portals

mainmenu.systemtools.filefinder=File Finder
mainmenu.systemtools.myactivity = My Activity

mainmenu.systemtools.sysadmin = System Administration

mainmenu.myemailrules=Workflow Alerts

working=Working

mainmenu.myaccount = User Settings
mainmenu.qa = Dr Bit
mainmenu.showmetip=Show a Tip of the Day

mainmenu.myaccount.resetpreferences=Repair My Workspace
mainmenu.myaccount.enable-notifications=Enable Email Alerts


#--------------------------------------------------------------------------------------------------------------
#kbee consoles

workspace = My Tasks
content-base = Templates
monitor = Monitor
security = Security
systemtools = System Tools
resources-explorer=File Server






groups=Groups
#--------------------------------------------------------------------------------------------------------------
#kbee footer
kbee.footer.about = About
kbee.footer.tutorial = Tutorial
kbee.footer.contact = Contact
kbee.footer.copyright = (c) 2004 - {0}. Novamens


#--------------------------------------------------------------------------------------------------------------
#SearchPanel
searchpanel.defaultlabel = Search


#--------------------------------------------------------------------------------------------------------------
#Notification
kbee.social.comment.notification.title = Comment to content 
kbee.social.comment.notification.msg = {0} added a comment to a content you follow: {1}
  
kbee.social.answer.notification.title = Answer to: {0}
kbee.social.answer.notification.msg = {0} answer to your question {1}: {2}

kbee.social.comment.report.feedback =The comment was sent to review. <br />Thanks for your help to improve the quality of the site.
kbee.social.answer.report.feedback =The answer was sent to review. <br />Thanks for your help to improve the quality of the site.
kbee.social.question.report.feedback =The question was sent to review. <br />Thanks for your help to improve the quality of the site.

kbee.social.vote.feedback = Thanks for your vote!

#--------------------------------------------------------------------------------------------------------------
#Security

kbee.security.rules.deletionalert =Borra la/s Regla de Permisos seleccionada/s?

#--------------------------------------------------------------------------------------------------------------
console.toolbar.order-action = Order.
console.toolbar.content-layout = Content

console.toolbar.view-mode-action=View Mode

# QA ------------------------------------------------------------------------------------------------------------
#
#
# QAHome
qa.home.searchpanel.defaultlabel = Search subject or question

qa.home.stat.title = Stats
qa.stat.users.label = Users
qa.stat.answers.label = Answers
qa.stat.questions.label = Questions

# Contact
qa.tutorial.title = Tutorial
qa.contact.title = Contact

# Contact followup
contact.msg-sent = Su mensaje fue enviado con óxito!
contact.followup = Gracias por tomarse el tiempo de contactarnos.

#Question submitted followup
qa.question-sent.home=Ir a la Portada
qa.question-sent.breadcrumb=Consulta Enviada
qa.question-sent.text-ok = Su consulta fue enviada con óxito! 
qa.question-sent.text-followup  = Le enviaremos notificaciones por correo cuando haya respuestas o comentarios.

# QA Footer
qa.footer.about=About
qa.footer.tutorial=Tutorial
qa.footer.contact=Contact

# QA Results Page 			
qa.results.votes =Votes: {0}.
qa.results.answers =Answers: {0}.
qa.results.noanswers =No answers yet.
qa.results.created = {0}.
qa.results.date-modified = Last modified: {0}.
qa.results.question-state = {0}.

# QA Answers Panel
qa.answers.no-answers = No answers yet.

# QA Comments Panel
qa.comments.title=Comments
qa.comments.no-comments = No comments.

