editorpage.menu.thumbnails = Thumbnails
editorpage.menu.icons = Icons
editorpage.menu.audit = Audit Trail
editorpage.menu.history = History
editorpage.menu.undo = Undo
editorpage.menu.edit = Edit
editorpage.menu.delete = Delete/Drop Working Copy
editorpage.menu.delete.confirmation = Delete/Drop Working Copy
editorpage.menu.restore = Restore
editorpage.menu.assign = Assign
editorpage.menu.sendtobase = Send to Library